-- ============================================================================
-- all_in_one.lua — 消耗与诱歼作战方案 (单文件版本, CMO 控制台直接粘贴)
--   顺序: 加载 manifest -> main -> clear -> reload -> attack
--   Generated by stage3, 2026-07-06 (重做, 因为 dofile 在 CMO 控制台不可用)
--
-- 使用方法:
--   1. 打开 CMO Lua Console (Ctrl+L)
--   2. 把这个文件全部内容粘贴进去, 点 Run
--   或者:
--   1. 把这个文件放到 [CMANO Game Folder]/Lua/all_in_one.lua
--   2. 在控制台执行: ScenEdit_RunScript("all_in_one.lua")
-- ============================================================================

print("[CMO] [INFO] ============ all_in_one.lua 开始 ============")
print("[CMO] [WARNING] 这是 4 阶段一体化脚本, 一次性建单位+清弹+装弹+调度")

-- ============================================================================
-- 第一部分: MANIFEST 数据 (原 manifest.lua)
-- ============================================================================

CFG_SCENARIO = {
    name                 = "消耗与诱歼作战方案",
    startTime            = "2026-04-10 10:00:00",
    side_red             = "红方",
    side_blue            = "蓝方",
    red_awareness        = "OMNI",
    red_emcon            = "Radar=Active;Sonar=Active;OECM=Active",
    blue_emcon           = "Radar=Active;Sonar=Active;OECM=Active",
    blue_autodetectable  = true,
    contact_settle_delay = 15,
}

CFG_DOCTRINE_RED = {
    weapon_control_status_air        = 0,
    weapon_control_status_surface    = 0,
    weapon_control_status_subsurface = 0,
    weapon_control_status_land       = 0,
}

CFG_DOCTRINE_BLUE = {
    weapon_control_status_air        = 0,
    weapon_control_status_surface    = 2,
    weapon_control_status_subsurface = 2,
    weapon_control_status_land       = 0,
}

UNITS = {}

UNITS["red_ddg_1"] = { side = "红方", type = "Ship", dbid = 3883, name = "red_ddg_1", lat = "30.25", lon = "124.75", altitude = "0", name_en = "Type 055 Renhai [101 Nanchang]" }
UNITS["red_ddg_2"] = { side = "红方", type = "Ship", dbid = 2296, name = "red_ddg_2", lat = "29.75", lon = "125.25", altitude = "0", name_en = "Type 052D Luyang III [172 Kunming]" }
UNITS["red_sub_1"] = { side = "红方", type = "Submarine", dbid = 124, name = "red_sub_1", lat = "30.0", lon = "126.0", altitude = "60", name_en = "Type 039G1 Song" }
UNITS["red_ac_1"]  = { side = "红方", type = "Aircraft", dbid = 2853, loadout_id = 1821, name = "red_ac_1", lat = "29.0", lon = "123.5", altitude = "7620", name_en = "J-16 Flying Shark" }
UNITS["red_ew_1"]  = { side = "红方", type = "Aircraft", dbid = 343,  loadout_id = 102,  name = "red_ew_1", lat = "28.5", lon = "124.0", altitude = "9144", name_en = "EA-18G Growler" }
UNITS["blue_ddg_1"] = { side = "蓝方", type = "Ship", dbid = 112, name = "blue_ddg_1", lat = "28.833", lon = "126.333", altitude = "0", name_en = "DDG-51 Arleigh Burke Flight I" }
UNITS["blue_ddg_2"] = { side = "蓝方", type = "Ship", dbid = 797, name = "blue_ddg_2", lat = "28.5", lon = "126.667", altitude = "0", name_en = "DDG-51 Arleigh Burke Flight I" }
UNITS["blue_aux_1"] = { side = "蓝方", type = "Ship", dbid = 26, name = "blue_aux_1", lat = "28.167", lon = "126.833", altitude = "0", name_en = "T-AO 187 Henry J. Kaiser" }

CLEAR_LIST = { "red_ddg_1", "red_ddg_2", "red_sub_1", "red_ac_1", "red_ew_1" }

AMMO = {
    { unitname = "red_ddg_1", wpn_dbid = 2868, number = 4 },  -- YJ-18
    { unitname = "red_sub_1", wpn_dbid = 2868, number = 4 },  -- YJ-18
    { unitname = "red_ac_1",  wpn_dbid = 541,  number = 2 },  -- YJ-83
}

STRIKE = {
    { attacker = "red_ac_1",  target = "blue_ddg_1", wpn_dbid = 541,  qty = 2, startDelay = 3900, interval = 60, tag = "red_ac_1_l1_4" },
    { attacker = "red_sub_1", target = "blue_ddg_1", wpn_dbid = 2868, qty = 4, startDelay = 3900, interval = 60, tag = "red_sub_1_l1_5" },
    { attacker = "red_ac_1",  target = "blue_ddg_2", wpn_dbid = 541,  qty = 2, startDelay = 3900, interval = 60, tag = "red_ac_1_l2_4" },
    { attacker = "red_ac_1",  target = "blue_aux_1", wpn_dbid = 541, qty = 2, startDelay = 3900, interval = 60, tag = "red_ac_1_l3_4" },
}

PATROLS = {
    { platform = "red_ew_1", type = "SEAD", subtype = "SEAD", zone_name = "EW_PATROL_ZONE",
      rps = { "RP-EW-1", "RP-EW-2", "RP-EW-3", "RP-EW-4" }, start_time = "2026-04-10 10:00:00", duration_seconds = 6300 },
}

REFERENCE_POINTS = {
    { side = "红方", name = "RP-EW-1", lat = "27.0", lon = "123.0" },
    { side = "红方", name = "RP-EW-2", lat = "27.0", lon = "125.0" },
    { side = "红方", name = "RP-EW-3", lat = "30.0", lon = "125.0" },
    { side = "红方", name = "RP-EW-4", lat = "30.0", lon = "123.0" },
}

VICTORY = { red_winning_threshold = 70, description = "蓝方护航编队被毁伤 ≥ 70% = 红方胜" }

-- helper
function table_count_keys(t)
    local n = 0
    for _ in pairs(t) do n = n + 1 end
    return n
end

print("[CMO] [INFO] MANIFEST 加载完成: " ..
    "UNITS=" .. table_count_keys(UNITS) .. ", " ..
    "CLEAR_LIST=" .. #CLEAR_LIST .. ", " ..
    "AMMO=" .. #AMMO .. ", " ..
    "STRIKE=" .. #STRIKE .. ", " ..
    "PATROLS=" .. #PATROLS .. ", " ..
    "REFERENCE_POINTS=" .. #REFERENCE_POINTS)

-- ============================================================================
-- 第二部分: STEP 1 — 创建单位 (原 main.lua)
-- ============================================================================
print("")
print("[CMO] ============ STEP 1/4: 创建单位 ============")

local function log(level, msg) print("[CMO] [" .. level .. "] " .. tostring(msg)) end
local function info(msg)  log("INFO",    msg) end
local function warn(msg)  log("WARNING", msg) end
local function ok(msg)    log("SUCCESS", msg) end

local function sideExists(name)
    return pcall(VP_GetSide, { Side = name })
end

local function ensureSide(name, color)
    if sideExists(name) then
        info("阵营已存在: " .. name)
        return true
    end
    pcall(ScenEdit_AddSide, { name = name, color = color })
    ok("阵营创建: " .. name)
    return true
end

ensureSide(CFG_SCENARIO.side_blue, "128,128,255")
ensureSide(CFG_SCENARIO.side_red,  "255,64,64")
pcall(ScenEdit_SetSidePosture, CFG_SCENARIO.side_red,  CFG_SCENARIO.side_blue, "H")
pcall(ScenEdit_SetSidePosture, CFG_SCENARIO.side_blue, CFG_SCENARIO.side_red,  "H")
ok("红方/蓝方 关系: Hostile")

local function addUnitFromManifest(uid)
    local u = UNITS[uid]
    if not u then warn("manifest 缺单位: " .. uid); return end
    local props = {
        side = u.side, type = u.type, name = u.name,
        dbid = u.dbid, lat = u.lat, lon = u.lon,
    }
    if u.type == "Aircraft" then
        props.Altitude = u.altitude       -- CMO API 用 Altitude (大写 A)
        props.LoadoutID = u.loadout_id   -- 必须有 LoadoutID (MCP 查 DataAircraftLoadouts)
        props.proficiency = "Regular"
    elseif u.type == "Ship" then
        props.proficiency = "Veteran"
    elseif u.type == "Submarine" then
        props.proficiency = "Regular"
    end
    if u.side == CFG_SCENARIO.side_blue and CFG_SCENARIO.blue_autodetectable then
        props.autodetectable = true
    end
    -- 检查关键字段
    if type(props.Altitude) ~= "number" and type(props.altitude) ~= "number" then
        props.Altitude = tonumber(u.altitude) or 5000  -- fallback
    end
    _errnum_ = 0
    _errmsg_ = ""
    pcall(ScenEdit_AddUnit, props)
    if (_errnum_ or 0) ~= 0 then
        warn("AddUnit 失败 " .. uid .. " | err=" .. tostring(_errmsg_) ..
             " | lat=" .. tostring(u.lat) .. " (type=" .. type(u.lat) ..
             ") | lon=" .. tostring(u.lon) .. " (type=" .. type(u.lon) .. ")")
        -- 尝试自动转换 lat/lon 为数字
        props.lat = tonumber(u.lat) or 0
        props.lon = tonumber(u.lon) or 0
        _errnum_ = 0
        _errmsg_ = ""
        pcall(ScenEdit_AddUnit, props)
        if (_errnum_ or 0) ~= 0 then
            warn("AddUnit 重试仍失败 " .. uid .. " | err=" .. tostring(_errmsg_))
            return
        end
        ok(("AddUnit %s (lat/lon 转数字重试成功)"):format(uid))
    end
    -- 立即验证
    local verify = ScenEdit_GetUnit({ side = u.side, name = u.name })
    if verify and verify.guid then
        ok(string.format("%-15s | %s | %-10s | dbid=%-5d @ (%s, %s) GUID=%s",
            uid, u.side, u.type, u.dbid, u.lat, u.lon, verify.guid))
    else
        warn(("添加后查不到 %s"):format(uid))
    end
end

addUnitFromManifest("red_ddg_1")
addUnitFromManifest("red_ddg_2")
addUnitFromManifest("red_sub_1")
addUnitFromManifest("red_ac_1")
addUnitFromManifest("red_ew_1")
addUnitFromManifest("blue_ddg_1")
addUnitFromManifest("blue_ddg_2")
addUnitFromManifest("blue_aux_1")

-- Doctrine
pcall(ScenEdit_SetDoctrine, { side = CFG_SCENARIO.side_red }, CFG_DOCTRINE_RED)
ok("红方 Doctrine: 全部 WCS=Free")
pcall(ScenEdit_SetDoctrine, { side = CFG_SCENARIO.side_blue }, CFG_DOCTRINE_BLUE)
ok("蓝方 Doctrine: Surface/Subsurface=Hold")

-- EMCON
local function findUnit(side, name)
    local r, s = pcall(VP_GetSide, { Side = side })
    if not r or not (s and s.units) then return nil end
    for _, u in ipairs(s.units) do if u.name == name then return u end end
    return nil
end

for _, uid in ipairs({ "red_ddg_1", "red_ddg_2", "red_sub_1", "red_ac_1", "red_ew_1",
                       "blue_ddg_1", "blue_ddg_2", "blue_aux_1" }) do
    local u = UNITS[uid]
    local unit = findUnit(u.side, u.name)
    if unit and unit.guid then
        local emcon = (u.side == CFG_SCENARIO.side_red) and CFG_SCENARIO.red_emcon or CFG_SCENARIO.blue_emcon
        pcall(ScenEdit_SetEMCON, "Unit", unit.guid, emcon)
    end
end
ok("所有 8 个单位 EMCON = Active")

-- 蓝方 autodetectable 双保险
for _, uid in ipairs({ "blue_ddg_1", "blue_ddg_2", "blue_aux_1" }) do
    local u = UNITS[uid]
    local bu = ScenEdit_GetUnit({ side = u.side, name = u.name })
    if bu and bu.guid then
        pcall(ScenEdit_SetUnit, { guid = bu.guid, autodetectable = true })
    end
end
ok("蓝方 3 个单位 autodetectable=true")

-- 红方 OMNI
do
    _errnum_ = 0
    ScenEdit_SetSideOptions({ side = CFG_SCENARIO.side_red, awareness = "OMNI" })
    if (_errnum_ or 0) == 0 then ok("红方 awareness=OMNI") else warn("OMNI 失败") end
end

-- SEAD 巡逻
local rps = PATROLS[1].rps
for i, rp_name in ipairs(rps) do
    local r = REFERENCE_POINTS[i]
    if r then pcall(ScenEdit_AddReferencePoint, { side = r.side, name = r.name, lat = r.lat, lon = r.lon }) end
end
ok("已创建 4 个参考点 (RP-EW-1..4)")

pcall(ScenEdit_AddMission, { side = CFG_SCENARIO.side_red, name = "M04_SEAD", type = "Patrol", subtype = "SEAD" })
pcall(ScenEdit_SetMission, CFG_SCENARIO.side_red, "M04_SEAD", { patrolzone = rps, onethirdrule = false })
local ew = findUnit(CFG_SCENARIO.side_red, "red_ew_1")
if ew and ew.guid then
    pcall(ScenEdit_AssignUnitToMission, { side = CFG_SCENARIO.side_red, unitname = "red_ew_1", mission = "M04_SEAD" })
    ok("red_ew_1 已加入 SEAD 巡逻")
end

print("[CMO] [INFO] ============ STEP 1 完成 ============")

-- ============================================================================
-- 第三部分: STEP 2 — 清弹 (原 clear.lua)
-- ============================================================================
print("")
print("[CMO] ============ STEP 2/4: 清弹 ============")

local function clearUnitWeapons(side, name)
    local u = ScenEdit_GetUnit({ side = side, name = name })
    if not u or not u.guid then warn("找不到 " .. side .. "/" .. name); return false end
    local jobs = {}
    for _, m in ipairs(u.mounts or {}) do
        for _, w in ipairs(m.mount_weapons or {}) do
            local cur = tonumber(w.wpn_current) or 0
            if cur > 0 then jobs[#jobs + 1] = { dbid = w.wpn_dbid, num = cur, mountid = m.mount_guid } end
        end
    end
    local done, fail = 0, 0
    for _, j in ipairs(jobs) do
        _errnum_ = 0
        ScenEdit_AddReloadsToUnit({ guid = u.guid, wpn_dbid = j.dbid, mount_guid = j.mountid, number = j.num, remove = true })
        if (_errnum_ or 0) == 0 then done = done + 1 else fail = fail + 1 end
    end
    ok(("%s: 减载归零 %d 条 (失败 %d)"):format(name, done, fail))
    return fail == 0
end

for _, uid in ipairs(CLEAR_LIST) do
    local u = UNITS[uid]
    if u then clearUnitWeapons(u.side, u.name) end
end

print("[CMO] [INFO] ============ STEP 2 完成 ============")

-- ============================================================================
-- 第四部分: STEP 3 — 装弹 (原 reload.lua)
-- ============================================================================
print("")
print("[CMO] ============ STEP 3/4: 装弹 ============")

local function reloadUnit(unitname, wpn_dbid, number)
    local side
    for _, u in pairs(UNITS) do if u.name == unitname then side = u.side; break end end
    if not side then warn("manifest 没找到单位: " .. unitname); return false end
    local u = ScenEdit_GetUnit({ side = side, name = unitname })
    if not (u and u.guid) then warn("找不到 " .. side .. "/" .. unitname); return false end
    _errnum_ = 0
    local ok2 = pcall(ScenEdit_AddReloadsToUnit, { side = side, unitname = unitname, wpn_dbid = wpn_dbid, number = number })
    if ok2 and (_errnum_ or 0) == 0 then
        ok(string.format("+ %d x [dbid=%d] -> %s", number, wpn_dbid, unitname))
        return true
    else
        warn(string.format("装弹失败 %s", unitname))
        return false
    end
end

for _, a in ipairs(AMMO) do reloadUnit(a.unitname, a.wpn_dbid, a.number) end

print("[CMO] [INFO] ============ STEP 3 完成 ============")

-- ============================================================================
-- 第五部分: STEP 4 — 真延时打击 (原 attack.lua)
-- ============================================================================
print("")
print("[CMO] ============ STEP 4/4: 真延时打击 (TOT 事件驱动) ============")

-- 全局变量 (fireAt 沙箱需要)
_SIDE_RED             = CFG_SCENARIO.side_red
_SIDE_BLUE            = CFG_SCENARIO.side_blue
_BLUE_AUTODETECTABLE  = CFG_SCENARIO.blue_autodetectable
_CONTACT_SETTLE_DELAY = tonumber(CFG_SCENARIO.contact_settle_delay) or 15
_ALLOW_BOL_FALLBACK   = false
_CONTACT_CACHE        = {}

local function sameGuid(a, b) return a and b and tostring(a):lower() == tostring(b):lower() end

local function collectContacts(sideName)
    local out, seen = {}, {}
    local ok2, r = pcall(ScenEdit_GetContacts, { side = sideName })
    if ok2 and type(r) == "table" then
        for _, c in ipairs(r) do
            if c.guid or c.Guid then
                local key = tostring(c.guid or c.Guid)
                if not seen[key] then seen[key] = true; out[#out + 1] = c end
            end
        end
    end
    return out
end

local function findContactForTarget(tgt, tgtName)
    if not (tgt and tgt.guid) then return nil end
    local cacheKey = tostring(tgt.guid)
    if _CONTACT_CACHE[cacheKey] then return _CONTACT_CACHE[cacheKey] end
    pcall(ScenEdit_SetSideOptions, { side = _SIDE_RED, awareness = "OMNI" })
    local cs = collectContacts(_SIDE_RED)
    info(_SIDE_RED .. " contact count = " .. tostring(#cs))
    for _, c in ipairs(cs) do
        local cg = c.guid or c.Guid
        if cg and (sameGuid(c.actualunitid, tgt.guid) or sameGuid(c.actualUnitID, tgt.guid)
            or sameGuid(c.actualunitguid, tgt.guid) or sameGuid(c.actualUnitGuid, tgt.guid)
            or sameGuid(c.actual_guid, tgt.guid) or sameGuid(c.actualGuid, tgt.guid)) then
            _CONTACT_CACHE[cacheKey] = cg; return cg
        end
    end
    for _, c in ipairs(cs) do
        local cg = c.guid or c.Guid
        local nm = tostring(c.name or c.Name or c.actualunitname or "")
        if cg and tgtName and nm:find(tgtName, 1, true) then
            _CONTACT_CACHE[cacheKey] = cg; warn("按名字匹配: " .. tgtName); return cg
        end
    end
    return nil
end

-- fireAt (全局)
function fireAt(attackerName, targetName, wpnDbid, qty)
    local atk = ScenEdit_GetUnit({ side = _SIDE_RED, name = attackerName })
    local tgt = ScenEdit_GetUnit({ side = _SIDE_BLUE, name = targetName })
    if not (atk and atk.guid) then print("[CMO] [ERROR] 找不到攻击方 " .. attackerName); return false end
    if not (tgt and tgt.guid) then print("[CMO] [ERROR] 找不到目标 " .. targetName); return false end
    pcall(ScenEdit_SetUnit, { guid = tgt.guid, autodetectable = true })
    local contactGuid
    for attempt = 1, 3 do
        contactGuid = findContactForTarget(tgt, targetName)
        if contactGuid then break end
        if attempt < 3 then
            warn("Attempt " .. attempt .. "/3: 无 contact, 2s 重试...")
            local _t = ScenEdit_CurrentTime()
            while ScenEdit_CurrentTime() < _t + 2 do end
        end
    end
    if contactGuid then
        _errnum_ = 0
        ScenEdit_AttackContact(atk.guid, contactGuid, { mode = "1", weapon = wpnDbid, qty = qty })
        ok(attackerName .. " -> CONTACT 攻击 " .. targetName)
        return true
    else
        print("[CMO] [ERROR] " .. attackerName .. " 无 contact, 取消发射")
        return false
    end
end

-- TOT ticks
local function totTicks() local t = ScenEdit_CurrentTime(); return string.format("%.0f", (t + 62135596801) * 1e7) end

-- scheduleOne
local function scheduleOne(atkName, tgtName, wpn, delay, tag)
    delay = delay + _CONTACT_SETTLE_DELAY
    local evName = "Event " .. tag
    local trName = "Trig " .. tag
    local acName = "Act " .. tag
    local fireTime = totTicks()
    local script = ("fireAt(%q,%q,%d,1)\n"):format(atkName, tgtName, wpn)
    _errnum_ = 0
    pcall(ScenEdit_SetTrigger, { mode = "add", type = "Time", name = trName, Time = fireTime })
    pcall(ScenEdit_SetAction, { mode = "add", type = "LuaScript", name = acName, ScriptText = script })
    pcall(ScenEdit_SetEvent, evName, { mode = "add", IsActive = true, IsRepeatable = false })
    pcall(ScenEdit_SetEventTrigger, evName, { mode = "add", name = trName })
    pcall(ScenEdit_SetEventAction, evName, { mode = "add", name = acName })
    ok(("调度 %s -> %s | +%ds | %s"):format(atkName, tgtName, delay, tag))
    return true
end

-- 主调度
local total_sched = 0
for i, s in ipairs(STRIKE) do
    info(("STRIKE[%d] %s -> %s | qty=%d"):format(i, s.attacker, s.target, s.qty))
    for k = 1, s.qty do
        local delay = s.startDelay + (k - 1) * s.interval
        local tag = ("TOT_%d_%d_%s"):format(i, k, s.tag)
        if scheduleOne(s.attacker, s.target, s.wpn_dbid, delay, tag) then
            total_sched = total_sched + 1
        end
    end
end

ok(string.format("STRIKE 调度完成: %d 个触发器 (每枚 1 个事件)", total_sched))
print("")
print("[CMO] ============ STEP 4 完成 ============")
print("[CMO] [INFO] 必须在 CMO 中推进游戏时间才会触发 (暂停不发射)")
print(string.format("[CMO] [INFO] 最早发射: T+%ds | 最晚发射: T+%ds",
    STRIKE[1].startDelay + _CONTACT_SETTLE_DELAY,
    STRIKE[#STRIKE].startDelay + (STRIKE[#STRIKE].qty - 1) * STRIKE[#STRIKE].interval + _CONTACT_SETTLE_DELAY))

print("")
print("[CMO] ============ all_in_one.lua 全部完成 ============")
print("[CMO] [INFO] 4 阶段执行完毕:")
print("[CMO] [INFO]   - 8 单位已创建")
print("[CMO] [INFO]   - 5 单位已清弹")
print("[CMO] [INFO]   - 3 单位已装弹 (YJ-18 x8 + YJ-83 x2)")
print("[CMO] [INFO]   - 10 个真延时触发器已调度")