-- ==========================================================================
-- manifest.lua — 消耗与诱歼作战方案
--     单一数据源。所有 4 个脚本 (main/clear/reload/attack) 都 dofile 此文件
--     Generated by stage3, 2026-07-06
-- ==========================================================================

print("[CMO] [INFO] ============ manifest.lua loaded ============")

-- ==========================================================================
-- CFG_SCENARIO — 场景配置
-- ==========================================================================
CFG_SCENARIO = {
    name                 = "消耗与诱歼作战方案",
    startTime            = "2026-04-10 10:00:00",
    side_red             = "红方",
    side_blue            = "蓝方",
    red_awareness        = "OMNI",
    red_emcon            = "Radar=Active;Sonar=Active;OECM=Active",
    blue_emcon           = "Radar=Active;Sonar=Active;OECM=Active",
    blue_autodetectable  = true,
    contact_settle_delay = 15,
}

CFG_DOCTRINE_RED = {
    weapon_control_status_air        = 0,
    weapon_control_status_surface    = 0,
    weapon_control_status_subsurface = 0,
    weapon_control_status_land       = 0,
}

CFG_DOCTRINE_BLUE = {
    weapon_control_status_air        = 0,
    weapon_control_status_surface    = 2,
    weapon_control_status_subsurface = 2,
    weapon_control_status_land       = 0,
}

-- ==========================================================================
-- UNITS — 全部 8 个单位（与 main.lua 中 name= 完全一致）
-- ==========================================================================
UNITS = {}

UNITS["red_ddg_1"] = {
    side    = "红方",
    type    = "Ship",
    dbid    = 3883,
    name    = "red_ddg_1",
    lat     = "30.25",
    lon     = "124.75",
    altitude= "0",
    name_en = "Type 055 Renhai [101 Nanchang]",
}
UNITS["red_ddg_2"] = {
    side    = "红方",
    type    = "Ship",
    dbid    = 2296,
    name    = "red_ddg_2",
    lat     = "29.75",
    lon     = "125.25",
    altitude= "0",
    name_en = "Type 052D Luyang III [172 Kunming]",
}
UNITS["red_sub_1"] = {
    side    = "红方",
    type    = "Submarine",
    dbid    = 124,
    name    = "red_sub_1",
    lat     = "30.0",
    lon     = "126.0",
    altitude= "60",
    name_en = "Type 039G1 Song",
}
UNITS["red_ac_1"] = {
    side    = "红方",
    type    = "Aircraft",
    dbid    = 2853,
    name    = "red_ac_1",
    lat     = "29.0",
    lon     = "123.5",
    altitude= "7620",
    name_en = "J-16 Flying Shark [Su-30MKK Copy]",
}
UNITS["red_ew_1"] = {
    side    = "红方",
    type    = "Aircraft",
    dbid    = 343,
    name    = "red_ew_1",
    lat     = "28.5",
    lon     = "124.0",
    altitude= "9144",
    name_en = "EA-18G Growler",
}
UNITS["blue_ddg_1"] = {
    side    = "蓝方",
    type    = "Ship",
    dbid    = 112,
    name    = "blue_ddg_1",
    lat     = "28.833333333333332",
    lon     = "126.33333333333333",
    altitude= "0",
    name_en = "DDG 51 Arleigh Burke [Arleigh Burke Flight I]",
}
UNITS["blue_ddg_2"] = {
    side    = "蓝方",
    type    = "Ship",
    dbid    = 797,
    name    = "blue_ddg_2",
    lat     = "28.5",
    lon     = "126.66666666666667",
    altitude= "0",
    name_en = "DDG 51 Arleigh Burke [Arleigh Burke Flight I]",
}
UNITS["blue_aux_1"] = {
    side    = "蓝方",
    type    = "Ship",
    dbid    = 26,
    name    = "blue_aux_1",
    lat     = "28.166666666666668",
    lon     = "126.83333333333333",
    altitude= "0",
    name_en = "T-AO 187 Henry J. Kaiser [Mod Cimarron]",
}

-- ==========================================================================
-- CLEAR_LIST — 5 个红方单位
-- ==========================================================================
CLEAR_LIST = {"red_ddg_1", "red_ddg_2", "red_sub_1", "red_ac_1", "red_ew_1"}

-- ==========================================================================
-- AMMO — 装弹清单 ({{unitname, wpn_dbid, number}})
-- ==========================================================================
AMMO = {
    { unitname = "red_ddg_1", wpn_dbid = 2868, number = 4 },  -- YJ-18
    { unitname = "red_sub_1", wpn_dbid = 2868, number = 4 },  -- YJ-18
    { unitname = "red_ac_1", wpn_dbid = 541, number = 2 },  -- YJ-83
}

-- ==========================================================================
-- STRIKE — 打击清单 ({{attacker, target, wpn_dbid, qty, startDelay, interval}})
--   真延时: 每次 fireAt 调用 qty=1, scheduleOne 拆成 N 个触发器
-- ==========================================================================
STRIKE = {
    { attacker = "red_ac_1", target = "blue_ddg_1", wpn_dbid = 541, qty = 2, startDelay = 3900, interval = 60, tag = "red_ac_1_l1_4" },
    { attacker = "red_sub_1", target = "blue_ddg_1", wpn_dbid = 2868, qty = 4, startDelay = 3900, interval = 60, tag = "red_sub_1_l1_5" },
    { attacker = "red_ac_1", target = "blue_ddg_2", wpn_dbid = 541, qty = 2, startDelay = 3900, interval = 60, tag = "red_ac_1_l2_4" },
    { attacker = "red_ac_1", target = "blue_aux_1", wpn_dbid = 541, qty = 2, startDelay = 3900, interval = 60, tag = "red_ac_1_l3_4" },
}

-- ==========================================================================
-- PATROLS — 巡逻任务
-- ==========================================================================
-- (single-line version was a bug, removed)
PATROLS = {
    {
        platform      = "red_ew_1",
        type          = "SEAD",
        subtype       = "SEAD",
        zone_name     = "EW_PATROL_ZONE",
        rps           = {"RP-EW-1", "RP-EW-2", "RP-EW-3", "RP-EW-4"},
        start_time    = "2026-04-10 10:00:00",
        duration_seconds = 6300,
    }
}

-- ==========================================================================
-- WAYPOINTS — 36 个航点 (用于航线)
-- ==========================================================================
WAYPOINTS = {
    { platform = "red_ddg_1", seq = 1, lat = "30.25", lon = "124.75", altitude = "0", speed = "15" },
    { platform = "red_ddg_1", seq = 2, lat = "29.8", lon = "125.2", altitude = "0", speed = "25" },
    { platform = "red_ddg_1", seq = 3, lat = "29.4", lon = "125.7", altitude = "0", speed = "25" },
    { platform = "red_ddg_1", seq = 4, lat = "29.2", lon = "126.1", altitude = "0", speed = "20" },
    { platform = "red_ddg_1", seq = 5, lat = "29.0", lon = "126.0", altitude = "0", speed = "20" },
    { platform = "red_ddg_1", seq = 6, lat = "29.3", lon = "125.5", altitude = "0", speed = "25" },
    { platform = "red_ddg_1", seq = 7, lat = "29.7", lon = "125.0", altitude = "0", speed = "25" },
    { platform = "red_ddg_1", seq = 8, lat = "30.1", lon = "124.6", altitude = "0", speed = "15" },
    { platform = "red_ddg_2", seq = 1, lat = "29.75", lon = "125.25", altitude = "0", speed = "20" },
    { platform = "red_ddg_2", seq = 2, lat = "29.5", lon = "125.5", altitude = "0", speed = "25" },
    { platform = "red_ddg_2", seq = 3, lat = "29.25", lon = "125.75", altitude = "0", speed = "25" },
    { platform = "red_ddg_2", seq = 4, lat = "29.0", lon = "126.0", altitude = "0", speed = "20" },
    { platform = "red_ddg_2", seq = 5, lat = "28.75", lon = "126.25", altitude = "0", speed = "15" },
    { platform = "red_ddg_2", seq = 6, lat = "28.5", lon = "126.5", altitude = "0", speed = "10" },
    { platform = "red_sub_1", seq = 1, lat = "30.0", lon = "126.0", altitude = "60", speed = "5" },
    { platform = "red_sub_1", seq = 2, lat = "29.8", lon = "126.1", altitude = "60", speed = "5" },
    { platform = "red_sub_1", seq = 3, lat = "29.6", lon = "126.2", altitude = "60", speed = "5" },
    { platform = "red_sub_1", seq = 4, lat = "29.4", lon = "126.3", altitude = "60", speed = "5" },
    { platform = "red_sub_1", seq = 5, lat = "29.2", lon = "126.4", altitude = "60", speed = "0" },
    { platform = "red_sub_1", seq = 6, lat = "29.0", lon = "126.5", altitude = "60", speed = "8" },
    { platform = "red_sub_1", seq = 7, lat = "29.2", lon = "126.6", altitude = "60", speed = "8" },
    { platform = "red_sub_1", seq = 8, lat = "29.5", lon = "126.5", altitude = "60", speed = "5" },
    { platform = "red_ac_1", seq = 1, lat = "29.0", lon = "123.5", altitude = "7620", speed = "200" },
    { platform = "red_ac_1", seq = 2, lat = "29.1", lon = "123.6", altitude = "5000", speed = "250" },
    { platform = "red_ac_1", seq = 3, lat = "28.8", lon = "125.0", altitude = "100", speed = "300" },
    { platform = "red_ac_1", seq = 4, lat = "28.833333333333332", lon = "126.33333333333333", altitude = "100", speed = "300" },
    { platform = "red_ac_1", seq = 5, lat = "28.5", lon = "126.66666666666667", altitude = "100", speed = "300" },
    { platform = "red_ac_1", seq = 6, lat = "28.166666666666668", lon = "126.83333333333333", altitude = "100", speed = "300" },
    { platform = "red_ac_1", seq = 7, lat = "28.0", lon = "127.0", altitude = "5000", speed = "400" },
    { platform = "red_ac_1", seq = 8, lat = "29.0", lon = "124.0", altitude = "5000", speed = "350" },
    { platform = "red_ew_1", seq = 1, lat = "28.5", lon = "124.0", altitude = "9144", speed = "250" },
    { platform = "red_ew_1", seq = 2, lat = "28.8", lon = "125.5", altitude = "9144", speed = "250" },
    { platform = "red_ew_1", seq = 3, lat = "29.1", lon = "126.3", altitude = "8000", speed = "220" },
    { platform = "red_ew_1", seq = 4, lat = "29.3", lon = "126.6", altitude = "8000", speed = "220" },
    { platform = "red_ew_1", seq = 5, lat = "29.0", lon = "126.9", altitude = "8000", speed = "220" },
    { platform = "red_ew_1", seq = 6, lat = "28.2", lon = "125.0", altitude = "9144", speed = "250" },
}

-- ==========================================================================
-- REFERENCE_POINTS — SEAD 巡逻区 4 个
-- ==========================================================================
REFERENCE_POINTS = {
    { side = "红方", name = "RP-EW-1", lat = "27.0", lon = "123.0" },
    { side = "红方", name = "RP-EW-2", lat = "27.0", lon = "125.0" },
    { side = "红方", name = "RP-EW-3", lat = "30.0", lon = "125.0" },
    { side = "红方", name = "RP-EW-4", lat = "30.0", lon = "123.0" },
}

-- ==========================================================================
-- TIMINGS — 17 个时间触发器
-- ==========================================================================
TIMINGS = {
    { kind = "combatPhase", tag = "phase_1", phase_name = "水面编队前出诱敌", relative_start = 0, absolute_start = "2026-04-10 10:00:00", absolute_end = "2026-04-10 10:30:00" },
    { kind = "combatPhase", tag = "phase_2", phase_name = "电磁佯动与防空消耗", relative_start = 1800, absolute_start = "2026-04-10 10:30:00", absolute_end = "2026-04-10 11:00:00" },
    { kind = "combatPhase", tag = "phase_3", phase_name = "空中力量决定性突击", relative_start = 3600, absolute_start = "2026-04-10 11:00:00", absolute_end = "2026-04-10 11:15:00" },
    { kind = "combatPhase", tag = "phase_4", phase_name = "水面编队撤离与评估", relative_start = 4500, absolute_start = "2026-04-10 11:15:00", absolute_end = "2026-04-10 11:45:00" },
    { kind = "killChainLinkStart", tag = "kc1_l1_1", kill_chain = "kc1", link_id = "l1_1", link_name = "诱敌巡航", relative_seconds = 0 },
    { kind = "killChainLinkStart", tag = "kc1_l1_2", kill_chain = "kc1", link_id = "l1_2", link_name = "电磁干扰", relative_seconds = 1800 },
    { kind = "killChainLinkStart", tag = "kc1_l1_3", kill_chain = "kc1", link_id = "l1_3", link_name = "空中瞄准", relative_seconds = 3600 },
    { kind = "killChainLinkStart", tag = "kc1_l1_4", kill_chain = "kc1", link_id = "l1_4", link_name = "空中交战", relative_seconds = 3900 },
    { kind = "killChainLinkStart", tag = "kc1_l1_5", kill_chain = "kc1", link_id = "l1_5", link_name = "潜艇交战", relative_seconds = 3900 },
    { kind = "killChainLinkStart", tag = "kc2_l2_1", kill_chain = "kc2", link_id = "l2_1", link_name = "诱敌巡航", relative_seconds = 0 },
    { kind = "killChainLinkStart", tag = "kc2_l2_2", kill_chain = "kc2", link_id = "l2_2", link_name = "电磁干扰", relative_seconds = 1800 },
    { kind = "killChainLinkStart", tag = "kc2_l2_3", kill_chain = "kc2", link_id = "l2_3", link_name = "空中瞄准", relative_seconds = 3600 },
    { kind = "killChainLinkStart", tag = "kc2_l2_4", kill_chain = "kc2", link_id = "l2_4", link_name = "空中交战", relative_seconds = 3900 },
    { kind = "killChainLinkStart", tag = "kc3_l3_1", kill_chain = "kc3", link_id = "l3_1", link_name = "诱敌巡航", relative_seconds = 0 },
    { kind = "killChainLinkStart", tag = "kc3_l3_2", kill_chain = "kc3", link_id = "l3_2", link_name = "电磁干扰", relative_seconds = 1800 },
    { kind = "killChainLinkStart", tag = "kc3_l3_3", kill_chain = "kc3", link_id = "l3_3", link_name = "空中瞄准", relative_seconds = 3600 },
    { kind = "killChainLinkStart", tag = "kc3_l3_4", kill_chain = "kc3", link_id = "l3_4", link_name = "空中交战", relative_seconds = 3900 },
}

-- ==========================================================================
-- VICTORY — 胜利条件
-- ==========================================================================
VICTORY = { red_winning_threshold = 70, description = "蓝方护航编队被毁伤 ≥ 70% = 红方胜" }

-- helper (必须在 print 之前定义)
function table_count_keys(t)
    local n = 0
    for _ in pairs(t) do n = n + 1 end
    return n
end

print("[CMO] [INFO] manifest.lua loaded: " ..
    "UNITS=" .. tostring(table_count_keys(UNITS)) .. ", "
    .. "CLEAR_LIST=" .. tostring(#CLEAR_LIST) .. ", "
    .. "AMMO=" .. tostring(#AMMO) .. ", "
    .. "STRIKE=" .. tostring(#STRIKE) .. ", "
    .. "PATROLS=" .. tostring(#PATROLS) .. ", "
    .. "WAYPOINTS=" .. tostring(#WAYPOINTS) .. ", "
    .. "REFERENCE_POINTS=" .. tostring(#REFERENCE_POINTS) .. ", "
    .. "TIMINGS=" .. tostring(#TIMINGS))
