-- ============================================================
-- 联合反击作战方案 (Joint Counter-Attack Plan)
-- Plan: plan_a1_001_legacy
-- Side: Red (红方) vs Blue (蓝方)
-- Generated by CMO Lua SKILL
-- ============================================================
Tool_EmulateNoConsole(true)

-- ============================================================
-- SECTION 1: MCP-Verified DBID Constants
-- ============================================================

-- == RED SIDE (China, OperatorCountry=2018) ==
-- Aircraft DBIDs (MCP: SQL DataAircraft)
local DBID_J16D_ROARINGWOLF = 4632   -- J-16D Roaring Wolf [PLAAF EW]
local DBID_H6K_BADGER        = 1731   -- H-6K Badger [PLAAF bomber]
local DBID_KJ500_CUB         = 3683   -- KJ-500 Cub [GX9 AWACS]
local DBID_J20A_FAGIN        = 5012   -- J-20A Fagin [PLAAF stealth fighter]
local DBID_J20B_FAGIN        = 2463   -- J-20B Fagin [PLAAF stealth fighter]

-- LoadoutIDs (MCP: DataAircraftLoadouts WHERE ComponentID=...)
local LOADOUT_J16D  = 753    -- ComponentID 4632
local LOADOUT_H6K   = 863    -- ComponentID 1731 (KD-20/CJ-10A ALCM)
local LOADOUT_KJ500 = 494    -- ComponentID 3683
local LOADOUT_J20A  = 1191   -- ComponentID 5012
local LOADOUT_J20B  = 198    -- ComponentID 2463

-- DF-26 SSM Facility (MCP: SQL DataFacility DF-26)
local DBID_DF26_FACILITY = 89      -- SSM Bn (DF-21C [CSS-5 Mod-4]) Conventional
-- Note: GND_DF26B_LAUNCHER / GND_DF26D_LAUNCHER modeled as SSM Bn DF-21C
-- This is the closest CMO equivalent for ground-based DF-26 ballistic missiles

-- == BLUE SIDE (US, OperatorCountry=2101) ==
-- Ship DBIDs (MCP: SQL DataShip WHERE OperatorCountry=2101)
local DBID_TICONDEROGA    = 40     -- CG 56 San Jacinto [Ticonderoga Baseline 3]
local DBID_BURKE_FLIGHT2  = 111    -- DDG 72 Mahan [Arleigh Burke Flight II]
local DBID_LHA_AMERICA    = 170    -- LHD 1 Wasp [Amphibious Assault]
local DBID_AUX_SUPPLY     = 753    -- T-AKE 1 Lewis and Clark [Combat Logistics Force]
-- Note: supply_kz targets T-AKE Lewis and Clark class; no precise fit, using DBID 753

-- Aircraft DBIDs (Blue side - for reference only, not spawned in this plan)
local DBID_F18E = 342    -- F/A-18E Super Hornet

-- ============================================================
-- SECTION 2: Scenario Setup
-- ============================================================

local function addSideIfNeeded(sideName, color)
    local ok, side = pcall(VP_GetSide, {Side = sideName})
    if not (ok and side) then
        local _, err = pcall(ScenEdit_AddSide, {name = sideName, color = color})
        if not _ then
            print("Warning: Could not create side " .. sideName .. ": " .. tostring(err))
        end
    end
end

addSideIfNeeded('Red', '255,0,0')
addSideIfNeeded('Blue', '0,0,255')

-- Set postures
ScenEdit_SetSidePosture('Red', 'Blue', 'H')
ScenEdit_SetSidePosture('Blue', 'Red', 'H')

-- Red doctrine
ScenEdit_SetDoctrine({side = 'Red'}, {
    weapon_control_status_air        = 0,
    weapon_control_status_surface    = 0,
    weapon_control_status_subsurface = 0,
    use_nuclear_weapons             = 'no',
})

-- Blue doctrine
ScenEdit_SetDoctrine({side = 'Blue'}, {
    weapon_control_status_air        = 0,
    weapon_control_status_surface    = 0,
    weapon_control_status_subsurface = 0,
    use_nuclear_weapons             = 'no',
})

-- ============================================================
-- SECTION 3: RED Side Units
-- ============================================================

-- === RED: DF-26B SSM Battalion (12 launchers) ===
-- GND_DF26B_LAUNCHER -> DBID 89 (SSM Bn DF-21C CSS-5)
-- Plan: 打击lha_meiguo (ST-01-001 engage: D001, D002, D003, D005, D011, D012)
local DF26B_LOCATIONS = {
    {lat = 18.54, lon = 110.00, name = 'RED-DF26B-01', pid = 'D001'},
    {lat = 18.54, lon = 110.01, name = 'RED-DF26B-02', pid = 'D002'},
    {lat = 18.55, lon = 110.00, name = 'RED-DF26B-03', pid = 'D003'},
    {lat = 18.55, lon = 110.01, name = 'RED-DF26B-04', pid = 'D004'},  -- chafei
    {lat = 18.55, lon = 110.01, name = 'RED-DF26B-05', pid = 'D005'},
    {lat = 18.54, lon = 110.01, name = 'RED-DF26B-06', pid = 'D006'},  -- chafei
    {lat = 18.55, lon = 110.01, name = 'RED-DF26B-07', pid = 'D007'},  -- simoer
    {lat = 18.54, lon = 110.02, name = 'RED-DF26B-08', pid = 'D008'},  -- simoer
    {lat = 18.54, lon = 110.03, name = 'RED-DF26B-09', pid = 'D009'},  -- momuseng
    {lat = 18.54, lon = 110.03, name = 'RED-DF26B-10', pid = 'D010'},  -- momuseng
    {lat = 18.54, lon = 110.03, name = 'RED-DF26B-11', pid = 'D011'},
    {lat = 18.53, lon = 110.03, name = 'RED-DF26B-12', pid = 'D012'},
}
for i, loc in ipairs(DF26B_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Facility', name = loc.name,
        dbid = DBID_DF26_FACILITY,
        latitude = loc.lat, longitude = loc.lon,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('DF26B_' .. loc.pid .. '_GUID', u.guid)
    end
end

-- === RED: DF-26D SSM Battalion (12 launchers) ===
-- GND_DF26D_LAUNCHER -> DBID 89 (SSM Bn DF-21C CSS-5, same proxy as DF-26B)
-- Plan: 打击lha_meiguo (D3001, D3002, D3003, D3005, D3011, D3012)
--       打击simoer (D3004, D3006)
--       打击chafei (D3007, D3008)
--       打击ddg_momuseng (D3009, D3010)
--       打击supply_kz (D3009, D3010)
local DF26D_LOCATIONS = {
    {lat = 23.67, lon = 113.00, name = 'RED-DF26D-01', pid = 'D3001'},
    {lat = 23.67, lon = 112.99, name = 'RED-DF26D-02', pid = 'D3002'},
    {lat = 23.65, lon = 112.99, name = 'RED-DF26D-03', pid = 'D3003'},
    {lat = 23.66, lon = 112.98, name = 'RED-DF26D-04', pid = 'D3004'},  -- simoer
    {lat = 23.65, lon = 112.97, name = 'RED-DF26D-05', pid = 'D3005'},
    {lat = 23.65, lon = 112.99, name = 'RED-DF26D-06', pid = 'D3006'},  -- simoer
    {lat = 23.64, lon = 112.97, name = 'RED-DF26D-07', pid = 'D3007'},  -- chafei
    {lat = 23.64, lon = 112.99, name = 'RED-DF26D-08', pid = 'D3008'},  -- chafei
    {lat = 23.65, lon = 112.99, name = 'RED-DF26D-09', pid = 'D3009'},  -- momuseng/supply
    {lat = 23.65, lon = 113.00, name = 'RED-DF26D-10', pid = 'D3010'},  -- momuseng/supply
    {lat = 23.65, lon = 113.00, name = 'RED-DF26D-11', pid = 'D3011'},
    {lat = 23.64, lon = 112.99, name = 'RED-DF26D-12', pid = 'D3012'},
}
for i, loc in ipairs(DF26D_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Facility', name = loc.name,
        dbid = DBID_DF26_FACILITY,
        latitude = loc.lat, longitude = loc.lon,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('DF26D_' .. loc.pid .. '_GUID', u.guid)
    end
end

-- === RED: J-16D EW Aircraft (4 units) ===
-- AC_J16D -> DBID 4632 (J-16D Roaring Wolf, PLAAF EW Variant)
-- LoadoutID: 753 (ComponentID 4632)
-- Engaged in: simoer strike (JD003, JD004) and chafei strike (JD002, JD007)
local J16D_LOCATIONS = {
    {lat = 9.91, lon = 115.53, name = 'RED-J16D-01', pid = 'JD002', alt = 1500},
    {lat = 9.91, lon = 115.50, name = 'RED-J16D-02', pid = 'JD003', alt = 1500},
    {lat = 9.90, lon = 115.49, name = 'RED-J16D-03', pid = 'JD004', alt = 1500},
    {lat = 9.94, lon = 115.52, name = 'RED-J16D-04', pid = 'JD007', alt = 1500},
}
for i, loc in ipairs(J16D_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Aircraft', name = loc.name,
        dbid = DBID_J16D_ROARINGWOLF, LoadoutID = LOADOUT_J16D,
        latitude = loc.lat, longitude = loc.lon,
        altitude = loc.alt, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('J16D_' .. loc.pid .. '_GUID', u.guid)
    end
end

-- === RED: H-6K Bombers (6 units) ===
-- BOMBER_H6K -> DBID 1731 (H-6K Badger, 6x KD-20/CJ-10A)
-- LoadoutID: 863 (ComponentID 1731)
-- HK003-HK004: 打击ddg_momuseng (Tomahawk)
-- HK005-HK006: 打击tico_simoer (Tomahawk)
-- HK007-HK008: 打击ddg_chafei (Tomahawk)
local H6K_LOCATIONS = {
    {lat = 26.32, lon = 112.79, name = 'RED-H6K-01', pid = 'HK003'},
    {lat = 26.30, lon = 112.91, name = 'RED-H6K-02', pid = 'HK004'},
    {lat = 26.45, lon = 112.90, name = 'RED-H6K-03', pid = 'HK005'},
    {lat = 26.22, lon = 112.68, name = 'RED-H6K-04', pid = 'HK006'},
    {lat = 26.20, lon = 112.91, name = 'RED-H6K-05', pid = 'HK007'},
    {lat = 26.39, lon = 112.98, name = 'RED-H6K-06', pid = 'HK008'},
}
for i, loc in ipairs(H6K_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Aircraft', name = loc.name,
        dbid = DBID_H6K_BADGER, LoadoutID = LOADOUT_H6K,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('H6K_' .. loc.pid .. '_GUID', u.guid)
    end
end

-- === RED: KJ-500 AWACS (1 unit) ===
-- AWACS_KJ500 -> DBID 3683 (KJ-500 Cub [GX9])
-- LoadoutID: 494 (ComponentID 3683)
-- KJ002: 打击lha_meiguo (reconnaissance role)
local okKJ, uKJ = pcall(ScenEdit_AddUnit, {
    side = 'Red', type = 'Aircraft', name = 'RED-KJ500-01',
    dbid = DBID_KJ500_CUB, LoadoutID = LOADOUT_KJ500,
    latitude = 26.32, longitude = 112.63,
    altitude = 1000, heading = 0, speed = 0,
    proficiency = 'Veteran',
})
if okKJ then
    ScenEdit_SetKeyValue('KJ500_KJ002_GUID', uKJ.guid)
end

-- === RED: J-20A Fighters (4 units) ===
-- AC_J20 -> DBID 5012 (J-20A Fagin)
-- LoadoutID: 1191 (ComponentID 5012)
-- ZD001-ZD004: 打击lha_meiguo
local J20_LOCATIONS = {
    {lat = 18.50, lon = 109.97, name = 'RED-J20A-01', pid = 'ZD001'},
    {lat = 18.50, lon = 109.98, name = 'RED-J20A-02', pid = 'ZD002'},
    {lat = 18.49, lon = 109.98, name = 'RED-J20A-03', pid = 'ZD003'},
    {lat = 18.49, lon = 109.99, name = 'RED-J20A-04', pid = 'ZD004'},
}
for i, loc in ipairs(J20_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Aircraft', name = loc.name,
        dbid = DBID_J20A_FAGIN, LoadoutID = LOADOUT_J20A,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('J20A_' .. loc.pid .. '_GUID', u.guid)
    end
end

-- ============================================================
-- SECTION 4: BLUE Side Units (Strike Targets)
-- ============================================================

-- === BLUE: Ticonderoga Cruiser (tico_simoer) ===
-- Target: tico_simoer, lat=7.970356, lon=119.503844
local okTICO, uTICO = pcall(ScenEdit_AddUnit, {
    side = 'Blue', type = 'Ship', name = 'BLUE-TICO-Simoer',
    dbid = DBID_TICONDEROGA,
    latitude = 7.970356, longitude = 119.503844,
    heading = 90, speed = 10,
    proficiency = 'Veteran',
})
if okTICO then
    ScenEdit_SetKeyValue('BLUE_TICO_SIMOER_GUID', uTICO.guid)
end

-- === BLUE: Arleigh Burke Destroyer (ddg_chafei) ===
-- Target: ddg_chafei, lat=8.284662, lon=119.783273
local okCHAF, uCHAF = pcall(ScenEdit_AddUnit, {
    side = 'Blue', type = 'Ship', name = 'BLUE-DDG-Chafei',
    dbid = DBID_BURKE_FLIGHT2,
    latitude = 8.284662, longitude = 119.783273,
    heading = 90, speed = 10,
    proficiency = 'Veteran',
})
if okCHAF then
    ScenEdit_SetKeyValue('BLUE_DDG_CHAFEI_GUID', uCHAF.guid)
end

-- === BLUE: LHA Amphibious Assault (lha_meiguo) ===
-- Target: lha_meiguo, lat=7.922858, lon=120.093579
local okLHA, uLHA = pcall(ScenEdit_AddUnit, {
    side = 'Blue', type = 'Ship', name = 'BLUE-LHA-America',
    dbid = DBID_LHA_AMERICA,
    latitude = 7.922858, longitude = 120.093579,
    heading = 90, speed = 8,
    proficiency = 'Veteran',
})
if okLHA then
    ScenEdit_SetKeyValue('BLUE_LHA_MEIGUO_GUID', uLHA.guid)
end

-- === BLUE: Auxiliary Supply Ship (supply_kz) ===
-- Target: supply_kz, lat=-0.101186, lon=106.164261
local okSUP, uSUP = pcall(ScenEdit_AddUnit, {
    side = 'Blue', type = 'Ship', name = 'BLUE-AUX-Supply',
    dbid = DBID_AUX_SUPPLY,
    latitude = -0.101186, longitude = 106.164261,
    heading = 0, speed = 5,
    proficiency = 'Veteran',
})
if okSUP then
    ScenEdit_SetKeyValue('BLUE_SUPPLY_KZ_GUID', uSUP.guid)
end

-- === BLUE: Arleigh Burke Destroyer (ddg_momuseng) ===
-- Target: ddg_momuseng, lat=7.104, lon=116.28
local okMOMU, uMOMU = pcall(ScenEdit_AddUnit, {
    side = 'Blue', type = 'Ship', name = 'BLUE-DDG-Momuseng',
    dbid = DBID_BURKE_FLIGHT2,
    latitude = 7.104, longitude = 116.28,
    heading = 90, speed = 10,
    proficiency = 'Veteran',
})
if okMOMU then
    ScenEdit_SetKeyValue('BLUE_DDG_MOMUSENG_GUID', uMOMU.guid)
end

-- ============================================================
-- SECTION 5: Skipped Units Summary (MCP not found)
-- ============================================================
-- The following units could not be resolved via MCP and are skipped:
--
-- RED SIDE (SKIP):
--   - SAT_JIANBING23: DBID not found in DataAircraft / DataFacility / DataSatellite
--     (Satellite reconnaissance platform; CMO does not model space-based satellites)
--   - UUV_RED (5x): DBID not found in DataSubmarine
--     (Chinese UUV platforms not available in current CMO DB)
--
-- BLUE SIDE (SKIP):
--   - Additional blue units (F-35, F/A-18, etc.) are not part of this strike plan
--
-- NOTE: GND_DF26B_LAUNCHER and GND_DF26D_LAUNCHER are modeled as:
--   DBID 89 (SSM Bn DF-21C [CSS-5 Mod-4]) Conventional
--   This is the closest CMO equivalent for DF-26 ballistic missile battalion.
-- ============================================================

-- ============================================================
-- SECTION 6: Reference Points (Strike Target Locations)
-- ============================================================

-- ST-01-002: 打击tico_simoer (Ticonderoga at 7.970356, 119.503844)
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-TICO-SIMOER', latitude = 7.970356, longitude = 119.503844, highlighted = false})

-- ST-01-003: 打击ddg_chafei (Burke at 8.284662, 119.783273)
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-DDG-CHAFEI', latitude = 8.284662, longitude = 119.783273, highlighted = false})

-- ST-01-001: 打击lha_meiguo (LHA at 7.922858, 120.093579)
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-LHA-MEIGUO', latitude = 7.922858, longitude = 120.093579, highlighted = false})

-- ST-01-004: 打击supply_kz (Supply at -0.101186, 106.164261)
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-SUPPLY-KZ', latitude = -0.101186, longitude = 106.164261, highlighted = false})

-- ST-01-005: 打击ddg_momuseng (Burke at 7.104, 116.28)
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-DDG-MOMUSENG', latitude = 7.104, longitude = 116.28, highlighted = false})

-- Patrol/reference zones for Red platforms
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-EW-Station', latitude = 9.91, longitude = 115.51, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Bomber-Patrol', latitude = 26.32, longitude = 112.80, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Fighter-AA', latitude = 18.50, longitude = 109.98, highlighted = false})

-- ============================================================
-- SECTION 7: Missions
-- ============================================================
local T0 = ScenEdit_CurrentTime()

-- === ST-01-002: 打击tico_simoer (Ticonderoga) ===
local mSimoer = ScenEdit_AddMission('Red', 'Red-Strike-TICO', 'strike', {subtype = 'naval'})
ScenEdit_SetMission('Red', 'Red-Strike-TICO', {
    targetlist = {'RP-TICO-SIMOER'},
    isactive = false,
})

-- === ST-01-003: 打击ddg_chafei (Burke) ===
local mChafei = ScenEdit_AddMission('Red', 'Red-Strike-CHAFEI', 'strike', {subtype = 'naval'})
ScenEdit_SetMission('Red', 'Red-Strike-CHAFEI', {
    targetlist = {'RP-DDG-CHAFEI'},
    isactive = false,
})

-- === ST-01-001: 打击lha_meiguo (LHA) ===
local mLHA = ScenEdit_AddMission('Red', 'Red-Strike-LHA', 'strike', {subtype = 'naval'})
ScenEdit_SetMission('Red', 'Red-Strike-LHA', {
    targetlist = {'RP-LHA-MEIGUO'},
    isactive = false,
})

-- === ST-01-004: 打击supply_kz (Supply) ===
local mSupply = ScenEdit_AddMission('Red', 'Red-Strike-SUPPLY', 'strike', {subtype = 'naval'})
ScenEdit_SetMission('Red', 'Red-Strike-SUPPLY', {
    targetlist = {'RP-SUPPLY-KZ'},
    isactive = false,
})

-- === ST-01-005: 打击ddg_momuseng (Burke) ===
local mMomuseng = ScenEdit_AddMission('Red', 'Red-Strike-MOMUSENG', 'strike', {subtype = 'naval'})
ScenEdit_SetMission('Red', 'Red-Strike-MOMUSENG', {
    targetlist = {'RP-DDG-MOMUSENG'},
    isactive = false,
})

-- === EW Jamming Mission ===
local mEW = ScenEdit_AddMission('Red', 'Red-EW-Jamming', 'patrol', {type = 'air'})
ScenEdit_SetMission('Red', 'Red-EW-Jamming', {
    patrolzone = {'RP-EW-Station'},
    flightsize = 3,
    minaircraftreq = 2,
    isactive = false,
})

-- === CAP / Area Defense ===
local mCAP = ScenEdit_AddMission('Red', 'Red-CAP', 'patrol', {type = 'air'})
ScenEdit_SetMission('Red', 'Red-CAP', {
    patrolzone = {'RP-Fighter-AA'},
    flightsize = 2,
    minaircraftreq = 2,
    isactive = false,
})

-- ============================================================
-- SECTION 8: Events (Kill Chain Timelines)
-- Combat phases: T0 = scenario start
-- T0+1H47M = satellite find (lha), T0+1H46M = satellite find (chafei), T0+1H52M = satellite find (simoer)
-- T0+1H55M+ = satellite track/aim
-- T0+2H10M = damage assessment (all targets)
-- ============================================================

-- === EVENT 0: Scenario Load ===
local evLoad = ScenEdit_SetEvent('Init_PlanLoaded', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'ScenLoaded', name = 'OnLoad'})
ScenEdit_SetEventTrigger(evLoad.guid, {mode = 'add', name = 'OnLoad'})

local initScript = [[
ScenEdit_SpecialMessage('Red', 'plan_a1_001_legacy 联合反击作战方案已加载')
ScenEdit_SpecialMessage('Red', '5个打击目标已标定: TICO(simoer)/DDG(chafei)/LHA(lha_meiguo)/SUPPLY(supply_kz)/DDG(momuseng)')
ScenEdit_SpecialMessage('Blue', 'Joint Counter-Attack Plan loaded - 5 strike targets activated')
ScenEdit_SetKeyValue('plan_phase', '0')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Init_Script', ScriptText = initScript})
ScenEdit_SetEventAction(evLoad.guid, {mode = 'add', name = 'Init_Script'})

-- === ST-01-002: 打击tico_simoer Timeline ===

-- T0+1H52M: Satellite W003 finds tico_simoer (link 10001)
local T1H52M = T0 + (1 * 3600 + 52 * 60)
local evFindSimoer = ScenEdit_SetEvent('ST01_ST02_Find_Simoer', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H52M', time = T1H52M})
ScenEdit_SetEventTrigger(evFindSimoer.guid, {mode = 'add', name = 'T0+1H52M'})
local findSimoerScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H52M] 天基侦察卫星发现蓝方提康德罗加巡洋舰(tico_simoer)')
ScenEdit_SpecialMessage('Red', '目标坐标: lat=7.970356, lon=119.503844')
ScenEdit_SetKeyValue('simoer_found', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'FindSimoer_Script', ScriptText = findSimoerScript})
ScenEdit_SetEventAction(evFindSimoer.guid, {mode = 'add', name = 'FindSimoer_Script'})

-- T0+1H53M: Satellite W003 tracks tico_simoer (link 10002)
local T1H53M = T0 + (1 * 3600 + 53 * 60)
local evTrackSimoer = ScenEdit_SetEvent('ST01_ST02_Track_Simoer', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H53M', time = T1H53M})
ScenEdit_SetEventTrigger(evTrackSimoer.guid, {mode = 'add', name = 'T0+1H53M'})
local trackSimoerScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H53M] 卫星持续跟踪tico_simoer，定位精确')
ScenEdit_SetKeyValue('simoer_tracked', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'TrackSimoer_Script', ScriptText = trackSimoerScript})
ScenEdit_SetEventAction(evTrackSimoer.guid, {mode = 'add', name = 'TrackSimoer_Script'})

-- T0+1H54M: Satellite W003 tracks tico_simoer (link 10003)
local T1H54M = T0 + (1 * 3600 + 54 * 60)
local evTrack2Simoer = ScenEdit_SetEvent('ST01_ST02_Track2_Simoer', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H54M', time = T1H54M})
ScenEdit_SetEventTrigger(evTrack2Simoer.guid, {mode = 'add', name = 'T0+1H54M'})
local track2SimoerScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H54M] 持续跟踪tico_simoer，目标航向航速已确定')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Track2Simoer_Script', ScriptText = track2SimoerScript})
ScenEdit_SetEventAction(evTrack2Simoer.guid, {mode = 'add', name = 'Track2Simoer_Script'})

-- T0+1H55M: Satellite W003 aims tico_simoer (link 10004)
local T1H55M = T0 + (1 * 3600 + 55 * 60)
local evAimSimoer = ScenEdit_SetEvent('ST01_ST02_Aim_Simoer', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H55M', time = T1H55M})
ScenEdit_SetEventTrigger(evAimSimoer.guid, {mode = 'add', name = 'T0+1H55M'})
local aimSimoerScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H55M] 目标瞄准完成，DF-26弹道导弹打击阵位待命')
ScenEdit_SpecialMessage('Red', 'J-16D电子战飞机起飞，建立电磁压制阵位')
ScenEdit_SetMission('Red', 'Red-EW-Jamming', {isactive = true})
ScenEdit_SetKeyValue('simoer_aimed', '1')
ScenEdit_SetKeyValue('plan_phase', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AimSimoer_Script', ScriptText = aimSimoerScript})
ScenEdit_SetEventAction(evAimSimoer.guid, {mode = 'add', name = 'AimSimoer_Script'})

-- T0+0S: Engage tico_simoer (DF-26B D007, D008 + DF-26D D3004, D3006 + J-16D JD003, JD004 + H-6K HK005, HK006)
local evEngageSimoer = ScenEdit_SetEvent('ST01_ST02_Engage_Simoer', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+0S', time = T0})
ScenEdit_SetEventTrigger(evEngageSimoer.guid, {mode = 'add', name = 'T0+0S'})
local engageSimoerScript = [[
ScenEdit_SetMission('Red', 'Red-Strike-TICO', {isactive = true})
ScenEdit_SpecialMessage('Red', '[T+0S] 反舰打击开始 - TICO(simoer)进入DF-26射程')
ScenEdit_SpecialMessage('Blue', '[ALERT] TICO Simoer under missile attack!')
ScenEdit_SetKeyValue('plan_phase', '2')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'EngageSimoer_Script', ScriptText = engageSimoerScript})
ScenEdit_SetEventAction(evEngageSimoer.guid, {mode = 'add', name = 'EngageSimoer_Script'})

-- T0+2H10M: Assessment tico_simoer (link 10006)
local T2H10M = T0 + (2 * 3600 + 10 * 60)
local evAssessSimoer = ScenEdit_SetEvent('ST01_ST02_Assess_Simoer', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H10M', time = T2H10M})
ScenEdit_SetEventTrigger(evAssessSimoer.guid, {mode = 'add', name = 'T0+2H10M'})
local assessSimoerScript = [[
ScenEdit_SpecialMessage('Red', '[T+2H10M] 天基侦察评估tico_simoer毁伤效果')
ScenEdit_SpecialMessage('Red', '毁评进行中，等待打击结果确认...')
ScenEdit_SetKeyValue('simoer_assessed', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessSimoer_Script', ScriptText = assessSimoerScript})
ScenEdit_SetEventAction(evAssessSimoer.guid, {mode = 'add', name = 'AssessSimoer_Script'})

-- T0+2H24M: Assessment complete tico_simoer
local T2H24M = T0 + (2 * 3600 + 24 * 60)
local evAssessDoneSimoer = ScenEdit_SetEvent('ST01_ST02_AssessDone_Simoer', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H24M', time = T2H24M})
ScenEdit_SetEventTrigger(evAssessDoneSimoer.guid, {mode = 'add', name = 'T0+2H24M'})
local assessDoneSimoerScript = [[
local simoer_guid = ScenEdit_GetKeyValue('BLUE_TICO_SIMOER_GUID')
if simoer_guid and simoer_guid ~= '' then
    local ok, u = pcall(ScenEdit_GetUnit, {guid = simoer_guid})
    if ok and u then
        if u.damage and u.damage > 0.5 then
            ScenEdit_SpecialMessage('Red', '[T+2H24M] 毁评结果: tico_simoer毁伤率>50%，任务完成')
            ScenEdit_SetScore('Red', 100, 'tico_simoer destroyed')
        else
            ScenEdit_SpecialMessage('Red', '[T+2H24M] 毁评结果: tico_simoer需要补充打击')
        end
    end
end
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessDoneSimoer_Script', ScriptText = assessDoneSimoerScript})
ScenEdit_SetEventAction(evAssessDoneSimoer.guid, {mode = 'add', name = 'AssessDoneSimoer_Script'})

-- === ST-01-003: 打击ddg_chafei Timeline ===

-- T0+1H46M: Satellite W051 finds ddg_chafei (link 20001)
local T1H46M = T0 + (1 * 3600 + 46 * 60)
local evFindChafei = ScenEdit_SetEvent('ST01_ST03_Find_Chafei', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H46M', time = T1H46M})
ScenEdit_SetEventTrigger(evFindChafei.guid, {mode = 'add', name = 'T0+1H46M'})
local findChafeiScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H46M] 天基侦察卫星发现蓝方伯克级驱逐舰(ddg_chafei)')
ScenEdit_SpecialMessage('Red', '目标坐标: lat=8.284662, lon=119.783273')
ScenEdit_SetKeyValue('chafei_found', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'FindChafei_Script', ScriptText = findChafeiScript})
ScenEdit_SetEventAction(evFindChafei.guid, {mode = 'add', name = 'FindChafei_Script'})

-- T0+1H47M: Satellite W051 tracks ddg_chafei (link 20002)
local T1H47M_Chafei = T0 + (1 * 3600 + 47 * 60)
local evTrackChafei = ScenEdit_SetEvent('ST01_ST03_Track_Chafei', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H47M_Chafei', time = T1H47M_Chafei})
ScenEdit_SetEventTrigger(evTrackChafei.guid, {mode = 'add', name = 'T0+1H47M_Chafei'})
local trackChafeiScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H47M] 持续跟踪ddg_chafei')
ScenEdit_SetKeyValue('chafei_tracked', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'TrackChafei_Script', ScriptText = trackChafeiScript})
ScenEdit_SetEventAction(evTrackChafei.guid, {mode = 'add', name = 'TrackChafei_Script'})

-- T0+1H48M: Satellite W051 tracks ddg_chafei (link 20003)
local T1H48M_Chafei = T0 + (1 * 3600 + 48 * 60)
local evTrack2Chafei = ScenEdit_SetEvent('ST01_ST03_Track2_Chafei', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H48M_Chafei', time = T1H48M_Chafei})
ScenEdit_SetEventTrigger(evTrack2Chafei.guid, {mode = 'add', name = 'T0+1H48M_Chafei'})
local track2ChafeiScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H48M] ddg_chafei航向航速已确定')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Track2Chafei_Script', ScriptText = track2ChafeiScript})
ScenEdit_SetEventAction(evTrack2Chafei.guid, {mode = 'add', name = 'Track2Chafei_Script'})

-- T0+1H49M: Satellite W051 aims ddg_chafei (link 20004)
local T1H49M_Chafei = T0 + (1 * 3600 + 49 * 60)
local evAimChafei = ScenEdit_SetEvent('ST01_ST03_Aim_Chafei', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H49M_Chafei', time = T1H49M_Chafei})
ScenEdit_SetEventTrigger(evAimChafei.guid, {mode = 'add', name = 'T0+1H49M_Chafei'})
local aimChafeiScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H49M] ddg_chafei瞄准完成')
ScenEdit_SetKeyValue('chafei_aimed', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AimChafei_Script', ScriptText = aimChafeiScript})
ScenEdit_SetEventAction(evAimChafei.guid, {mode = 'add', name = 'AimChafei_Script'})

-- T0+0S: Engage ddg_chafei (DF-26B D004, D006 + DF-26D D3007, D3008 + J-16D JD002, JD007 + H-6K HK007, HK008)
local evEngageChafei = ScenEdit_SetEvent('ST01_ST03_Engage_Chafei', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+0S_Chafei', time = T0})
ScenEdit_SetEventTrigger(evEngageChafei.guid, {mode = 'add', name = 'T0+0S_Chafei'})
local engageChafeiScript = [[
ScenEdit_SetMission('Red', 'Red-Strike-CHAFEI', {isactive = true})
ScenEdit_SpecialMessage('Red', '[T+0S] 反舰打击开始 - ddg_chafei进入DF-26射程')
ScenEdit_SpecialMessage('Blue', '[ALERT] DDG Chafei under missile attack!')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'EngageChafei_Script', ScriptText = engageChafeiScript})
ScenEdit_SetEventAction(evEngageChafei.guid, {mode = 'add', name = 'EngageChafei_Script'})

-- T0+2H10M: Assessment ddg_chafei (link 20006)
local evAssessChafei = ScenEdit_SetEvent('ST01_ST03_Assess_Chafei', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H10M_Chafei', time = T2H10M})
ScenEdit_SetEventTrigger(evAssessChafei.guid, {mode = 'add', name = 'T0+2H10M_Chafei'})
local assessChafeiScript = [[
ScenEdit_SpecialMessage('Red', '[T+2H10M] 天基侦察评估ddg_chafei毁伤效果')
ScenEdit_SetKeyValue('chafei_assessed', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessChafei_Script', ScriptText = assessChafeiScript})
ScenEdit_SetEventAction(evAssessChafei.guid, {mode = 'add', name = 'AssessChafei_Script'})

-- T0+2H24M: Assessment complete ddg_chafei
local evAssessDoneChafei = ScenEdit_SetEvent('ST01_ST03_AssessDone_Chafei', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H24M_Chafei', time = T2H24M})
ScenEdit_SetEventTrigger(evAssessDoneChafei.guid, {mode = 'add', name = 'T0+2H24M_Chafei'})
local assessDoneChafeiScript = [[
local chafei_guid = ScenEdit_GetKeyValue('BLUE_DDG_CHAFEI_GUID')
if chafei_guid and chafei_guid ~= '' then
    local ok, u = pcall(ScenEdit_GetUnit, {guid = chafei_guid})
    if ok and u then
        if u.damage and u.damage > 0.5 then
            ScenEdit_SpecialMessage('Red', '[T+2H24M] 毁评结果: ddg_chafei毁伤率>50%，任务完成')
            ScenEdit_SetScore('Red', 100, 'ddg_chafei destroyed')
        else
            ScenEdit_SpecialMessage('Red', '[T+2H24M] 毁评结果: ddg_chafei需要补充打击')
        end
    end
end
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessDoneChafei_Script', ScriptText = assessDoneChafeiScript})
ScenEdit_SetEventAction(evAssessDoneChafei.guid, {mode = 'add', name = 'AssessDoneChafei_Script'})

-- === ST-01-001: 打击lha_meiguo Timeline ===

-- T0+1H47M: Satellite W051 finds lha_meiguo (link 30001)
local evFindLHA = ScenEdit_SetEvent('ST01_ST01_Find_LHA', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H47M_LHA', time = T1H46M})
ScenEdit_SetEventTrigger(evFindLHA.guid, {mode = 'add', name = 'T0+1H47M_LHA'})
local findLHAScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H47M] 天基侦察卫星发现蓝方两栖攻击舰(lha_meiguo)')
ScenEdit_SpecialMessage('Red', '目标坐标: lat=7.922858, lon=120.093579')
ScenEdit_SetKeyValue('lha_found', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'FindLHA_Script', ScriptText = findLHAScript})
ScenEdit_SetEventAction(evFindLHA.guid, {mode = 'add', name = 'FindLHA_Script'})

-- T0+1H48M: Satellite W051 locates lha_meiguo (link 30002)
local T1H48M_LHA = T0 + (1 * 3600 + 48 * 60)
local evLocLHA = ScenEdit_SetEvent('ST01_ST01_Locate_LHA', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H48M_LHA', time = T1H48M_LHA})
ScenEdit_SetEventTrigger(evLocLHA.guid, {mode = 'add', name = 'T0+1H48M_LHA'})
local locateLHAScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H48M] 定位lha_meiguo，目标精确坐标已确认')
ScenEdit_SetKeyValue('lha_located', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'LocateLHA_Script', ScriptText = locateLHAScript})
ScenEdit_SetEventAction(evLocLHA.guid, {mode = 'add', name = 'LocateLHA_Script'})

-- T0+1H49M: Satellite W051 tracks lha_meiguo (link 30003)
local T1H49M_LHA = T0 + (1 * 3600 + 49 * 60)
local evTrackLHA = ScenEdit_SetEvent('ST01_ST01_Track_LHA', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H49M_LHA', time = T1H49M_LHA})
ScenEdit_SetEventTrigger(evTrackLHA.guid, {mode = 'add', name = 'T0+1H49M_LHA'})
local trackLHAScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H49M] 持续跟踪lha_meiguo，航向航速已确定')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'TrackLHA_Script', ScriptText = trackLHAScript})
ScenEdit_SetEventAction(evTrackLHA.guid, {mode = 'add', name = 'TrackLHA_Script'})

-- T0+1H50M: Satellite W051 aims lha_meiguo (link 30004)
local T1H50M_LHA = T0 + (1 * 3600 + 50 * 60)
local evAimLHA = ScenEdit_SetEvent('ST01_ST01_Aim_LHA', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H50M_LHA', time = T1H50M_LHA})
ScenEdit_SetEventTrigger(evAimLHA.guid, {mode = 'add', name = 'T0+1H50M_LHA'})
local aimLHAScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H50M] lha_meiguo瞄准完成，J-20战斗机挂弹待发')
ScenEdit_SpecialMessage('Red', 'H-6K轰炸机群开始滑行准备')
ScenEdit_SetMission('Red', 'Red-CAP', {isactive = true})
ScenEdit_SetKeyValue('lha_aimed', '1')
ScenEdit_SetKeyValue('plan_phase', '3')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AimLHA_Script', ScriptText = aimLHAScript})
ScenEdit_SetEventAction(evAimLHA.guid, {mode = 'add', name = 'AimLHA_Script'})

-- T0+0S: Engage lha_meiguo (DF-26B: D001,D002,D003,D005,D011,D012 + DF-26D: D3001,D3002,D3003,D3005,D3011,D3012 + KJ500 KJ002 + J-20A: ZD001-ZD004)
local evEngageLHA = ScenEdit_SetEvent('ST01_ST01_Engage_LHA', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+0S_LHA', time = T0})
ScenEdit_SetEventTrigger(evEngageLHA.guid, {mode = 'add', name = 'T0+0S_LHA'})
local engageLHAScript = [[
ScenEdit_SetMission('Red', 'Red-Strike-LHA', {isactive = true})
ScenEdit_SpecialMessage('Red', '[T+0S] 反舰打击开始 - lha_meiguo进入DF-26射程，饱和攻击')
ScenEdit_SpecialMessage('Red', 'DF-26B/D弹道导弹 + J-20A战斗机 + H-6K轰炸机联合打击')
ScenEdit_SpecialMessage('Blue', '[CRITICAL] LHA America under massive missile attack!')
ScenEdit_SetKeyValue('plan_phase', '4')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'EngageLHA_Script', ScriptText = engageLHAScript})
ScenEdit_SetEventAction(evEngageLHA.guid, {mode = 'add', name = 'EngageLHA_Script'})

-- T0+2H10M: Assessment lha_meiguo
local evAssessLHA = ScenEdit_SetEvent('ST01_ST01_Assess_LHA', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H10M_LHA', time = T2H10M})
ScenEdit_SetEventTrigger(evAssessLHA.guid, {mode = 'add', name = 'T0+2H10M_LHA'})
local assessLHAScript = [[
ScenEdit_SpecialMessage('Red', '[T+2H10M] 天基侦察评估lha_meiguo毁伤效果')
ScenEdit_SetKeyValue('lha_assessed', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessLHA_Script', ScriptText = assessLHAScript})
ScenEdit_SetEventAction(evAssessLHA.guid, {mode = 'add', name = 'AssessLHA_Script'})

-- T0+2H24M: Assessment complete lha_meiguo
local T2H24M_LHA = T0 + (2 * 3600 + 24 * 60)
local evAssessDoneLHA = ScenEdit_SetEvent('ST01_ST01_AssessDone_LHA', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H24M_LHA', time = T2H24M_LHA})
ScenEdit_SetEventTrigger(evAssessDoneLHA.guid, {mode = 'add', name = 'T0+2H24M_LHA'})
local assessDoneLHAScript = [[
local lha_guid = ScenEdit_GetKeyValue('BLUE_LHA_MEIGUO_GUID')
if lha_guid and lha_guid ~= '' then
    local ok, u = pcall(ScenEdit_GetUnit, {guid = lha_guid})
    if ok and u then
        if u.damage and u.damage > 0.5 then
            ScenEdit_SpecialMessage('Red', '[T+2H24M] 毁评结果: lha_meiguo毁伤率>50%，任务完成')
            ScenEdit_SetScore('Red', 200, 'lha_meiguo destroyed')
        else
            ScenEdit_SpecialMessage('Red', '[T+2H24M] 毁评结果: lha_meiguo需要补充打击')
        end
    end
end
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessDoneLHA_Script', ScriptText = assessDoneLHAScript})
ScenEdit_SetEventAction(evAssessDoneLHA.guid, {mode = 'add', name = 'AssessDoneLHA_Script'})

-- === ST-01-004: 打击supply_kz Timeline ===

-- T0+1H53M: Satellite W003 finds supply_kz (link 40001)
local T1H53M_Supply = T0 + (1 * 3600 + 53 * 60)
local evFindSupply = ScenEdit_SetEvent('ST01_ST04_Find_Supply', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H53M_Supply', time = T1H53M_Supply})
ScenEdit_SetEventTrigger(evFindSupply.guid, {mode = 'add', name = 'T0+1H53M_Supply'})
local findSupplyScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H53M] 天基侦察卫星发现蓝方补给舰(supply_kz)')
ScenEdit_SpecialMessage('Red', '目标坐标: lat=-0.101186, lon=106.164261')
ScenEdit_SetKeyValue('supply_found', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'FindSupply_Script', ScriptText = findSupplyScript})
ScenEdit_SetEventAction(evFindSupply.guid, {mode = 'add', name = 'FindSupply_Script'})

-- T0+1H54M: Satellite W003 locates supply_kz (link 40002)
local T1H54M_Supply = T0 + (1 * 3600 + 54 * 60)
local evLocSupply = ScenEdit_SetEvent('ST01_ST04_Locate_Supply', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H54M_Supply', time = T1H54M_Supply})
ScenEdit_SetEventTrigger(evLocSupply.guid, {mode = 'add', name = 'T0+1H54M_Supply'})
local locateSupplyScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H54M] 定位supply_kz')
ScenEdit_SetKeyValue('supply_located', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'LocateSupply_Script', ScriptText = locateSupplyScript})
ScenEdit_SetEventAction(evLocSupply.guid, {mode = 'add', name = 'LocateSupply_Script'})

-- T0+1H55M: Satellite W003 tracks supply_kz (link 40003)
local T1H55M_Supply = T0 + (1 * 3600 + 55 * 60)
local evTrackSupply = ScenEdit_SetEvent('ST01_ST04_Track_Supply', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H55M_Supply', time = T1H55M_Supply})
ScenEdit_SetEventTrigger(evTrackSupply.guid, {mode = 'add', name = 'T0+1H55M_Supply'})
local trackSupplyScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H55M] 持续跟踪supply_kz')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'TrackSupply_Script', ScriptText = trackSupplyScript})
ScenEdit_SetEventAction(evTrackSupply.guid, {mode = 'add', name = 'TrackSupply_Script'})

-- T0+1H56M: Satellite W003 aims supply_kz (link 40004)
local T1H56M_Supply = T0 + (1 * 3600 + 56 * 60)
local evAimSupply = ScenEdit_SetEvent('ST01_ST04_Aim_Supply', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H56M_Supply', time = T1H56M_Supply})
ScenEdit_SetEventTrigger(evAimSupply.guid, {mode = 'add', name = 'T0+1H56M_Supply'})
local aimSupplyScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H56M] supply_kz瞄准完成')
ScenEdit_SetKeyValue('supply_aimed', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AimSupply_Script', ScriptText = aimSupplyScript})
ScenEdit_SetEventAction(evAimSupply.guid, {mode = 'add', name = 'AimSupply_Script'})

-- T0+0S: Engage supply_kz (DF-26D: D3009, D3010 + H-6K: HK003, HK004)
local evEngageSupply = ScenEdit_SetEvent('ST01_ST04_Engage_Supply', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+0S_Supply', time = T0})
ScenEdit_SetEventTrigger(evEngageSupply.guid, {mode = 'add', name = 'T0+0S_Supply'})
local engageSupplyScript = [[
ScenEdit_SetMission('Red', 'Red-Strike-SUPPLY', {isactive = true})
ScenEdit_SpecialMessage('Red', '[T+0S] 反舰打击开始 - supply_kz补给舰进入打击范围')
ScenEdit_SpecialMessage('Blue', '[ALERT] Supply ship under attack!')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'EngageSupply_Script', ScriptText = engageSupplyScript})
ScenEdit_SetEventAction(evEngageSupply.guid, {mode = 'add', name = 'EngageSupply_Script'})

-- T0+2H18M: Assessment supply_kz (link 40006)
local T2H18M_Supply = T0 + (2 * 3600 + 18 * 60)
local evAssessSupply = ScenEdit_SetEvent('ST01_ST04_Assess_Supply', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H18M_Supply', time = T2H18M_Supply})
ScenEdit_SetEventTrigger(evAssessSupply.guid, {mode = 'add', name = 'T0+2H18M_Supply'})
local assessSupplyScript = [[
ScenEdit_SpecialMessage('Red', '[T+2H18M] 天基侦察评估supply_kz毁伤效果')
ScenEdit_SetKeyValue('supply_assessed', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessSupply_Script', ScriptText = assessSupplyScript})
ScenEdit_SetEventAction(evAssessSupply.guid, {mode = 'add', name = 'AssessSupply_Script'})

-- T0+2H30M: Assessment complete supply_kz
local T2H30M_Supply = T0 + (2 * 3600 + 30 * 60)
local evAssessDoneSupply = ScenEdit_SetEvent('ST01_ST04_AssessDone_Supply', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H30M_Supply', time = T2H30M_Supply})
ScenEdit_SetEventTrigger(evAssessDoneSupply.guid, {mode = 'add', name = 'T0+2H30M_Supply'})
local assessDoneSupplyScript = [[
local supply_guid = ScenEdit_GetKeyValue('BLUE_SUPPLY_KZ_GUID')
if supply_guid and supply_guid ~= '' then
    local ok, u = pcall(ScenEdit_GetUnit, {guid = supply_guid})
    if ok and u then
        if u.damage and u.damage > 0.5 then
            ScenEdit_SpecialMessage('Red', '[T+2H30M] 毁评结果: supply_kz补给舰毁伤率>50%，任务完成')
            ScenEdit_SetScore('Red', 50, 'supply_kz destroyed')
        else
            ScenEdit_SpecialMessage('Red', '[T+2H30M] 毁评结果: supply_kz需要补充打击')
        end
    end
end
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessDoneSupply_Script', ScriptText = assessDoneSupplyScript})
ScenEdit_SetEventAction(evAssessDoneSupply.guid, {mode = 'add', name = 'AssessDoneSupply_Script'})

-- === ST-01-005: 打击ddg_momuseng Timeline ===

-- T0+1H46M: Satellite W051 finds ddg_momuseng (link 50001)
local evFindMomuseng = ScenEdit_SetEvent('ST01_ST05_Find_Momuseng', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H46M_Momuseng', time = T1H46M})
ScenEdit_SetEventTrigger(evFindMomuseng.guid, {mode = 'add', name = 'T0+1H46M_Momuseng'})
local findMomusengScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H46M] 天基侦察卫星发现蓝方伯克级驱逐舰(ddg_momuseng)')
ScenEdit_SpecialMessage('Red', '目标坐标: lat=7.104, lon=116.28')
ScenEdit_SetKeyValue('momuseng_found', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'FindMomuseng_Script', ScriptText = findMomusengScript})
ScenEdit_SetEventAction(evFindMomuseng.guid, {mode = 'add', name = 'FindMomuseng_Script'})

-- T0+1H47M: Satellite W051 locates ddg_momuseng (link 50002)
local T1H47M_Momuseng = T0 + (1 * 3600 + 47 * 60)
local evLocMomuseng = ScenEdit_SetEvent('ST01_ST05_Locate_Momuseng', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H47M_Momuseng', time = T1H47M_Momuseng})
ScenEdit_SetEventTrigger(evLocMomuseng.guid, {mode = 'add', name = 'T0+1H47M_Momuseng'})
local locateMomusengScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H47M] 定位ddg_momuseng')
ScenEdit_SetKeyValue('momuseng_located', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'LocateMomuseng_Script', ScriptText = locateMomusengScript})
ScenEdit_SetEventAction(evLocMomuseng.guid, {mode = 'add', name = 'LocateMomuseng_Script'})

-- T0+1H48M: Satellite W051 tracks ddg_momuseng (link 50003)
local T1H48M_Momuseng = T0 + (1 * 3600 + 48 * 60)
local evTrackMomuseng = ScenEdit_SetEvent('ST01_ST05_Track_Momuseng', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H48M_Momuseng', time = T1H48M_Momuseng})
ScenEdit_SetEventTrigger(evTrackMomuseng.guid, {mode = 'add', name = 'T0+1H48M_Momuseng'})
local trackMomusengScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H48M] 持续跟踪ddg_momuseng')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'TrackMomuseng_Script', ScriptText = trackMomusengScript})
ScenEdit_SetEventAction(evTrackMomuseng.guid, {mode = 'add', name = 'TrackMomuseng_Script'})

-- T0+1H49M: Satellite W051 aims ddg_momuseng (link 50004)
local T1H49M_Momuseng = T0 + (1 * 3600 + 49 * 60)
local evAimMomuseng = ScenEdit_SetEvent('ST01_ST05_Aim_Momuseng', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+1H49M_Momuseng', time = T1H49M_Momuseng})
ScenEdit_SetEventTrigger(evAimMomuseng.guid, {mode = 'add', name = 'T0+1H49M_Momuseng'})
local aimMomusengScript = [[
ScenEdit_SpecialMessage('Red', '[T+1H49M] ddg_momuseng瞄准完成')
ScenEdit_SetKeyValue('momuseng_aimed', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AimMomuseng_Script', ScriptText = aimMomusengScript})
ScenEdit_SetEventAction(evAimMomuseng.guid, {mode = 'add', name = 'AimMomuseng_Script'})

-- T0+0S: Engage ddg_momuseng (DF-26B: D009, D010 + DF-26D: D3009, D3010 + H-6K: HK003, HK004)
local evEngageMomuseng = ScenEdit_SetEvent('ST01_ST05_Engage_Momuseng', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+0S_Momuseng', time = T0})
ScenEdit_SetEventTrigger(evEngageMomuseng.guid, {mode = 'add', name = 'T0+0S_Momuseng'})
local engageMomusengScript = [[
ScenEdit_SetMission('Red', 'Red-Strike-MOMUSENG', {isactive = true})
ScenEdit_SpecialMessage('Red', '[T+0S] 反舰打击开始 - ddg_momuseng进入DF-26射程')
ScenEdit_SpecialMessage('Blue', '[ALERT] DDG Momuseng under missile attack!')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'EngageMomuseng_Script', ScriptText = engageMomusengScript})
ScenEdit_SetEventAction(evEngageMomuseng.guid, {mode = 'add', name = 'EngageMomuseng_Script'})

-- T0+2H10M: Assessment ddg_momuseng (link 50006)
local evAssessMomuseng = ScenEdit_SetEvent('ST01_ST05_Assess_Momuseng', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H10M_Momuseng', time = T2H10M})
ScenEdit_SetEventTrigger(evAssessMomuseng.guid, {mode = 'add', name = 'T0+2H10M_Momuseng'})
local assessMomusengScript = [[
ScenEdit_SpecialMessage('Red', '[T+2H10M] 天基侦察评估ddg_momuseng毁伤效果')
ScenEdit_SetKeyValue('momuseng_assessed', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessMomuseng_Script', ScriptText = assessMomusengScript})
ScenEdit_SetEventAction(evAssessMomuseng.guid, {mode = 'add', name = 'AssessMomuseng_Script'})

-- T0+2H24M: Assessment complete ddg_momuseng
local T2H24M_Momuseng = T0 + (2 * 3600 + 24 * 60)
local evAssessDoneMomuseng = ScenEdit_SetEvent('ST01_ST05_AssessDone_Momuseng', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+2H24M_Momuseng', time = T2H24M_Momuseng})
ScenEdit_SetEventTrigger(evAssessDoneMomuseng.guid, {mode = 'add', name = 'T0+2H24M_Momuseng'})
local assessDoneMomusengScript = [[
local momuseng_guid = ScenEdit_GetKeyValue('BLUE_DDG_MOMUSENG_GUID')
if momuseng_guid and momuseng_guid ~= '' then
    local ok, u = pcall(ScenEdit_GetUnit, {guid = momuseng_guid})
    if ok and u then
        if u.damage and u.damage > 0.5 then
            ScenEdit_SpecialMessage('Red', '[T+2H24M] 毁评结果: ddg_momuseng毁伤率>50%，任务完成')
            ScenEdit_SetScore('Red', 100, 'ddg_momuseng destroyed')
        else
            ScenEdit_SpecialMessage('Red', '[T+2H24M] 毁评结果: ddg_momuseng需要补充打击')
        end
    end
end
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AssessDoneMomuseng_Script', ScriptText = assessDoneMomusengScript})
ScenEdit_SetEventAction(evAssessDoneMomuseng.guid, {mode = 'add', name = 'AssessDoneMomuseng_Script'})

-- ============================================================
-- SECTION 9: EMCON Control
-- ============================================================

-- Red EW aircraft: Active EMCON for electronic warfare
for _, pid in ipairs({'JD002', 'JD003', 'JD004', 'JD007'}) do
    local guid = ScenEdit_GetKeyValue('J16D_' .. pid .. '_GUID')
    if guid and guid ~= '' then
        pcall(ScenEdit_SetEMCON, 'Unit', guid, 'Radar=Passive;OECM=Active')
    end
end

-- Red AWACS: Active radar
local kj_guid = ScenEdit_GetKeyValue('KJ500_KJ002_GUID')
if kj_guid and kj_guid ~= '' then
    pcall(ScenEdit_SetEMCON, 'Unit', kj_guid, 'Radar=Active')
end

-- Red fighters: Default EMCON
for _, pid in ipairs({'ZD001', 'ZD002', 'ZD003', 'ZD004'}) do
    local guid = ScenEdit_GetKeyValue('J20A_' .. pid .. '_GUID')
    if guid and guid ~= '' then
        pcall(ScenEdit_SetEMCON, 'Unit', guid, 'Radar=Active')
    end
end

-- ============================================================
-- SECTION 10: Summary
-- ============================================================
print('============================================')
print('plan_a1_001_legacy - Joint Counter-Attack Plan')
print('============================================')
print('RED SIDE:')
print('  DF-26B SSM:      12 units (DBID=89 DF-21C proxy)')
print('  DF-26D SSM:      12 units (DBID=89 DF-21C proxy)')
print('  J-16D EW:         4 units (DBID=4632 Loadout=753)')
print('  H-6K Bomber:      6 units (DBID=1731 Loadout=863)')
print('  KJ-500 AWACS:     1 unit  (DBID=3683 Loadout=494)')
print('  J-20A Fighter:    4 units (DBID=5012 Loadout=1191)')
print('BLUE SIDE (Targets):')
print('  TICO Simoer:      1 unit  (DBID=40)  @ 7.97N, 119.50E')
print('  DDG Chafei:       1 unit  (DBID=111) @ 8.28N, 119.78E')
print('  LHA America:      1 unit  (DBID=170) @ 7.92N, 120.09E')
print('  AUX Supply:       1 unit  (DBID=753) @ 0.10S, 106.16E')
print('  DDG Momuseng:     1 unit  (DBID=111) @ 7.10N, 116.28E')
print('KILL CHAINS:')
print('  ST-01-001: 打击lha_meiguo')
print('  ST-01-002: 打击tico_simoer')
print('  ST-01-003: 打击ddg_chafei')
print('  ST-01-004: 打击supply_kz')
print('  ST-01-005: 打击ddg_momuseng')
print('SKIPPED (MCP not found):')
print('  SAT_JIANBING23 - Satellite Jianbing-23 (no CMO equivalent)')
print('  UUV_RED - Chinese UUV (not in current DB)')
print('============================================')
ScenEdit_SpecialMessage('Red', 'plan_a1_001_legacy 联合反击作战方案初始化完成')
