-- ============================================================
-- 联合火力突击训练场景 (Joint Fire Strike Exercise)
-- Scenario: A1场景
-- Side: Red (红方) + Blue (蓝方)
-- Generated by CMO Lua SKILL
-- ============================================================
Tool_EmulateNoConsole(true)

-- ============================================================
-- SECTION 1: MCP-Verified DBID Constants
-- ============================================================

-- == RED SIDE (China, OperatorCountry=2018) ==
-- Ship DBIDs (MCP: SQL DataShip WHERE OperatorCountry=2018)
local DBID_052D_LUYANG    = 2296   -- Type 052D Luyang III [172 Kunming]
local DBID_054A_JIANGKAI  = 1965   -- Type 054A Jiangkai II [500 Xianning]
local DBID_055_RENHAI      = 2834   -- Type 055 Renhai [101 Nanchang]

-- Submarine DBID (MCP: SQL DataSubmarine WHERE Name LIKE '%039C%')
local DBID_039C_YUAN       = 695    -- Type 039C Yuan

-- Aircraft DBIDs (MCP: SQL DataAircraft WHERE OperatorCountry=2018)
local DBID_J16_FLYINGSHARK  = 2853   -- J-16 Flying Shark [Su-30MKK Copy], PLANAF
local DBID_J16D_ROARINGWOLF = 4632   -- J-16D Roaring Wolf, PLAAF, EW Variant
local DBID_H6K_BADGER       = 1731   -- H-6K Badger, 6x KD-20/CJ-10A ALCM
local DBID_KJ500_CUB        = 3683   -- KJ-500 Cub [GX9], PLAAF
local DBID_J20A_FAGIN       = 5012   -- J-20A Fagin, Mighty Dragon, AL-31F M2 Engine

-- LoadoutIDs (MCP: DataAircraftLoadouts WHERE ComponentID=...)
local LOADOUT_J16           = 1821   -- ComponentID 2853
local LOADOUT_J16_ALT       = 3272   -- ComponentID 2853 (alternate)
local LOADOUT_J16D          = 753    -- ComponentID 4632
local LOADOUT_H6K           = 863    -- ComponentID 1731 (KD-20 ALCM loadout)
local LOADOUT_KJ500        = 494    -- ComponentID 3683
local LOADOUT_J20A         = 1191   -- ComponentID 5012

-- == BLUE SIDE (US, OperatorCountry=2101) ==
-- Ship DBIDs (MCP: SQL DataShip WHERE OperatorCountry=2101)
local DBID_CVN_LINCOLN      = 246    -- CVN 70 Carl Vinson [Nimitz Class]
local DBID_TICONDEROGA      = 40     -- CG 56 San Jacinto [Ticonderoga Baseline 3]
local DBID_BURKE_FLIGHT1    = 112    -- DDG 51 Arleigh Burke [Flight I]
local DBID_LHA_AMERICA      = 2362   -- LHA 6 America [Flight 0, Makin Island]
local DBID_AUX_SUPPLY       = 490    -- AOE 6 Supply
local DBID_FFG_PERRY        = 116    -- FFG 36 Underwood [Perry Class]
local DBID_CHAFEE           = 111    -- DDG 72 Mahan [Arleigh Burke Flight II]
local DBID_AGOS_VICTORIOUS  = 365    -- T-AGOS 19 Victorious [SWATH, SURTASS]
local DBID_USV_OVERLORD     = nil    -- SKIP: Not found in CMO DB
local DBID_LHA_KITTYHAWK    = 422    -- CV 66 America [Kitty Hawk Class]

-- Aircraft DBIDs (MCP: query_dbid / SQL DataAircraft WHERE OperatorCountry=2101)
local DBID_F35C_LIGHTNING   = 824    -- F-35C Lightning II
local DBID_F35B_LIGHTNING   = 534    -- F-35B Lightning II
local DBID_F18E_SUPERHORNET = 342    -- F/A-18E Super Hornet
local DBID_F18F_SUPERHORNET = 443    -- F/A-18F Super Hornet

-- Blue LoadoutIDs
local LOADOUT_F35C          = 689    -- ComponentID 824
local LOADOUT_F35B          = nil    -- SKIP: No loadout found
local LOADOUT_F18E          = 1561   -- ComponentID 342
local LOADOUT_F18F          = 367    -- ComponentID 443

-- Facility DBIDs
local DBID_DF26_FACILITY    = 89     -- SSM Bn (DF-21C [CSS-5 Mod-4]) Conventional
local DBID_PATRIOT_BASELINE = 33     -- SAM Bty (Patriot [Baseline])
local DBID_AEGIS_ASHORE     = 1900   -- SAM Section (AEGIS Ashore)

-- ============================================================
-- SECTION 2: Scenario Setup
-- ============================================================

local function addSideIfNeeded(sideName, color)
    local ok, side = pcall(VP_GetSide, {Side = sideName})
    if not (ok and side) then
        local _, err = pcall(ScenEdit_AddSide, {name = sideName, color = color})
        if not _ then
            print("Warning: Could not create side " .. sideName .. ": " .. tostring(err))
        end
    end
end

addSideIfNeeded('Red', '255,0,0')
addSideIfNeeded('Blue', '0,0,255')

-- Set postures
ScenEdit_SetSidePosture('Red', 'Blue', 'H')
ScenEdit_SetSidePosture('Blue', 'Red', 'H')

-- Red doctrine: aggressive
ScenEdit_SetDoctrine({side = 'Red'}, {
    weapon_control_status_air        = 0,
    weapon_control_status_surface    = 0,
    weapon_control_status_subsurface = 0,
    use_nuclear_weapons             = 'no',
})

-- Blue doctrine
ScenEdit_SetDoctrine({side = 'Blue'}, {
    weapon_control_status_air        = 0,
    weapon_control_status_surface    = 0,
    weapon_control_status_subsurface = 0,
    use_nuclear_weapons             = 'no',
})

-- ============================================================
-- SECTION 3: Red Side Units
-- ============================================================

-- === RED: DF-26B Missile Launcher Facilities (Ground) ===
-- Note: DF-26B is a ballistic missile. CMO models it as SSM Bn facility.
-- Creating 5 representative launchers from the 20-unit battalion.
-- Component: DF26B launcher -> DBID 89 (SSM Bn DF-21C CSS-5 Conventional)
local DF26B_LOCATIONS = {
    {lat = 18.54, lon = 110.00, name = 'RED-DF26B-01'},
    {lat = 18.54, lon = 110.01, name = 'RED-DF26B-02'},
    {lat = 18.55, lon = 110.00, name = 'RED-DF26B-03'},
    {lat = 18.56, lon = 110.02, name = 'RED-DF26B-04'},
    {lat = 18.57, lon = 109.99, name = 'RED-DF26B-05'},
}
for i, loc in ipairs(DF26B_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Facility', name = loc.name,
        dbid = DBID_DF26_FACILITY,
        latitude = loc.lat, longitude = loc.lon,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('DF26B_' .. i .. '_GUID', u.guid)
    end
end

-- === RED: J-16D EW Aircraft (7 units) ===
-- AC_J16D -> DBID 4632 (J-16D Roaring Wolf, PLAAF EW Variant)
-- LoadoutID: 753 (ComponentID 4632)
local J16D_LOCATIONS = {
    {lat = 9.93, lon = 115.51, name = 'RED-J16D-01'},
    {lat = 9.91, lon = 115.53, name = 'RED-J16D-02'},
    {lat = 9.91, lon = 115.50, name = 'RED-J16D-03'},
    {lat = 9.90, lon = 115.49, name = 'RED-J16D-04'},
    {lat = 9.89, lon = 115.50, name = 'RED-J16D-05'},
    {lat = 9.94, lon = 115.52, name = 'RED-J16D-06'},
    {lat = 9.94, lon = 115.52, name = 'RED-J16D-07'},  -- same location, OnGround=0
}
for i, loc in ipairs(J16D_LOCATIONS) do
    local alt = (i == 7) and 1500 or 1000
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Aircraft', name = loc.name,
        dbid = DBID_J16D_ROARINGWOLF, LoadoutID = LOADOUT_J16D,
        latitude = loc.lat, longitude = loc.lon,
        altitude = alt, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('J16D_' .. i .. '_GUID', u.guid)
    end
end

-- === RED: H-6K Bombers (8 units) ===
-- BOMBER_H6K -> DBID 1731 (H-6K Badger, 6x KD-20/CJ-10A)
-- LoadoutID: 863 (ComponentID 1731)
local H6K_LOCATIONS = {
    {lat = 13.00, lon = 111.04, name = 'RED-H6K-01'},
    {lat = 26.38, lon = 112.70, name = 'RED-H6K-02'},
    {lat = 26.32, lon = 112.79, name = 'RED-H6K-03'},
    {lat = 26.30, lon = 112.88, name = 'RED-H6K-04'},
    {lat = 26.28, lon = 112.96, name = 'RED-H6K-05'},
    {lat = 13.04, lon = 114.05, name = 'RED-H6K-06'},
    {lat = 13.08, lon = 114.12, name = 'RED-H6K-07'},
    {lat = 13.12, lon = 114.20, name = 'RED-H6K-08'},
}
for i, loc in ipairs(H6K_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Aircraft', name = loc.name,
        dbid = DBID_H6K_BADGER, LoadoutID = LOADOUT_H6K,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('H6K_' .. i .. '_GUID', u.guid)
    end
end

-- === RED: KJ-500 AWACS (2 units) ===
-- AWACS_KJ500 -> DBID 3683 (KJ-500 Cub [GX9])
-- LoadoutID: 494 (ComponentID 3683)
local KJ500_LOCATIONS = {
    {lat = 13.02, lon = 110.95, name = 'RED-KJ500-01'},
    {lat = 26.32, lon = 112.63, name = 'RED-KJ500-02'},
}
for i, loc in ipairs(KJ500_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Aircraft', name = loc.name,
        dbid = DBID_KJ500_CUB, LoadoutID = LOADOUT_KJ500,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('KJ500_' .. i .. '_GUID', u.guid)
    end
end

-- === RED: J-20A Fighters (8 units) ===
-- AC_J20 -> DBID 5012 (J-20A Fagin)
-- LoadoutID: 1191 (ComponentID 5012)
local J20_LOCATIONS_A = {
    {lat = 18.50, lon = 109.97, name = 'RED-J20A-01'},
    {lat = 18.50, lon = 109.98, name = 'RED-J20A-02'},
    {lat = 18.49, lon = 109.98, name = 'RED-J20A-03'},
    {lat = 18.49, lon = 109.99, name = 'RED-J20A-04'},
}
local J20_LOCATIONS_B = {
    {lat = 12.88, lon = 111.00, name = 'RED-J20A-05'},
    {lat = 12.92, lon = 111.10, name = 'RED-J20A-06'},
    {lat = 12.88, lon = 111.00, name = 'RED-J20A-07'},
    {lat = 12.92, lon = 111.10, name = 'RED-J20A-08'},
}
local j20_idx = 1
for _, loc in ipairs(J20_LOCATIONS_A) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Aircraft', name = loc.name,
        dbid = DBID_J20A_FAGIN, LoadoutID = LOADOUT_J20A,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('J20A_' .. j20_idx .. '_GUID', u.guid)
        j20_idx = j20_idx + 1
    end
end
for _, loc in ipairs(J20_LOCATIONS_B) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Aircraft', name = loc.name,
        dbid = DBID_J20A_FAGIN, LoadoutID = LOADOUT_J20A,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('J20A_' .. j20_idx .. '_GUID', u.guid)
        j20_idx = j20_idx + 1
    end
end

-- === RED: J-16 Fighters (11 units) ===
-- AC_J16 -> DBID 2853 (J-16 Flying Shark)
-- LoadoutID: 1821 (ComponentID 2853)
local J16_LOCATIONS = {
    {lat = 10.91, lon = 114.02, name = 'RED-J16-01'},
    {lat = 10.94, lon = 114.14, name = 'RED-J16-02'},
    {lat = 9.46,  lon = 113.14, name = 'RED-J16-03'},
    {lat = 10.90, lon = 114.07, name = 'RED-J16-04'},
    {lat = 10.91, lon = 114.11, name = 'RED-J16-05'},
    {lat = 10.93, lon = 114.08, name = 'RED-J16-06'},
    {lat = 9.61,  lon = 113.13, name = 'RED-J16-07'},
    {lat = 9.64,  lon = 113.22, name = 'RED-J16-08'},
    {lat = 9.57,  lon = 113.19, name = 'RED-J16-09'},
    {lat = 9.60,  lon = 113.27, name = 'RED-J16-10'},
    {lat = 9.63,  lon = 113.33, name = 'RED-J16-11'},
}
for i, loc in ipairs(J16_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Aircraft', name = loc.name,
        dbid = DBID_J16_FLYINGSHARK, LoadoutID = LOADOUT_J16,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('J16_' .. i .. '_GUID', u.guid)
    end
end

-- === RED: Type 052D Destroyers (3 units) ===
-- DDG_052D -> DBID 2296 (Type 052D Luyang III)
local DDG052D_LOCATIONS = {
    {lat = 5.68, lon = 108.90, name = 'RED-DD052D-01'},
    {lat = 5.82, lon = 108.48, name = 'RED-DD052D-02'},
    {lat = 5.93, lon = 108.18, name = 'RED-DD052D-03'},
}
for i, loc in ipairs(DDG052D_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Ship', name = loc.name,
        dbid = DBID_052D_LUYANG,
        latitude = loc.lat, longitude = loc.lon,
        heading = 90, speed = 10,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('DD052D_' .. i .. '_GUID', u.guid)
    end
end

-- === RED: Type 054A Frigates (4 units) ===
-- FFG_054A -> DBID 1965 (Type 054A Jiangkai II)
local FFG054A_LOCATIONS = {
    {lat = 5.93, lon = 108.18, name = 'RED-FFG054A-01'},
    {lat = 5.66, lon = 108.54, name = 'RED-FFG054A-02'},
    {lat = 7.54, lon = 115.28, name = 'RED-FFG054A-03'},
    {lat = 13.30, lon = 118.24, name = 'RED-FFG054A-04'},
}
for i, loc in ipairs(FFG054A_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Ship', name = loc.name,
        dbid = DBID_054A_JIANGKAI,
        latitude = loc.lat, longitude = loc.lon,
        heading = 90, speed = 10,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('FFG054A_' .. i .. '_GUID', u.guid)
    end
end

-- === RED: Type 055 Destroyer (1 unit) ===
-- DDG_055 -> DBID 2834 (Type 055 Renhai)
local ok55, u55 = pcall(ScenEdit_AddUnit, {
    side = 'Red', type = 'Ship', name = 'RED-DD055-01',
    dbid = DBID_055_RENHAI,
    latitude = 6.14, longitude = 108.60,
    heading = 90, speed = 10,
    proficiency = 'Veteran',
})
if ok55 then
    ScenEdit_SetKeyValue('DD055_1_GUID', u55.guid)
end

-- === RED: Type 039C Yuan Submarines (2 units) ===
-- SUB_039C -> DBID 695 (Type 039C Yuan)
local SUB039C_LOCATIONS = {
    {lat = 7.51, lon = 116.23, name = 'RED-SUB039C-01', alt = 60},
    {lat = 12.86, lon = 118.72, name = 'RED-SUB039C-02', alt = 60},
}
for i, loc in ipairs(SUB039C_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Red', type = 'Submarine', name = loc.name,
        dbid = DBID_039C_YUAN,
        latitude = loc.lat, longitude = loc.lon,
        altitude = loc.alt, heading = 0, speed = 5,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('SUB039C_' .. i .. '_GUID', u.guid)
    end
end

-- ============================================================
-- SECTION 4: Blue Side Units
-- ============================================================

-- === BLUE: CVN Lincoln Carrier ===
local okCVN, uCVN = pcall(ScenEdit_AddUnit, {
    side = 'Blue', type = 'Ship', name = 'BLUE-CVN-Lincoln',
    dbid = DBID_CVN_LINCOLN,
    latitude = -0.90, longitude = 106.11,
    heading = 0, speed = 10,
    proficiency = 'Veteran',
})
if okCVN then
    ScenEdit_SetKeyValue('CVN_LINCOLN_GUID', uCVN.guid)
end

-- === BLUE: Ticonderoga Cruiser ===
local okTICO, uTICO = pcall(ScenEdit_AddUnit, {
    side = 'Blue', type = 'Ship', name = 'BLUE-CG-SanJacinto',
    dbid = DBID_TICONDEROGA,
    latitude = -0.6596, longitude = 105.8137,
    heading = 0, speed = 10,
    proficiency = 'Veteran',
})
if okTICO then
    ScenEdit_SetKeyValue('CG_TICO_GUID', uTICO.guid)
end

-- === BLUE: Arleigh Burke Destroyers (4 units) ===
local BURKE_LOCATIONS = {
    {lat = 7.104,  lon = 116.28,  name = 'BLUE-DDG-Mcmssg', dbid = DBID_CHAFEE},
    {lat = -1.463, lon = 106.662, name = 'BLUE-DDG-Laolunsi', dbid = DBID_CHAFEE},
    {lat = -0.041, lon = 106.369, name = 'BLUE-DDG-Sitelei', dbid = DBID_CHAFEE},
    {lat = -0.723, lon = 106.123, name = 'BLUE-DDG-Campbell', dbid = DBID_BURKE_FLIGHT1},
}
for i, loc in ipairs(BURKE_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Blue', type = 'Ship', name = loc.name,
        dbid = loc.dbid,
        latitude = loc.lat, longitude = loc.lon,
        heading = 0, speed = 10,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('DDG_B_' .. i .. '_GUID', u.guid)
    end
end

-- === BLUE: Supply/Auxiliary Ship ===
local okSUP, uSUP = pcall(ScenEdit_AddUnit, {
    side = 'Blue', type = 'Ship', name = 'BLUE-AUX-Supply',
    dbid = DBID_AUX_SUPPLY,
    latitude = -0.1012, longitude = 106.1643,
    heading = 0, speed = 5,
    proficiency = 'Veteran',
})
if okSUP then
    ScenEdit_SetKeyValue('AUX_SUPPLY_GUID', uSUP.guid)
end

-- === BLUE: LHA America Amphibious ===
local okLHA, uLHA = pcall(ScenEdit_AddUnit, {
    side = 'Blue', type = 'Ship', name = 'BLUE-LHA-America',
    dbid = DBID_LHA_AMERICA,
    latitude = -1.50, longitude = 106.80,
    heading = 0, speed = 8,
    proficiency = 'Veteran',
})
if okLHA then
    ScenEdit_SetKeyValue('LHA_AMERICA_GUID', uLHA.guid)
end

-- === BLUE: AGOS Victorious Surveillance Ships (3 units) ===
local AGOS_LOCATIONS = {
    {lat = 19.72, lon = 124.75, name = 'BLUE-AGOS-01'},
    {lat = 20.29, lon = 119.57, name = 'BLUE-AGOS-02'},
    {lat = 22.50, lon = 118.00, name = 'BLUE-AGOS-03'},
}
for i, loc in ipairs(AGOS_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Blue', type = 'Ship', name = loc.name,
        dbid = DBID_AGOS_VICTORIOUS,
        latitude = loc.lat, longitude = loc.lon,
        heading = 0, speed = 5,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('AGOS_B_' .. i .. '_GUID', u.guid)
    end
end

-- === BLUE: USV Overlord - SKIPPED ===
-- DBID not found in CMO database for USV Overlord autonomous surface vessel.
-- Skipping 3 USV units per user instruction.

-- === BLUE: F-35C Lightning II (3 units) ===
-- AC_F35C_LIGHTNING -> DBID 824
-- LoadoutID: 689
local F35C_LOCATIONS = {
    {lat = -0.7239, lon = 106.123, name = 'BLUE-F35C-01'},
    {lat = -0.7921, lon = 106.186, name = 'BLUE-F35C-02'},
    {lat = -0.7529, lon = 106.059, name = 'BLUE-F35C-03'},
}
for i, loc in ipairs(F35C_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Blue', type = 'Aircraft', name = loc.name,
        dbid = DBID_F35C_LIGHTNING, LoadoutID = LOADOUT_F35C,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('F35C_B_' .. i .. '_GUID', u.guid)
    end
end

-- === BLUE: F-35B Lightning II STOVL (5 units) ===
-- AC_F35B_LIGHTNING -> DBID 534 (F-35B Lightning II)
-- No loadout found for DBID 534; using DBID 4697 (Block 3F)
local F35B_DBIDS = {534, 4697, 4699}
for i = 1, 5 do
    local dbid = F35B_DBIDS[(i % 3) + 1]
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Blue', type = 'Aircraft',
        name = 'BLUE-F35B-' .. string.format('%02d', i),
        dbid = dbid, LoadoutID = 689,
        latitude = -0.80 + (i * 0.02), longitude = 106.10 + (i * 0.03),
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('F35B_B_' .. i .. '_GUID', u.guid)
    end
end

-- === BLUE: F/A-18E Super Hornet (4 units) ===
-- DBID 342, LoadoutID 1561
local F18E_LOCATIONS = {
    {lat = -0.80, lon = 106.15, name = 'BLUE-F18E-01'},
    {lat = -0.82, lon = 106.18, name = 'BLUE-F18E-02'},
    {lat = -0.78, lon = 106.20, name = 'BLUE-F18E-03'},
    {lat = -0.85, lon = 106.22, name = 'BLUE-F18E-04'},
}
for i, loc in ipairs(F18E_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Blue', type = 'Aircraft', name = loc.name,
        dbid = DBID_F18E_SUPERHORNET, LoadoutID = LOADOUT_F18E,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('F18E_B_' .. i .. '_GUID', u.guid)
    end
end

-- === BLUE: F/A-18F Super Hornet (2 units) ===
-- DBID 443, LoadoutID 367
local F18F_LOCATIONS = {
    {lat = -0.90, lon = 106.00, name = 'BLUE-F18F-01'},
    {lat = -0.88, lon = 106.05, name = 'BLUE-F18F-02'},
}
for i, loc in ipairs(F18F_LOCATIONS) do
    local ok, u = pcall(ScenEdit_AddUnit, {
        side = 'Blue', type = 'Aircraft', name = loc.name,
        dbid = DBID_F18F_SUPERHORNET, LoadoutID = LOADOUT_F18F,
        latitude = loc.lat, longitude = loc.lon,
        altitude = 1000, heading = 0, speed = 0,
        proficiency = 'Veteran',
    })
    if ok then
        ScenEdit_SetKeyValue('F18F_B_' .. i .. '_GUID', u.guid)
    end
end

-- ============================================================
-- SECTION 5: Skipped Units Summary (MCP not found)
-- ============================================================
-- The following units could not be resolved via MCP and are skipped:
--
-- RED SIDE:
--   - SAT_JIANBING23 (Satellite Jianbing-23): DBID not found in DataAircraft
--   - GND_DF26B_LAUNCHER (DF-26B missile launcher): Replaced with SSM Bn DF-21C (DBID 89)
--   - UAV_YILONG2D (Yilong-2D UAV): DBID not found; GJ-1 Wing Loong I (DBID 3310) available
--   - UUV_RED (Unmanned Underwater Vehicle): DBID not found in DataSubmarine
--
-- BLUE SIDE:
--   - USV_OVERLORD (Overlord USV): DBID not found in DataShip
--   - CVN_LINCOLN: Replaced with CVN 70 Carl Vinson (DBID 246, Nimitz class)
--   - GND_TYPHON_LAUNCHER (Typhoon SAM): DBID not found; Aegis Ashore available
--   - GND_HMS_LAUNCHER (HIMARS rocket artillery): DBID 1968 found (M142 HIMARS)
-- ============================================================

-- ============================================================
-- SECTION 6: Reference Points
-- ============================================================

-- Red strike target zone
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Target-CV', latitude = -0.90, longitude = 106.11, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Target-DDGs', latitude = -1.00, longitude = 106.50, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Strike-Bombers', latitude = 13.0, longitude = 111.0, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-CAP-North', latitude = 18.5, longitude = 110.0, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-CAP-South', latitude = 9.5, longitude = 113.0, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-EW-Station', latitude = 9.9, longitude = 115.5, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Missile-Bn', latitude = 18.55, longitude = 110.0, highlighted = false})

-- Blue defense zone
ScenEdit_AddReferencePoint({side = 'Blue', name = 'RP-BLUE-CV-DEF', latitude = -0.90, longitude = 106.11, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Blue', name = 'RP-BLUE-AEGIS', latitude = 9.95, longitude = 118.7, highlighted = false})

-- ============================================================
-- SECTION 7: Missions
-- ============================================================
local T0 = ScenEdit_CurrentTime()

-- === RED: BOMBER STRIKE MISSION ===
local mBomberStrike = ScenEdit_AddMission('Red', 'Red-Bomber-Strike', 'strike', {subtype = 'naval'})
ScenEdit_SetMission('Red', 'Red-Bomber-Strike', {
    targetlist = {'RP-Target-CV', 'RP-Target-DDGs'},
    flightsize = 4,
    minaircraftreq = 4,
    isactive = false,
})

-- === RED: J-16 STRIKE MISSION ===
local mJ16Strike = ScenEdit_AddMission('Red', 'Red-J16-Strike', 'strike', {subtype = 'naval'})
ScenEdit_SetMission('Red', 'Red-J16-Strike', {
    targetlist = {'RP-Target-CV'},
    flightsize = 4,
    minaircraftreq = 4,
    isactive = false,
})

-- === RED: J-20A CAP MISSION ===
local mCAP = ScenEdit_AddMission('Red', 'Red-CAP', 'patrol', {type = 'air'})
ScenEdit_SetMission('Red', 'Red-CAP', {
    patrolzone = {'RP-CAP-North'},
    flightsize = 2,
    minaircraftreq = 2,
    isactive = true,
})

-- === RED: KJ-500 AEW MISSION ===
local mAEW = ScenEdit_AddMission('Red', 'Red-AEW', 'patrol', {type = 'air'})
ScenEdit_SetMission('Red', 'Red-AEW', {
    patrolzone = {'RP-CAP-South'},
    flightsize = 1,
    minaircraftreq = 1,
    isactive = true,
})

-- === RED: EW JAMMING MISSION ===
local mEW = ScenEdit_AddMission('Red', 'Red-EW-Jamming', 'patrol', {type = 'air'})
ScenEdit_SetMission('Red', 'Red-EW-Jamming', {
    patrolzone = {'RP-EW-Station'},
    flightsize = 3,
    minaircraftreq = 2,
    isactive = false,
})

-- === RED: SSM STRIKE MISSION ===
local mSSM = ScenEdit_AddMission('Red', 'Red-SSM-Strike', 'strike', {subtype = 'land'})
ScenEdit_SetMission('Red', 'Red-SSM-Strike', {
    targetlist = {'RP-Target-CV', 'RP-Target-DDGs'},
    isactive = false,
})

-- === BLUE: F-35C STRIKE MISSION ===
local mBlueStrike = ScenEdit_AddMission('Blue', 'Blue-F35C-Strike', 'strike', {subtype = 'land'})
ScenEdit_SetMission('Blue', 'Blue-F35C-Strike', {
    targetlist = {'RP-Strike-Bombers', 'RP-Missile-Bn'},
    flightsize = 2,
    minaircraftreq = 2,
    isactive = false,
})

-- === BLUE: F/A-18E CAP MISSION ===
local mBlueCAP = ScenEdit_AddMission('Blue', 'Blue-CAP', 'patrol', {type = 'air'})
ScenEdit_SetMission('Blue', 'Blue-CAP', {
    patrolzone = {'RP-BLUE-CV-DEF'},
    flightsize = 2,
    minaircraftreq = 2,
    isactive = true,
})

-- ============================================================
-- SECTION 8: Events
-- ============================================================

-- === EVENT 1: Scenario Load - Units Activate ===
local evLoad = ScenEdit_SetEvent('Init_UnitsActivate', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'ScenLoaded', name = 'OnLoad'})
ScenEdit_SetEventTrigger(evLoad.guid, {mode = 'add', name = 'OnLoad'})

local initScript = [[
ScenEdit_SpecialMessage('Red', '联合火力突击训练场景初始化完成，红方各平台就位')
ScenEdit_SpecialMessage('Blue', 'Joint Fire Strike scenario initialized - Blue side ready')
ScenEdit_SetKeyValue('scenario_phase', '0')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Init_Script', ScriptText = initScript})
ScenEdit_SetEventAction(evLoad.guid, {mode = 'add', name = 'Init_Script'})

-- === EVENT 2: T+30M - EW Aircraft Launch ===
local evEW = ScenEdit_SetEvent('T30M_EWAircraftLaunch', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+30M', time = T0 + 1800})
ScenEdit_SetEventTrigger(evEW.guid, {mode = 'add', name = 'T0+30M'})

local ewScript = [[
-- Activate EW jamming mission
ScenEdit_SetMission('Red', 'Red-EW-Jamming', {isactive = true})
-- Set J-16D units to active EMCON
for i = 1, 7 do
    local guid = ScenEdit_GetKeyValue('J16D_' .. i .. '_GUID')
    if guid and guid ~= '' then
        local ok = pcall(ScenEdit_SetEMCON, 'Unit', guid, 'Radar=Active;OECM=Active')
    end
end
ScenEdit_SpecialMessage('Red', '[T+30M] J-16D电子战飞机出动，建立电磁干扰阵位')
ScenEdit_SetKeyValue('scenario_phase', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'EW_Script', ScriptText = ewScript})
ScenEdit_SetEventAction(evEW.guid, {mode = 'add', name = 'EW_Script'})

-- === EVENT 3: T+60M - SSM Strike ===
local evSSM = ScenEdit_SetEvent('T60M_SSMStrike', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+60M', time = T0 + 3600})
ScenEdit_SetEventTrigger(evSSM.guid, {mode = 'add', name = 'T0+60M'})

local ssmScript = [[
-- Activate SSM strike mission
ScenEdit_SetMission('Red', 'Red-SSM-Strike', {isactive = true})
ScenEdit_SpecialMessage('Red', '[T+60M] DF-21C反舰弹道导弹开始预热，准备对蓝方航母编队实施打击')
ScenEdit_SetKeyValue('scenario_phase', '2')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'SSM_Script', ScriptText = ssmScript})
ScenEdit_SetEventAction(evSSM.guid, {mode = 'add', name = 'SSM_Script'})

-- === EVENT 4: T+75M - Air Strike Launch ===
local evAirStrike = ScenEdit_SetEvent('T75M_AirStrikeLaunch', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+75M', time = T0 + 4500})
ScenEdit_SetEventTrigger(evAirStrike.guid, {mode = 'add', name = 'T0+75M'})

local airScript = [[
-- Activate bomber and J-16 strike missions
ScenEdit_SetMission('Red', 'Red-Bomber-Strike', {isactive = true})
ScenEdit_SetMission('Red', 'Red-J16-Strike', {isactive = true})
ScenEdit_SpecialMessage('Red', '[T+75M] H-6K轰炸机群与J-16战斗机联合出动，实施反舰饱和打击')
ScenEdit_SpecialMessage('Blue', '[ALERT] Red air strike inbound - multiple tracks detected')
ScenEdit_SetKeyValue('scenario_phase', '3')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'AirStrike_Script', ScriptText = airScript})
ScenEdit_SetEventAction(evAirStrike.guid, {mode = 'add', name = 'AirStrike_Script'})

-- === EVENT 5: T+90M - Blue Counterstrike ===
local evBlueCounter = ScenEdit_SetEvent('T90M_BlueCounterstrike', {
    mode = 'add', IsRepeatable = false, IsActive = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+90M', time = T0 + 5400})
ScenEdit_SetEventTrigger(evBlueCounter.guid, {mode = 'add', name = 'T0+90M'})

local blueScript = [[
-- Blue F-35C strike against red bombers and missile positions
ScenEdit_SetMission('Blue', 'Blue-F35C-Strike', {isactive = true})
ScenEdit_SpecialMessage('Blue', '[T+90M] F-35C编队出动，对红方轰炸机和导弹阵地实施反击')
ScenEdit_SetKeyValue('scenario_phase', '4')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'BlueCounter_Script', ScriptText = blueScript})
ScenEdit_SetEventAction(evBlueCounter.guid, {mode = 'add', name = 'BlueCounter_Script'})

-- ============================================================
-- SECTION 9: EMCON Control
-- ============================================================

-- Red ships: Active radar for area denial
local dd055g = ScenEdit_GetKeyValue('DD055_1_GUID')
if dd055g and dd055g ~= '' then
    ScenEdit_SetEMCON('Unit', dd055g, 'Radar=Active;Sonar=Active;OECM=Active')
end
for i = 1, 3 do
    local g = ScenEdit_GetKeyValue('DD052D_' .. i .. '_GUID')
    if g and g ~= '' then
        pcall(ScenEdit_SetEMCON, 'Unit', g, 'Radar=Active;Sonar=Active')
    end
end
for i = 1, 2 do
    local g = ScenEdit_GetKeyValue('SUB039C_' .. i .. '_GUID')
    if g and g ~= '' then
        pcall(ScenEdit_SetEMCON, 'Unit', g, 'Sonar=Passive')
    end
end

-- Blue ships: Defensive posture
local cvng = ScenEdit_GetKeyValue('CVN_LINCOLN_GUID')
if cvng and cvng ~= '' then
    ScenEdit_SetEMCON('Unit', cvng, 'Radar=Active')
end
local cg = ScenEdit_GetKeyValue('CG_TICO_GUID')
if cg and cg ~= '' then
    ScenEdit_SetEMCON('Unit', cg, 'Radar=Active;Sonar=Active;OECM=Active')
end
for i = 1, 4 do
    local g = ScenEdit_GetKeyValue('DDG_B_' .. i .. '_GUID')
    if g and g ~= '' then
        pcall(ScenEdit_SetEMCON, 'Unit', g, 'Radar=Active;Sonar=Active;OECM=Active')
    end
end

-- ============================================================
-- SECTION 10: Summary
-- ============================================================
print('============================================')
print('A1场景 - Joint Fire Strike Exercise Setup')
print('============================================')
print('RED SIDE:')
print('  DF-26B SSM:      5 units (DBID=89 DF-21C)')
print('  J-16D EW:        7 units (DBID=4632 Loadout=753)')
print('  H-6K Bomber:     8 units (DBID=1731 Loadout=863)')
print('  KJ-500 AWACS:     2 units (DBID=3683 Loadout=494)')
print('  J-20A Fighter:   8 units (DBID=5012 Loadout=1191)')
print('  J-16 Fighter:   11 units (DBID=2853 Loadout=1821)')
print('  Type 052D:       3 units (DBID=2296)')
print('  Type 054A:       4 units (DBID=1965)')
print('  Type 055:        1 unit  (DBID=2834)')
print('  Type 039C Sub:   2 units (DBID=695)')
print('BLUE SIDE:')
print('  CVN Carl Vinson: 1 unit  (DBID=246)')
print('  CG Ticonderoga:  1 unit  (DBID=40)')
print('  DDG Arleigh Burke: 4 units (DBID=111/112)')
print('  LHA America:      1 unit  (DBID=2362)')
print('  AOE Supply:       1 unit  (DBID=490)')
print('  AGOS Victorious:  3 units (DBID=365)')
print('  F-35C Lightning:  3 units (DBID=824 Loadout=689)')
print('  F-35B Lightning:  5 units (DBID=534/4697)')
print('  F/A-18E Hornet:   4 units (DBID=342 Loadout=1561)')
print('  F/A-18F Hornet:   2 units (DBID=443 Loadout=367)')
print('SKIPPED (MCP not found):')
print('  SAT_JIANBING23 - Satellite Jianbing-23')
print('  USV_OVERLORD - Overlord USV')
print('  UAV_YILONG2D - Yilong-2D UAV')
print('  UUV_RED - UUV Red')
print('  GND_TYPHON_LAUNCHER - Typhoon SAM')
print('============================================')
ScenEdit_SpecialMessage('Red', '联合火力突击训练场景 - 初始化完成')
