-- ============================================================
-- 多轴饱和攻击方案 (Multi-Axis Saturation Attack Plan)
-- Plan ID: MASA001
-- Generated by CMO Lua SKILL
-- Red side: RedForce (China)
-- Blue side: BlueForce (US)
-- T0 = scenario start time
-- ============================================================

-- ============================================================
-- SECTION 1: Constants — DBIDs confirmed via MCP queries
-- ============================================================
local DBID = {
    DDG_055      = 2834,  -- Type 055 Renhai [101 Nanchang] — China, Ship
    DDG_BURKE    = 294,   -- DDG 79 Oscar Austin [Arleigh Burke Flight IIA] — US, Ship
    T_AO_KAISER  = 26,    -- T-AO 187 Henry J. Kaiser [Mod Cimarron] — US, Ship
    SUB_039C     = 695,   -- Type 039C Yuan — China, Submarine
    J16          = 2853,  -- J-16 Flying Shark — China, Aircraft
    J16D         = 4632,  -- J-16D Roaring Wolf — China, Aircraft
}

local LOADOUT = {
    J16_ASM      = 1821,  -- J-16 anti-ship loadout (confirmed via MCP: YJ-12 x2 + RAE)
    J16D_EW      = 753,   -- J-16D EW loadout
}

local WEAPON = {
    YJ12         = 2862,  -- YJ-12 (air-launched ASM)
    YJ18         = 2867,  -- YJ-18 [3M54E Klub Copy, Rocket Boosted Penetrator] (ship-launched)
    YJ83         = 541,   -- YJ-83 [C-802A] (submarine torpedo-tube launched)
}

local SIDE = {
    RED  = "RedForce",
    BLUE = "BlueForce",
}

-- ============================================================
-- SECTION 2: Helper — safe side creation (idempotent)
-- ============================================================
local function addSideSafe(name)
    local ok, result = pcall(ScenEdit_AddSide, {name = name})
    if not ok then
        print("[WARN] addSide(" .. name .. "): " .. tostring(result))
    end
end

local function setPostureSafe(sideA, sideB, posture)
    local ok, err = pcall(ScenEdit_SetSidePosture, sideA, sideB, posture)
    if not ok then
        print("[WARN] setPosture(" .. sideA .. "," .. sideB .. "," .. posture .. "): " .. tostring(err))
    end
end

-- ============================================================
-- SECTION 3: Create sides and set postures
-- ============================================================
print("[PHASE 1] Creating sides...")

addSideSafe(SIDE.RED)
addSideSafe(SIDE.BLUE)

setPostureSafe(SIDE.RED,  SIDE.BLUE, "H")  -- Red hostile to Blue
setPostureSafe(SIDE.BLUE, SIDE.RED,  "H")  -- Blue hostile to Red

print("[PHASE 1] Sides created: RedForce (H to BlueForce) / BlueForce (H to RedForce)")

-- ============================================================
-- SECTION 4: Create Red Force units
-- ============================================================
print("[PHASE 2] Creating Red Force units...")

-- 4.1 055 Renhai Destroyer #1
local ddg055_1 = ScenEdit_AddUnit({
    side       = SIDE.RED,
    type       = "Ship",
    name       = "055-DDG-1 [Nanchang]",
    dbid       = DBID.DDG_055,
    latitude   = 30.166666666666668,
    longitude  = 123.5,
    altitude   = 0,
    heading    = 90,
    speed      = 20,
    proficiency = "Veteran",
})
if ddg055_1 then
    ScenEdit_SetKeyValue("DDG055_1_GUID", ddg055_1.guid)
    print("  + 055-DD-1 [Nanchang] spawned, guid=" .. ddg055_1.guid)
else
    print("  [ERROR] Failed to spawn 055-DD-1 [Nanchang]")
end

-- 4.2 055 Renhai Destroyer #2
local ddg055_2 = ScenEdit_AddUnit({
    side       = SIDE.RED,
    type       = "Ship",
    name       = "055-DD-2",
    dbid       = DBID.DDG_055,
    latitude   = 29.833333333333332,
    longitude  = 123.83333333333333,
    altitude   = 0,
    heading    = 90,
    speed      = 20,
    proficiency = "Veteran",
})
if ddg055_2 then
    ScenEdit_SetKeyValue("DDG055_2_GUID", ddg055_2.guid)
    print("  + 055-DD-2 spawned, guid=" .. ddg055_2.guid)
else
    print("  [ERROR] Failed to spawn 055-DD-2")
end

-- 4.3 Type 039C Yuan Submarine (depth = 60 m)
local sub039c = ScenEdit_AddUnit({
    side             = SIDE.RED,
    type             = "Submarine",
    name             = "039C-SUB-1",
    dbid             = DBID.SUB_039C,
    latitude         = 30.5,
    longitude        = 126.16666666666667,
    altitude         = 60,     -- submerged depth 60 m (positive = below surface)
    heading          = 135,
    speed            = 8,
    proficiency      = "Veteran",
})
if sub039c then
    ScenEdit_SetKeyValue("SUB039C_1_GUID", sub039c.guid)
    print("  + 039C-SUB-1 spawned, guid=" .. sub039c.guid)
else
    print("  [ERROR] Failed to spawn 039C-SUB-1")
end

-- 4.4 J-16 #1 (anti-ship loadout)
local j16_1 = ScenEdit_AddUnit({
    side       = SIDE.RED,
    type       = "Aircraft",
    name       = "J16-1",
    dbid       = DBID.J16,
    LoadoutID  = LOADOUT.J16_ASM,
    latitude   = 30.0,
    longitude  = 122.0,
    altitude   = 7620,
    heading    = 90,
    speed      = 250,
    proficiency = "Veteran",
})
if j16_1 then
    ScenEdit_SetKeyValue("J16_1_GUID", j16_1.guid)
    print("  + J16-1 spawned, guid=" .. j16_1.guid)
else
    print("  [ERROR] Failed to spawn J16-1")
end

-- 4.5 J-16 #2
local j16_2 = ScenEdit_AddUnit({
    side       = SIDE.RED,
    type       = "Aircraft",
    name       = "J16-2",
    dbid       = DBID.J16,
    LoadoutID  = LOADOUT.J16_ASM,
    latitude   = 30.083333333333332,
    longitude  = 122.16666666666667,
    altitude   = 7620,
    heading    = 90,
    speed      = 250,
    proficiency = "Veteran",
})
if j16_2 then
    ScenEdit_SetKeyValue("J16_2_GUID", j16_2.guid)
    print("  + J16-2 spawned, guid=" .. j16_2.guid)
else
    print("  [ERROR] Failed to spawn J16-2")
end

-- 4.6 J-16 #3
local j16_3 = ScenEdit_AddUnit({
    side       = SIDE.RED,
    type       = "Aircraft",
    name       = "J16-3",
    dbid       = DBID.J16,
    LoadoutID  = LOADOUT.J16_ASM,
    latitude   = 29.916666666666668,
    longitude  = 122.08333333333333,
    altitude   = 7315,
    heading    = 0,
    speed      = 250,
    proficiency = "Veteran",
})
if j16_3 then
    ScenEdit_SetKeyValue("J16_3_GUID", j16_3.guid)
    print("  + J16-3 spawned, guid=" .. j16_3.guid)
else
    print("  [ERROR] Failed to spawn J16-3")
end

-- 4.7 J-16 #4
local j16_4 = ScenEdit_AddUnit({
    side       = SIDE.RED,
    type       = "Aircraft",
    name       = "J16-4",
    dbid       = DBID.J16,
    LoadoutID  = LOADOUT.J16_ASM,
    latitude   = 30.033333333333335,
    longitude  = 122.25,
    altitude   = 7315,
    heading    = 90,
    speed      = 250,
    proficiency = "Veteran",
})
if j16_4 then
    ScenEdit_SetKeyValue("J16_4_GUID", j16_4.guid)
    print("  + J16-4 spawned, guid=" .. j16_4.guid)
else
    print("  [ERROR] Failed to spawn J16-4")
end

-- 4.8 J-16D #1 (electronic warfare)
local j16d_1 = ScenEdit_AddUnit({
    side       = SIDE.RED,
    type       = "Aircraft",
    name       = "J16D-1",
    dbid       = DBID.J16D,
    LoadoutID  = LOADOUT.J16D_EW,
    latitude   = 30.133333333333333,
    longitude  = 123.0,
    altitude   = 8534,
    heading    = 90,
    speed      = 250,
    proficiency = "Veteran",
})
if j16d_1 then
    ScenEdit_SetKeyValue("J16D_1_GUID", j16d_1.guid)
    print("  + J16D-1 spawned, guid=" .. j16d_1.guid)
else
    print("  [ERROR] Failed to spawn J16D-1")
end

print("[PHASE 2] Red Force units spawned: 2x055, 1x039C, 4xJ-16, 1xJ-16D")

-- ============================================================
-- SECTION 5: Create Blue Force target units
-- ============================================================
print("[PHASE 3] Creating Blue Force target units...")

-- 5.1 Arleigh Burke Flight IIA Destroyer #1
local blue_ddg1 = ScenEdit_AddUnit({
    side       = SIDE.BLUE,
    type       = "Ship",
    name       = "蓝方伯克舰1",
    dbid       = DBID.DDG_BURKE,
    latitude   = 30.333333333333332,
    longitude  = 127.5,
    altitude   = 0,
    heading    = 0,
    speed      = 0,
    proficiency = "Regular",
})
if blue_ddg1 then
    ScenEdit_SetKeyValue("BLUE_DDG1_GUID", blue_ddg1.guid)
    print("  + 蓝方伯克舰1 spawned, guid=" .. blue_ddg1.guid)
end

-- 5.2 Arleigh Burke Flight IIA Destroyer #2
local blue_ddg2 = ScenEdit_AddUnit({
    side       = SIDE.BLUE,
    type       = "Ship",
    name       = "蓝方伯克舰2",
    dbid       = DBID.DDG_BURKE,
    latitude   = 30.0,
    longitude  = 127.75,
    altitude   = 0,
    heading    = 0,
    speed      = 0,
    proficiency = "Regular",
})
if blue_ddg2 then
    ScenEdit_SetKeyValue("BLUE_DDG2_GUID", blue_ddg2.guid)
    print("  + 蓝方伯克舰2 spawned, guid=" .. blue_ddg2.guid)
end

-- 5.3 T-AO Henry J. Kaiser Fleet Tanker / Supply Ship
local blue_ao = ScenEdit_AddUnit({
    side       = SIDE.BLUE,
    type       = "Ship",
    name       = "蓝方补给舰",
    dbid       = DBID.T_AO_KAISER,
    latitude   = 30.166666666666668,
    longitude  = 127.25,
    altitude   = 0,
    heading    = 0,
    speed      = 0,
    proficiency = "Regular",
})
if blue_ao then
    ScenEdit_SetKeyValue("BLUE_AO_GUID", blue_ao.guid)
    print("  + 蓝方补给舰 spawned, guid=" .. blue_ao.guid)
end

print("[PHASE 3] Blue Force targets spawned: 2xArleigh Burke DDG, 1xT-AO Kaiser")

-- ============================================================
-- SECTION 6: Reference points — J-16D EW patrol zone
-- ============================================================
print("[PHASE 4] Creating EW patrol zone reference points...")

local EW_RP_NAMES = {}
local ewRPs = {
    {"EW-RP-N",  30.250, 124.000},
    {"EW-RP-E",  30.200, 125.500},
    {"EW-RP-S",  30.100, 124.500},
    {"EW-RP-W",  30.150, 123.500},
}
for i, rp in ipairs(ewRPs) do
    local rpName = rp[1]
    local rpLat  = rp[2]
    local rpLon  = rp[3]
    ScenEdit_AddReferencePoint({
        side       = SIDE.RED,
        name       = rpName,
        latitude   = rpLat,
        longitude  = rpLon,
        highlighted = false,
    })
    EW_RP_NAMES[i] = rpName
    print("  + RP " .. rpName .. " (" .. rpLat .. "," .. rpLon .. ")")
end

-- Target reference points (attack zones)
local TARGET_RP_NAMES = {}
local targetRPs = {
    {"TGT-RP-BDG1", 30.333, 127.500},
    {"TGT-RP-BDG2", 30.000, 127.750},
    {"TGT-RP-AO",   30.167, 127.250},
}
for i, rp in ipairs(targetRPs) do
    ScenEdit_AddReferencePoint({
        side       = SIDE.RED,
        name       = rp[1],
        latitude   = rp[2],
        longitude  = rp[3],
        highlighted = true,
    })
    TARGET_RP_NAMES[i] = rp[1]
    print("  + Target RP " .. rp[1])
end

print("[PHASE 4] Reference points created")

-- ============================================================
-- SECTION 7: Doctrine settings for Red Force
-- ============================================================
print("[PHASE 5] Setting Red Force doctrine...")

ScenEdit_SetDoctrine({side = SIDE.RED}, {
    weapon_control_status_air        = 0,   -- Free
    weapon_control_status_surface    = 0,   -- Free
    weapon_control_status_subsurface  = 0,   -- Free
    ignore_plotted_course           = "no",
    use_nuclear_weapons             = "no",
    engage_ambiguous_targets        = "optimistic",
    engage_non_hostile_targets      = "no",
})

-- J-16D EW suppression doctrine: passive sensors first
if j16d_1 then
    ScenEdit_SetEMCON("Unit", j16d_1.guid, "Radar=Passive;OECM=Active")
    print("  J16D-1 EMCON: Radar=Passive; OECM=Active")
end

-- 055 DDGs: passive until attack phase
if ddg055_1 then
    ScenEdit_SetEMCON("Unit", ddg055_1.guid, "Radar=Passive;Sonar=Passive;OECM=Passive")
end
if ddg055_2 then
    ScenEdit_SetEMCON("Unit", ddg055_2.guid, "Radar=Passive;Sonar=Passive;OECM=Passive")
end

print("[PHASE 5] Doctrine configured")

-- ============================================================
-- SECTION 8: Missions
-- ============================================================
print("[PHASE 6] Creating missions...")

-- 8.1 J-16D EW patrol mission
local ewMission = ScenEdit_AddMission(SIDE.RED, "EW-Patrol", "Patrol", {
    type = "SEA",
})
if ewMission then
    ScenEdit_SetMission(SIDE.RED, "EW-Patrol", {
        patrolzone  = EW_RP_NAMES,
        onethirdrule = false,
    })
    print("  + EW-Patrol mission created (SEA patrol)")
end

-- 8.2 J-16 #1 maritime strike
local mJ16_1 = ScenEdit_AddMission(SIDE.RED, "Strike-J16-1", "Strike", {
    type = "SEA",
})
if mJ16_1 then
    ScenEdit_SetMission(SIDE.RED, "Strike-J16-1", {attackee = SIDE.BLUE})
    print("  + Strike-J16-1 mission created")
end

-- 8.3 J-16 #2 maritime strike
local mJ16_2 = ScenEdit_AddMission(SIDE.RED, "Strike-J16-2", "Strike", {
    type = "SEA",
})
if mJ16_2 then
    ScenEdit_SetMission(SIDE.RED, "Strike-J16-2", {attackee = SIDE.BLUE})
    print("  + Strike-J16-2 mission created")
end

-- 8.4 J-16 #3 maritime strike
local mJ16_3 = ScenEdit_AddMission(SIDE.RED, "Strike-J16-3", "Strike", {
    type = "SEA",
})
if mJ16_3 then
    ScenEdit_SetMission(SIDE.RED, "Strike-J16-3", {attackee = SIDE.BLUE})
    print("  + Strike-J16-3 mission created")
end

-- 8.5 J-16 #4 maritime strike
local mJ16_4 = ScenEdit_AddMission(SIDE.RED, "Strike-J16-4", "Strike", {
    type = "SEA",
})
if mJ16_4 then
    ScenEdit_SetMission(SIDE.RED, "Strike-J16-4", {attackee = SIDE.BLUE})
    print("  + Strike-J16-4 mission created")
end

-- 8.6 055-DD-1 surface strike
local mDDG1 = ScenEdit_AddMission(SIDE.RED, "Strike-DDG-1", "Strike", {
    type = "SEA",
})
if mDDG1 then
    ScenEdit_SetMission(SIDE.RED, "Strike-DDG-1", {attackee = SIDE.BLUE})
    print("  + Strike-DDG-1 mission created")
end

-- 8.7 055-DD-2 surface strike
local mDDG2 = ScenEdit_AddMission(SIDE.RED, "Strike-DDG-2", "Strike", {
    type = "SEA",
})
if mDDG2 then
    ScenEdit_SetMission(SIDE.RED, "Strike-DDG-2", {attackee = SIDE.BLUE})
    print("  + Strike-DDG-2 mission created")
end

-- 8.8 039C submarine strike
local mSUB = ScenEdit_AddMission(SIDE.RED, "Strike-SUB", "Strike", {
    type = "SEA",
})
if mSUB then
    ScenEdit_SetMission(SIDE.RED, "Strike-SUB", {attackee = SIDE.BLUE})
    print("  + Strike-SUB mission created")
end

print("[PHASE 6] All missions created")

-- ============================================================
-- SECTION 9: Assign units to missions
-- ============================================================
print("[PHASE 7] Assigning units to missions...")

if j16d_1  then ScenEdit_AssignUnitToMission(j16d_1.guid,  "EW-Patrol")      end
if j16_1   then ScenEdit_AssignUnitToMission(j16_1.guid,   "Strike-J16-1")   end
if j16_2   then ScenEdit_AssignUnitToMission(j16_2.guid,   "Strike-J16-2")   end
if j16_3   then ScenEdit_AssignUnitToMission(j16_3.guid,   "Strike-J16-3")   end
if j16_4   then ScenEdit_AssignUnitToMission(j16_4.guid,   "Strike-J16-4")   end
if ddg055_1 then ScenEdit_AssignUnitToMission(ddg055_1.guid, "Strike-DDG-1") end
if ddg055_2 then ScenEdit_AssignUnitToMission(ddg055_2.guid, "Strike-DDG-2") end
if sub039c  then ScenEdit_AssignUnitToMission(sub039c.guid,  "Strike-SUB")    end

print("[PHASE 7] Units assigned to missions")

-- ============================================================
-- SECTION 10: Special Actions — manual weapon control
-- ============================================================
print("[PHASE 8] Creating special actions for manual control...")

local function addManualStrike(saId, desc, attackerName, targetName, wpnDbId)
    local script = string.format([[
local attacker = ScenEdit_GetUnit({name='%s'})
local target   = ScenEdit_GetUnit({name='%s'})
if not attacker then
    print('[ERROR] Attacker %s not found')
    return
end
if not target then
    print('[ERROR] Target %s not found')
    return
end
print('[STRIKE] ' .. attacker.name .. ' launching weapon (dbid=%d) at ' .. target.name)
local ok, err = pcall(ScenEdit_AttackContact, attacker.guid, target.guid, {weapon_dbid=%d})
if not ok then
    print('[ERROR] ' .. tostring(err))
end
]], attackerName, targetName, attackerName, targetName, wpnDbId, wpnDbId)

    ScenEdit_AddSpecialAction({
        Side = SIDE.RED,
        ActionNameOrID = saId,
        description = desc,
        IsActive   = true,
        IsRepeatable = true,
        ScriptText = script,
    })
    print("  + Special action: " .. desc)
end

-- DDG1 → 蓝方伯克舰1 (YJ-18 shipborne)
addManualStrike("sa_ddg1_atk_bdg1",
    "手动发射 | 055-DD-1 → 蓝方伯克舰1 (YJ-18)",
    "055-DD-1 [Nanchang]", "蓝方伯克舰1", WEAPON.YJ18)

-- DDG1 → 蓝方伯克舰2
addManualStrike("sa_ddg1_atk_bdg2",
    "手动发射 | 055-DD-1 → 蓝方伯克舰2 (YJ-18)",
    "055-DD-1 [Nanchang]", "蓝方伯克舰2", WEAPON.YJ18)

-- DDG2 → 蓝方伯克舰1
addManualStrike("sa_ddg2_atk_bdg1",
    "手动发射 | 055-DD-2 → 蓝方伯克舰1 (YJ-18)",
    "055-DD-2", "蓝方伯克舰1", WEAPON.YJ18)

-- DDG2 → 蓝方伯克舰2
addManualStrike("sa_ddg2_atk_bdg2",
    "手动发射 | 055-DD-2 → 蓝方伯克舰2 (YJ-18)",
    "055-DD-2", "蓝方伯克舰2", WEAPON.YJ18)

-- DDG → 补给舰
addManualStrike("sa_ddg_atk_ao",
    "手动发射 | 055-DD → 蓝方补给舰 (YJ-18)",
    "055-DD-1 [Nanchang]", "蓝方补给舰", WEAPON.YJ18)

-- J16-3 → 补给舰 (YJ-12 air-launched)
addManualStrike("sa_j16_atk_ao",
    "手动发射 | J16-3 → 蓝方补给舰 (YJ-12)",
    "J16-3", "蓝方补给舰", WEAPON.YJ12)

-- SUB → 补给舰 (YJ-83 torpedo-tube)
addManualStrike("sa_sub_atk_ao",
    "手动发射 | 039C-SUB-1 → 蓝方补给舰 (YJ-83)",
    "039C-SUB-1", "蓝方补给舰", WEAPON.YJ83)

print("[PHASE 8] Special actions created")

-- ============================================================
-- SECTION 11: Time-scheduled events (TCA pattern)
-- T0 = scenario start
-- Phase 1:  T0+0M   — Force assembly and transit
-- Phase 2:  T0+30M  — EW suppression & target confirmation
-- Phase 3:  T0+40M  — Multi-axis saturation attack (weapon launch)
-- Phase 4:  T0+60M  — Battle damage assessment
-- ============================================================
print("[PHASE 9] Creating time-scheduled events...")

local LfCR = "\r\n"

-- === Event: Phase 1 — Force Assembly (T0 + 0 min) ===
local ev1 = ScenEdit_SetEvent("Ev_Phase1_Assembly", {
    mode = "add",
    IsActive   = true,
    IsRepeatable = 0,
    IsShown    = true,
    Probability = 100,
})
ScenEdit_SetTrigger({mode = "add", type = "Time", name = "Trig_Phase1", Time = "0"})
ScenEdit_SetEventTrigger("Ev_Phase1_Assembly", {mode = "add", name = "Trig_Phase1"})
ScenEdit_SetAction({mode = "add", type = "LuaScript", name = "Act_Phase1", scriptText =
    "print('[PHASE 1] All Red platforms: transit to designated attack positions')" .. LfCR ..
    "ScenEdit_SpecialMessage(SIDE.RED, '[阶段1] 兵力向预定阵位机动集结')"
})
ScenEdit_SetEventAction("Ev_Phase1_Assembly", {mode = "add", name = "Act_Phase1"})
print("  + Ev_Phase1_Assembly (T+0M)")

-- === Event: Phase 2 — EW Suppression (T0 + 30 min) ===
local ev2 = ScenEdit_SetEvent("Ev_Phase2_EWSuppression", {
    mode = "add",
    IsActive   = true,
    IsRepeatable = 0,
    IsShown    = true,
    Probability = 100,
})
ScenEdit_SetTrigger({mode = "add", type = "Time", name = "Trig_Phase2", Time = "30"})
ScenEdit_SetEventTrigger("Ev_Phase2_EWSuppression", {mode = "add", name = "Trig_Phase2"})
ScenEdit_SetAction({mode = "add", type = "LuaScript", name = "Act_Phase2", scriptText =
    "print('[PHASE 2] J-16D: commencing EW suppression patrol')" .. LfCR ..
    "ScenEdit_SpecialMessage(SIDE.RED, '[阶段2] J-16D开始电磁侦察压制，所有平台确认目标位置')"
})
ScenEdit_SetEventAction("Ev_Phase2_EWSuppression", {mode = "add", name = "Act_Phase2"})
print("  + Ev_Phase2_EWSuppression (T+30M)")

-- === Event: Phase 3 — Saturation Attack (T0 + 40 min) ===
local ev3 = ScenEdit_SetEvent("Ev_Phase3_SaturationAttack", {
    mode = "add",
    IsActive   = true,
    IsRepeatable = 0,
    IsShown    = true,
    Probability = 100,
})
ScenEdit_SetTrigger({mode = "add", type = "Time", name = "Trig_Phase3", Time = "40"})
ScenEdit_SetEventTrigger("Ev_Phase3_SaturationAttack", {mode = "add", name = "Trig_Phase3"})
ScenEdit_SetAction({mode = "add", type = "LuaScript", name = "Act_Phase3", scriptText =
    "print('[PHASE 3] SATURATION ATTACK — All platforms launching missiles')" .. LfCR ..
    LfCR ..
    "-- J-16 aircraft: YJ-12 (dbid=2862)" .. LfCR ..
    "local t1 = ScenEdit_GetUnit({name='蓝方伯克舰1'})" .. LfCR ..
    "local t2 = ScenEdit_GetUnit({name='蓝方伯克舰2'})" .. LfCR ..
    "local t3 = ScenEdit_GetUnit({name='蓝方补给舰'})" .. LfCR ..
    LfCR ..
    "local function fire(unitName, target, wpnDbId)" .. LfCR ..
    "  if not target then return end" .. LfCR ..
    "  local u = ScenEdit_GetUnit({name=unitName})" .. LfCR ..
    "  if u then" .. LfCR ..
    "    pcall(ScenEdit_AttackContact, u.guid, target.guid, {weapon_dbid=wpnDbId})" .. LfCR ..
    "  end" .. LfCR ..
    "end" .. LfCR ..
    LfCR ..
    "-- Saturation fire from multiple axes" .. LfCR ..
    "-- Axis 1: J16-1 → Burke 1 (YJ-12)" .. LfCR ..
    "fire('J16-1', t1, 2862)" .. LfCR ..
    "-- Axis 2: J16-2 → Burke 2 (YJ-12)" .. LfCR ..
    "fire('J16-2', t2, 2862)" .. LfCR ..
    "-- Axis 3: J16-3 + J16-4 → Supply (YJ-12)" .. LfCR ..
    "fire('J16-3', t3, 2862)" .. LfCR ..
    "fire('J16-4', t3, 2862)" .. LfCR ..
    "-- Axis 4: 055-DD-1 → Burke 1, 2, AO (YJ-18 dbid=2867)" .. LfCR ..
    "fire('055-DD-1 [Nanchang]', t1, 2867)" .. LfCR ..
    "fire('055-DD-1 [Nanchang]', t2, 2867)" .. LfCR ..
    "fire('055-DD-1 [Nanchang]', t3, 2867)" .. LfCR ..
    "-- Axis 5: 055-DD-2 → all targets (YJ-18)" .. LfCR ..
    "fire('055-DD-2', t1, 2867)" .. LfCR ..
    "fire('055-DD-2', t2, 2867)" .. LfCR ..
    "fire('055-DD-2', t3, 2867)" .. LfCR ..
    "-- Axis 6: 039C-SUB-1 → Supply (YJ-83 dbid=541)" .. LfCR ..
    "fire('039C-SUB-1', t3, 541)" .. LfCR ..
    LfCR ..
    "ScenEdit_SpecialMessage(SIDE.RED, '[阶段3] 多轴饱和攻击 — 反舰导弹齐射！')"
})
ScenEdit_SetEventAction("Ev_Phase3_SaturationAttack", {mode = "add", name = "Act_Phase3"})
print("  + Ev_Phase3_SaturationAttack (T+40M)")

-- === Event: Phase 4 — Battle Damage Assessment (T0 + 60 min) ===
local ev4 = ScenEdit_SetEvent("Ev_Phase4_BDA", {
    mode = "add",
    IsActive   = true,
    IsRepeatable = 0,
    IsShown    = true,
    Probability = 100,
})
ScenEdit_SetTrigger({mode = "add", type = "Time", name = "Trig_Phase4", Time = "60"})
ScenEdit_SetEventTrigger("Ev_Phase4_BDA", {mode = "add", name = "Trig_Phase4"})
ScenEdit_SetAction({mode = "add", type = "LuaScript", name = "Act_Phase4", scriptText =
    "print('[PHASE 4] Battle Damage Assessment')" .. LfCR ..
    "local targets = {'蓝方伯克舰1', '蓝方伯克舰2', '蓝方补给舰'}" .. LfCR ..
    "local destroyed = 0" .. LfCR ..
    "for _, n in ipairs(targets) do" .. LfCR ..
    "  local u = ScenEdit_GetUnit({name=n})" .. LfCR ..
    "  if not u then" .. LfCR ..
    "    print('  [BDA] ' .. n .. ' — DESTROYED')" .. LfCR ..
    "    destroyed = destroyed + 1" .. LfCR ..
    "  else" .. LfCR ..
    "    print('  [BDA] ' .. n .. ' — surviving, damage=' .. tostring(u.damage))" .. LfCR ..
    "  end" .. LfCR ..
    "end" .. LfCR ..
    "local msg = string.format('[阶段4] BDA: %d/3 targets destroyed', destroyed)" .. LfCR ..
    "ScenEdit_SpecialMessage(SIDE.RED, msg)" .. LfCR ..
    "if destroyed >= 2 then" .. LfCR ..
    "  ScenEdit_SetScore(SIDE.RED, 500, 'Mission Success: Blue force attritted')" .. LfCR ..
    "  ScenEdit_SpecialMessage(SIDE.RED, '【作战成功】摧毁' .. destroyed .. '个目标')" .. LfCR ..
    "elseif destroyed > 0 then" .. LfCR ..
    "  ScenEdit_SpecialMessage(SIDE.RED, '【部分达成】摧毁' .. destroyed .. '个目标，继续监控')" .. LfCR ..
    "else" .. LfCR ..
    "  ScenEdit_SpecialMessage(SIDE.RED, '【未达成】目标仍存活，考虑补充打击')" .. LfCR ..
    "end"
})
ScenEdit_SetEventAction("Ev_Phase4_BDA", {mode = "add", name = "Act_Phase4"})
print("  + Ev_Phase4_BDA (T+60M)")

print("[PHASE 9] Time-scheduled events created")

-- ============================================================
-- SECTION 12: Target designation for strike missions
-- ============================================================
print("[PHASE 10] Assigning targets to strike missions...")

-- KC001 kill chain: 蓝方伯克舰1 targeted by J16-1 + 055-DD-1
ScenEdit_AssignUnitAsTarget({mission = "Strike-J16-1", unitname = "蓝方伯克舰1"})
ScenEdit_AssignUnitAsTarget({mission = "Strike-DDG-1", unitname = "蓝方伯克舰1"})

-- KC002 kill chain: 蓝方伯克舰2 targeted by J16-2 + 055-DD-2
ScenEdit_AssignUnitAsTarget({mission = "Strike-J16-2", unitname = "蓝方伯克舰2"})
ScenEdit_AssignUnitAsTarget({mission = "Strike-DDG-2", unitname = "蓝方伯克舰2"})

-- KC003 kill chain: 蓝方补给舰 targeted by J16-3, J16-4, 039C-SUB-1, both 055
ScenEdit_AssignUnitAsTarget({mission = "Strike-J16-3", unitname = "蓝方补给舰"})
ScenEdit_AssignUnitAsTarget({mission = "Strike-J16-4", unitname = "蓝方补给舰"})
ScenEdit_AssignUnitAsTarget({mission = "Strike-DDG-1", unitname = "蓝方补给舰"})
ScenEdit_AssignUnitAsTarget({mission = "Strike-DDG-2", unitname = "蓝方补给舰"})
ScenEdit_AssignUnitAsTarget({mission = "Strike-SUB",   unitname = "蓝方补给舰"})

-- All strikes also target both Burke DDGs
ScenEdit_AssignUnitAsTarget({mission = "Strike-DDG-1", unitname = "蓝方伯克舰2"})
ScenEdit_AssignUnitAsTarget({mission = "Strike-DDG-2", unitname = "蓝方伯克舰1"})

print("[PHASE 10] Targets assigned to strike missions")

-- ============================================================
-- SECTION 13: Operational summary
-- ============================================================
print("========================================")
print(" 多轴饱和攻击方案 — 加载完成 (MASA001)")
print("========================================")
print("")
print("作战时间轴 (UTC):")
print("  T+0M   : 阶段1 - 兵力机动集结")
print("  T+30M  : 阶段2 - J-16D电磁压制与目标确认")
print("  T+40M  : 阶段3 - 多轴饱和攻击（导弹齐射）")
print("  T+60M  : 阶段4 - 打击效果评估与兵力撤收")
print("")
print("红方参战平台:")
print("  水面: 055-DD-1 [Nanchang] (YJ-18 x8)")
print("        055-DD-2              (YJ-18 x8)")
print("  航空: J16-1, J16-2, J16-3, J16-4 (各YJ-12 x2)")
print("        J16D-1 (电子战/压制)")
print("  水下: 039C-SUB-1 (YJ-83 x4)")
print("")
print("蓝方目标:")
print("  蓝方伯克舰1 (DDG-79 Oscar Austin)")
print("  蓝方伯克舰2 (DDG-79 Oscar Austin)")
print("  蓝方补给舰 (T-AO 187 Henry J. Kaiser)")
print("")
print("武器 DBID (via MCP):")
print("  YJ-12 = 2862 (空射)")
print("  YJ-18 = 2867 (舰射, 冲压穿甲)")
print("  YJ-83 = 541  (潜射, 533mm鱼雷管)")
print("")
print("特殊动作 (Special Actions):")
print("  [手动发射 | 055-DD-1 → 蓝方伯克舰1 (YJ-18)]")
print("  [手动发射 | 055-DD-1 → 蓝方伯克舰2 (YJ-18)]")
print("  [手动发射 | 055-DD-2 → 蓝方伯克舰1 (YJ-18)]")
print("  [手动发射 | 055-DD-2 → 蓝方伯克舰2 (YJ-18)]")
print("  [手动发射 | 055-DD → 蓝方补给舰 (YJ-18)]")
print("  [手动发射 | J16-3 → 蓝方补给舰 (YJ-12)]")
print("  [手动发射 | 039C-SUB-1 → 蓝方补给舰 (YJ-83)]")
print("========================================")
