-- ============================================================
-- 消耗与诱歼作战方案 (Attrition & Decoy Kill Operation)
-- Plan ID: plan_strategy_C
-- Side: Red (红方)
-- Generated by CMO Lua SKILL
-- ============================================================
Tool_EmulateNoConsole(true)

-- ============================================================
-- SECTION 1: MCP-Verified DBID Constants
-- ============================================================
-- Ship DBIDs (MCP: query_dbid "Type 055 Renhai" / "Type 052D Luyang III")
local DBID_055_RENHAI     = 2834
local DBID_052D_LUYANG    = 2296

-- Submarine DBID (MCP: query_dbid "Type 039C Yuan" -> SQL DataSubmarine)
local DBID_039C_YUAN      = 695

-- Aircraft DBIDs (MCP: query_dbid "J-16 Flying Shark" / "J-15D Growler Shark")
-- J-16: DBID 2853 (PLANAF, Su-30MKK Copy)
-- J-15D: DBID 4957 (PLANAF, EW variant; EA-18G not available for China side)
local DBID_J16             = 2853
local DBID_J15D_EW         = 4957

-- LoadoutIDs (MCP: read_query DataAircraftLoadouts WHERE ComponentID=...)
-- J-16 Loadout: ID 1821
-- J-15D EW Loadout: ID 1210
local LOADOUT_J16          = 1821
local LOADOUT_J15D_EW      = 1210

-- ============================================================
-- SECTION 2: Scenario Setup & Doctrine
-- ============================================================
-- Ensure Red side exists (fallback if not in base scenario)
local ok, existingSide = pcall(VP_GetSide, {Side = 'Red'})
if not (ok and existingSide) then
    local _, err = pcall(ScenEdit_AddSide, {name = 'Red', color = '255,0,0'})
    if not _ then
        print("Warning: Could not create Red side: " .. tostring(err))
    end
end

-- Ensure Blue side posture
local ok2, blueSide = pcall(VP_GetSide, {Side = 'Blue'})
if ok2 and blueSide then
    ScenEdit_SetSidePosture('Red', 'Blue', 'H')
end

-- Red side doctrine: aggressive posture
ScenEdit_SetDoctrine({side = 'Red'}, {
    weapon_control_status_air        = 0,   -- Free
    weapon_control_status_surface    = 0,   -- Free
    weapon_control_status_subsurface = 0,   -- Free
    ignore_plotted_course            = 'no',
    use_nuclear_weapons              = 'no',
})

-- ============================================================
-- SECTION 3: Red Unit Creation
-- ============================================================

-- === RED-055 (red_ddg_1): Type 055 Renhai Destroyer ===
-- Role: Surface decoy, bait enemy radar
local ok, unit = pcall(ScenEdit_AddUnit, {
    side        = 'Red',
    type        = 'Ship',
    name        = 'RED-055 #1',
    dbid        = DBID_055_RENHAI,
    latitude    = 30.25,
    longitude    = 124.75,
    heading     = 135,
    speed       = 10,
    proficiency = 'Veteran',
})
if ok then
    ScenEdit_SetKeyValue('RED_055_GUID', unit.guid)
    print("Created RED-055 #1, GUID: " .. unit.guid)
else
    print("Error creating RED-055 #1: " .. tostring(unit))
end

-- === RED-052D (red_ddg_2): Type 052D Luyang III Destroyer ===
local ok2, unit2 = pcall(ScenEdit_AddUnit, {
    side        = 'Red',
    type        = 'Ship',
    name        = 'RED-052D #1',
    dbid        = DBID_052D_LUYANG,
    latitude    = 29.75,
    longitude    = 125.25,
    heading     = 90,
    speed       = 20,
    proficiency = 'Veteran',
})
if ok2 then
    ScenEdit_SetKeyValue('RED_052D_GUID', unit2.guid)
    print("Created RED-052D #1, GUID: " .. unit2.guid)
else
    print("Error creating RED-052D #1: " .. tostring(unit2))
end

-- === RED-SUB (red_sub_1): Type 039C Yuan Submarine ===
-- Submerged at 60m depth
local ok3, unit3 = pcall(ScenEdit_AddUnit, {
    side        = 'Red',
    type        = 'Submarine',
    name        = 'RED-SUB #1',
    dbid        = DBID_039C_YUAN,
    latitude    = 30.0,
    longitude    = 126.0,
    altitude    = 60,        -- 60m depth (negative altitude in CMO = submerged)
    heading     = 0,
    speed       = 5,
    proficiency = 'Veteran',
})
if ok3 then
    ScenEdit_SetKeyValue('RED_SUB_GUID', unit3.guid)
    print("Created RED-SUB #1, GUID: " .. unit3.guid)
else
    print("Error creating RED-SUB #1: " .. tostring(unit3))
end

-- === RED-J16 (red_ac_1): J-16 Flying Shark Strike Aircraft ===
local ok4, unit4 = pcall(ScenEdit_AddUnit, {
    side        = 'Red',
    type        = 'Aircraft',
    name        = 'RED-J16 #1',
    dbid        = DBID_J16,
    LoadoutID   = LOADOUT_J16,
    latitude    = 29.0,
    longitude    = 123.5,
    altitude    = 7620,
    heading     = 0,
    speed       = 200,
    proficiency = 'Veteran',
})
if ok4 then
    ScenEdit_SetKeyValue('RED_J16_GUID', unit4.guid)
    print("Created RED-J16 #1, GUID: " .. unit4.guid)
else
    print("Error creating RED-J16 #1: " .. tostring(unit4))
end

-- === RED-J15D-EW (red_ew_1): J-15D Growler Shark EW Aircraft ===
-- Note: EA-18G Growler (US) not available for China side.
-- Using J-15D Growler Shark (DBID 4957, PLANAF EW variant) as substitute.
local ok5, unit5 = pcall(ScenEdit_AddUnit, {
    side        = 'Red',
    type        = 'Aircraft',
    name        = 'RED-J15D-EW #1',
    dbid        = DBID_J15D_EW,
    LoadoutID   = LOADOUT_J15D_EW,
    latitude    = 28.5,
    longitude    = 124.0,
    altitude    = 9144,
    heading     = 90,
    speed       = 250,
    proficiency = 'Veteran',
})
if ok5 then
    ScenEdit_SetKeyValue('RED_J15D_EW_GUID', unit5.guid)
    print("Created RED-J15D-EW #1, GUID: " .. unit5.guid)
else
    print("Error creating RED-J15D-EW #1: " .. tostring(unit5))
end

-- ============================================================
-- SECTION 4: Reference Points (Patrol Zones & Attack Positions)
-- ============================================================

-- Phase 1 Decoy Zone RPs
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Decoy-1', latitude = 30.25,  longitude = 124.75, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Decoy-2', latitude = 29.75,  longitude = 125.25, highlighted = false})

-- Phase 2 EW Station RPs
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-EW-1', latitude = 28.8,  longitude = 125.5, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-EW-2', latitude = 29.1,  longitude = 126.3, highlighted = false})

-- Phase 3 Strike Approach RPs
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Attack-1', latitude = 28.833, longitude = 126.333, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Attack-2', latitude = 28.5,   longitude = 126.667, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Attack-3', latitude = 28.167, longitude = 126.833, highlighted = false})

-- Phase 4 Withdrawal RPs
ScenEdit_AddReferencePoint({side = 'Red', name = 'RP-Withdraw-1', latitude = 29.0, longitude = 127.0, highlighted = false})

-- Blue Target RPs (enemy positions)
ScenEdit_AddReferencePoint({side = 'Red', name = 'TGT-BLUE-DD1', latitude = 28.833, longitude = 126.333, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'TGT-BLUE-DD2', latitude = 28.5,   longitude = 126.667, highlighted = false})
ScenEdit_AddReferencePoint({side = 'Red', name = 'TGT-BLUE-AUX', latitude = 28.167, longitude = 126.833, highlighted = false})

-- ============================================================
-- SECTION 5: Missions
-- ============================================================
local T0 = ScenEdit_CurrentTime()
local T0_30M = T0 + (30 * 60)
local T0_60M = T0 + (60 * 60)
local T0_75M = T0 + (75 * 60)
local T0_90M = T0 + (90 * 60)
local T0_105M = T0 + (105 * 60)

-- === Decoy Patrol Mission (Phase 1: 10:00-10:30) ===
local mDecoy = ScenEdit_AddMission('Red', 'Red-Decoy-Patrol', 'patrol', {type = 'naval'})
ScenEdit_SetMission('Red', 'Red-Decoy-Patrol', {
    patrolzone   = {'RP-Decoy-1', 'RP-Decoy-2'},
    onethirdrule = false,
    flightsize   = 2,
    minaircraftreq = 0,
    isactive     = true,
})

-- === EW Support Mission (Phase 2: 10:30-11:00) ===
local mEW = ScenEdit_AddMission('Red', 'Red-EW-Support', 'patrol', {type = 'air'})
ScenEdit_SetMission('Red', 'Red-EW-Support', {
    patrolzone   = {'RP-EW-1', 'RP-EW-2'},
    onethirdrule = false,
    flightsize   = 1,
    minaircraftreq = 1,
    isactive     = true,
})

-- === Anti-Ship Strike Mission (Phase 3: 11:00-11:15) ===
local mStrike = ScenEdit_AddMission('Red', 'Red-AntiShip-Strike', 'strike', {subtype = 'naval'})
ScenEdit_SetMission('Red', 'Red-AntiShip-Strike', {
    targetlist   = {'TGT-BLUE-DD1', 'TGT-BLUE-DD2', 'TGT-BLUE-AUX'},
    flightsize   = 1,
    minaircraftreq = 1,
    isactive     = false,   -- Activated at T0+60M by event
})

-- === Submarine Attack Mission ===
local mSub = ScenEdit_AddMission('Red', 'Red-Sub-Attack', 'strike', {subtype = 'sub'})

-- ============================================================
-- SECTION 6: Phase Events (Time-Triggered)
-- ============================================================

-- ============================================================
-- PHASE 1 EVENT: Surface Decoy Advance (T0)
-- Trigger: Scenario Loaded -> immediate
-- ============================================================
local evPhase1 = ScenEdit_SetEvent('Phase1_DecoyAdvance', {
    mode         = 'add',
    IsRepeatable = false,
    IsActive     = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'ScenLoaded', name = 'OnLoad'})
ScenEdit_SetEventTrigger(evPhase1.guid, {mode = 'add', name = 'OnLoad'})

local phase1Script = [[
local guid = ScenEdit_GetKeyValue('RED_055_GUID')
local guid2 = ScenEdit_GetKeyValue('RED_052D_GUID')
if guid and guid ~= '' then
    -- RED-055: High speed advance toward enemy formation (15 -> 25 kts)
    ScenEdit_SetUnit({guid = guid, speed = 15, heading = 135, autonomous = true})
    ScenEdit_SpecialMessage('Red', '[Phase 1] 055诱饵舰前出诱敌，开启雷达吸引蓝方注意')
end
if guid2 and guid2 ~= '' then
    -- RED-052D: Parallel advance
    ScenEdit_SetUnit({guid = guid2, speed = 20, heading = 90, autonomous = true})
    ScenEdit_SpecialMessage('Red', '[Phase 1] 052D驱逐舰协同前出，编队向蓝方方向机动')
end
ScenEdit_SetKeyValue('phase', '1')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Phase1_DecoyScript', ScriptText = phase1Script})
ScenEdit_SetEventAction(evPhase1.guid, {mode = 'add', name = 'Phase1_DecoyScript'})

-- ============================================================
-- PHASE 2 EVENT: EW Jamming Starts (T0+30M)
-- Trigger: Time = T0 + 30 minutes
-- ============================================================
local evPhase2 = ScenEdit_SetEvent('Phase2_EWJamming', {
    mode         = 'add',
    IsRepeatable = false,
    IsActive     = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+30M', time = T0_30M})
ScenEdit_SetEventTrigger(evPhase2.guid, {mode = 'add', name = 'T0+30M'})

local phase2Script = [[
local ewGuid = ScenEdit_GetKeyValue('RED_J15D_EW_GUID')
if ewGuid and ewGuid ~= '' then
    -- J-15D EW: Move to jamming station, EMCON active
    ScenEdit_SetUnit({guid = ewGuid, speed = 220, heading = 45, altitude = 8000, autonomous = true})
    ScenEdit_SetEMCON('Unit', ewGuid, 'Radar=Active;OECM=Active')
    ScenEdit_SpecialMessage('Red', '[Phase 2] J-15D电子战飞机前出至干扰阵位，实施电磁佯动')
end
ScenEdit_SetKeyValue('phase', '2')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Phase2_EWScript', ScriptText = phase2Script})
ScenEdit_SetEventAction(evPhase2.guid, {mode = 'add', name = 'Phase2_EWScript'})

-- ============================================================
-- PHASE 3 EVENT: Strike Aircraft Launch (T0+60M)
-- Trigger: Time = T0 + 60 minutes
-- ============================================================
local evPhase3 = ScenEdit_SetEvent('Phase3_StrikeLaunch', {
    mode         = 'add',
    IsRepeatable = false,
    IsActive     = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+60M', time = T0_60M})
ScenEdit_SetEventTrigger(evPhase3.guid, {mode = 'add', name = 'T0+60M'})

local phase3Script = [[
-- Activate strike mission
ScenEdit_SetMission('Red', 'Red-AntiShip-Strike', {isactive = true})

local j16Guid = ScenEdit_GetKeyValue('RED_J16_GUID')
if j16Guid and j16Guid ~= '' then
    -- J-16: Descend to low altitude, high speed approach
    ScenEdit_SetUnit({guid = j16Guid, speed = 300, heading = 90, altitude = 100, autonomous = true})
    ScenEdit_SpecialMessage('Red', '[Phase 3] J-16战斗机低空突防，向蓝方舰船目标接近')
end

local subGuid = ScenEdit_GetKeyValue('RED_SUB_GUID')
if subGuid and subGuid ~= '' then
    -- Submarine: Rise to periscope depth for attack
    ScenEdit_SetUnit({guid = subGuid, speed = 8, altitude = 10, autonomous = true})
    ScenEdit_SpecialMessage('Red', '[Phase 3] 039C潜艇上浮至攻击阵位，准备发射反舰导弹')
end

ScenEdit_SetKeyValue('phase', '3')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Phase3_StrikeScript', ScriptText = phase3Script})
ScenEdit_SetEventAction(evPhase3.guid, {mode = 'add', name = 'Phase3_StrikeScript'})

-- ============================================================
-- PHASE 3b EVENT: J-16 Missile Launch (T0+65M)
-- Trigger: Time = T0 + 65 minutes
-- ============================================================
local evPhase3b = ScenEdit_SetEvent('Phase3b_J16Missiles', {
    mode         = 'add',
    IsRepeatable = false,
    IsActive     = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+65M', time = T0_60M + (5 * 60)})
ScenEdit_SetEventTrigger(evPhase3b.guid, {mode = 'add', name = 'T0+65M'})

local phase3bScript = [[
local j16Guid = ScenEdit_GetKeyValue('RED_J16_GUID')
if j16Guid and j16Guid ~= '' then
    -- J-16 fires YJ-83 anti-ship missiles at blue destroyers
    -- Target 1: Blue DDG-1 (lat 28.833, lon 126.333)
    -- Target 2: Blue DDG-2 (lat 28.5, lon 126.667)
    -- Note: CMO does not support programmatic weapon launch.
    -- This event triggers the strike mission and notifies the player.
    local u = ScenEdit_GetUnit({guid = j16Guid})
    if u then
        ScenEdit_SpecialMessage('Red', '[Phase 3b] J-16发射YJ-83反舰导弹齐射，攻击蓝方驱逐舰群')
    end
end
ScenEdit_SetKeyValue('phase', '3b')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Phase3b_MissileScript', ScriptText = phase3bScript})
ScenEdit_SetEventAction(evPhase3b.guid, {mode = 'add', name = 'Phase3b_MissileScript'})

-- ============================================================
-- PHASE 3c EVENT: Submarine Missile Launch (T0+65M)
-- Trigger: Time = T0 + 65 minutes
-- ============================================================
local evPhase3c = ScenEdit_SetEvent('Phase3c_SubMissiles', {
    mode         = 'add',
    IsRepeatable = false,
    IsActive     = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+65M_Sub', time = T0_60M + (5 * 60)})
ScenEdit_SetEventTrigger(evPhase3c.guid, {mode = 'add', name = 'T0+65M_Sub'})

local phase3cScript = [[
local subGuid = ScenEdit_GetKeyValue('RED_SUB_GUID')
if subGuid and subGuid ~= '' then
    ScenEdit_SpecialMessage('Red', '[Phase 3c] 039C潜艇发射YJ-18反舰导弹，对蓝方编队实施侧向打击')
end
ScenEdit_SetKeyValue('phase', '3c')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Phase3c_SubMissileScript', ScriptText = phase3cScript})
ScenEdit_SetEventAction(evPhase3c.guid, {mode = 'add', name = 'Phase3c_SubMissileScript'})

-- ============================================================
-- PHASE 4 EVENT: Surface Units Withdraw (T0+75M)
-- Trigger: Time = T0 + 75 minutes
-- ============================================================
local evPhase4 = ScenEdit_SetEvent('Phase4_Withdraw', {
    mode         = 'add',
    IsRepeatable = false,
    IsActive     = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+75M', time = T0_75M})
ScenEdit_SetEventTrigger(evPhase4.guid, {mode = 'add', name = 'T0+75M'})

local phase4Script = [[
local guid = ScenEdit_GetKeyValue('RED_055_GUID')
local guid2 = ScenEdit_GetKeyValue('RED_052D_GUID')
local ewGuid = ScenEdit_GetKeyValue('RED_J15D_EW_GUID')
if guid and guid ~= '' then
    ScenEdit_SetUnit({guid = guid, speed = 25, heading = 315, autonomous = true})
    ScenEdit_SpecialMessage('Red', '[Phase 4] 055诱饵舰高速撤离，脱离接触')
end
if guid2 and guid2 ~= '' then
    ScenEdit_SetUnit({guid = guid2, speed = 25, heading = 315, autonomous = true})
end
if ewGuid and ewGuid ~= '' then
    ScenEdit_SetUnit({guid = ewGuid, speed = 350, heading = 270, autonomous = true})
    ScenEdit_SpecialMessage('Red', '[Phase 4] J-15D电子战飞机掩护突击编队撤离')
end
ScenEdit_SetKeyValue('phase', '4')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Phase4_WithdrawScript', ScriptText = phase4Script})
ScenEdit_SetEventAction(evPhase4.guid, {mode = 'add', name = 'Phase4_WithdrawScript'})

-- ============================================================
-- ASSESSMENT EVENT: Battle Assessment (T0+90M)
-- Trigger: Time = T0 + 90 minutes
-- ============================================================
local evAssess = ScenEdit_SetEvent('Assessment_BattleResult', {
    mode         = 'add',
    IsRepeatable = false,
    IsActive     = true,
})
ScenEdit_SetTrigger({mode = 'add', type = 'Time', name = 'T0+90M', time = T0_90M})
ScenEdit_SetEventTrigger(evAssess.guid, {mode = 'add', name = 'T0+90M'})

local assessScript = [[
-- Check damage on Blue side units
local okBlue, blueSide = pcall(VP_GetSide, {Side = 'Blue'})
local totalDamage = 0
local unitCount = 0
if okBlue and blueSide then
    for _, u in ipairs(blueSide.units or {}) do
        unitCount = unitCount + 1
        local dmg = u.damage or 0
        totalDamage = totalDamage + dmg
    end
end
local avgDamage = (unitCount > 0) and math.floor(totalDamage / unitCount) or 0
ScenEdit_SpecialMessage('Red', '[评估] 战斗阶段完成。蓝方单位受损率约: ' .. avgDamage .. '%')
ScenEdit_SetKeyValue('phase', 'assessed')
]]
ScenEdit_SetAction({mode = 'add', type = 'LuaScript', name = 'Assessment_Script', ScriptText = assessScript})
ScenEdit_SetEventAction(evAssess.guid, {mode = 'add', name = 'Assessment_Script'})

-- ============================================================
-- POSTURE & EMCON
-- ============================================================
-- Red ships: Active radar to act as decoy
local guid = ScenEdit_GetKeyValue('RED_055_GUID')
if guid and guid ~= '' then
    ScenEdit_SetEMCON('Unit', guid, 'Radar=Active;Sonar=Active;OECM=Active')
end
local guid2 = ScenEdit_GetKeyValue('RED_052D_GUID')
if guid2 and guid2 ~= '' then
    ScenEdit_SetEMCON('Unit', guid2, 'Radar=Active;Sonar=Active;OECM=Active')
end

-- Red Sub: Passive sonar
local subGuid = ScenEdit_GetKeyValue('RED_SUB_GUID')
if subGuid and subGuid ~= '' then
    ScenEdit_SetEMCON('Unit', subGuid, 'Sonar=Passive')
end

-- ============================================================
-- PRINT SUMMARY
-- ============================================================
print('============================================')
print('消耗与诱歼作战方案 - Red Force Setup Complete')
print('  Plan: plan_strategy_C')
print('  Units Created:')
print('    - RED-055 #1 (Type 055 Renhai)    DBID=' .. DBID_055_RENHAI)
print('    - RED-052D #1 (Type 052D Luyang)  DBID=' .. DBID_052D_LUYANG)
print('    - RED-SUB #1 (Type 039C Yuan)     DBID=' .. DBID_039C_YUAN)
print('    - RED-J16 #1 (J-16 Flying Shark)   DBID=' .. DBID_J16 .. ' Loadout=' .. LOADOUT_J16)
print('    - RED-J15D-EW #1 (J-15D Growler)   DBID=' .. DBID_J15D_EW .. ' Loadout=' .. LOADOUT_J15D_EW)
print('  Phase Timeline:')
print('    T0       : Surface decoy advance')
print('    T0+30M   : EW jamming begins')
print('    T0+60M   : Strike aircraft launch')
print('    T0+65M   : Missile launch')
print('    T0+75M   : Withdrawal')
print('    T0+90M   : Battle assessment')
print('============================================')
ScenEdit_SpecialMessage('Red', '消耗与诱歼作战方案初始化完成，红方各平台就位。')
