"""Deterministic Lua renderer for Phase 2 execution plans."""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Mapping

from cmo_lua_agent.generation.system_instrumentation import SystemInstrumentationBundle

from cmo_lua_agent.generation.runtime_models import (
    ExecutionPlan,
    LuaRuntimeProfile,
    LuaSourceSpan,
    Operation,
    RenderedLua,
    canonical_sha256,
)


RENDERER_VERSION = "1.0.0"

_INITIALIZATION_PRIMITIVES = frozenset(
    {
        "ensure_sides", "configure_side_state", "ensure_ship", "ensure_aircraft",
        "configure_aircraft", "configure_ship_inventory", "prepare_target_contact",
    }
)


@dataclass(frozen=True, slots=True)
class _RenderContext:
    unit_names: Mapping[str, str]
    unit_sides: Mapping[str, str]
    routes: Mapping[str, Mapping[str, Any]]
    air_targets: Mapping[str, Mapping[str, Any]]


class LuaRenderer:
    def __init__(self, *, renderer_version: str = RENDERER_VERSION) -> None:
        self._renderer_version = renderer_version

    def render(
        self,
        *,
        plan: ExecutionPlan,
        runtime: LuaRuntimeProfile,
        instrumentation: SystemInstrumentationBundle | None = None,
    ) -> RenderedLua:
        context = _build_context(plan)
        lines: list[str] = []
        source_map: dict[str, LuaSourceSpan] = {}

        self._append_header(lines=lines, plan=plan, runtime=runtime, instrumentation=instrumentation)
        self._append_runtime_helpers(lines=lines, runtime=runtime)

        instrumentation_inserted = False
        for index, operation in enumerate(plan.operations):
            start_line = len(lines) + 1
            lines.extend(
                self._render_operation(
                    operation,
                    plan=plan,
                    runtime=runtime,
                    context=context,
                )
            )
            end_line = len(lines)
            source_map[operation.operation_id] = LuaSourceSpan(
                start_line=start_line,
                end_line=end_line,
            )
            if instrumentation is not None and not instrumentation_inserted:
                next_operation = plan.operations[index + 1] if index + 1 < len(plan.operations) else None
                if operation.primitive_type in _INITIALIZATION_PRIMITIVES and (
                    next_operation is None or next_operation.primitive_type not in _INITIALIZATION_PRIMITIVES
                ):
                    start_line = len(lines) + 1
                    lines.extend(instrumentation.content.rstrip("\n").split("\n"))
                    lines.append("")
                    source_map["system.native_score"] = LuaSourceSpan(start_line=start_line, end_line=len(lines) - 1)
                    instrumentation_inserted = True

        if instrumentation is not None and not instrumentation_inserted:
            raise ValueError("instrumentation_insertion_point_missing: no scenario initialization operation")

        lines.extend(
            [
                "phase3_collect_final_state()",
                (
                    "runtime_log('Phase 2 script scheduled')"
                    if instrumentation is None
                    else "runtime_log('Phase 3.2 scored script scheduled')"
                ),
            ]
        )

        content = "\n".join(lines) + "\n"
        metadata = {
            "plan_schema_version": plan.plan_schema_version,
            "compiler_version": plan.compiler_version,
            "renderer_version": self._renderer_version,
            "runtime_id": runtime.runtime_id,
            "runtime_version": runtime.runtime_version,
            "scenario_id": plan.scenario_id,
            "plan_checksum": plan.checksum,
            "runtime_checksum": canonical_sha256(runtime.to_dict()),
        }
        return RenderedLua(
            content=content,
            metadata=metadata,
            source_map=source_map,
        )

    def _append_header(
        self,
        *,
        lines: list[str],
        plan: ExecutionPlan,
        runtime: LuaRuntimeProfile,
        instrumentation: SystemInstrumentationBundle | None,
    ) -> None:
        operation_events = {
            operation.operation_id: runtime.event_name(
                scenario_id=plan.scenario_id,
                operation_id=operation.operation_id,
                phase="main",
                attempt=0,
            )
            for operation in plan.operations
        }
        lines.extend(
            [
                (
                    "-- Generated by CMO Lua Agent Phase 2 deterministic renderer"
                    if instrumentation is None
                    else "-- Generated by CMO Lua Agent Phase 3.2 scored deterministic renderer"
                ),
                f"-- scenario_id: {plan.scenario_id}",
                f"-- runtime: {runtime.runtime_id}@{runtime.runtime_version}",
                f"-- plan_checksum: {plan.checksum}",
                *([] if instrumentation is None else [
                    "-- instrumentation: cmo_native_score",
                    f"-- score_spec_checksum: {instrumentation.native_score_compilation.score_spec_checksum}",
                    f"-- native_score_fragment_checksum: {instrumentation.native_score_compilation.fragment_checksum}",
                ]),
                "",
                "local RUNTIME = {}",
                f"RUNTIME.events = {_lua_value(operation_events)}",
                "",
            ]
        )

    def _append_runtime_helpers(
        self,
        *,
        lines: list[str],
        runtime: LuaRuntimeProfile,
    ) -> None:
        lines.extend(
            [
                "local function runtime_log(message)",
                "    print('[P2] ' .. tostring(message))",
                "end",
                "",
                "local function lookup_unit(side, name)",
                "    local ok, unit = pcall(ScenEdit_GetUnit, {side=side, name=name})",
                "    if ok and unit and unit.guid then return unit end",
                "    return nil",
                "end",
                "",
                "local function checked_cmo_call(label, fn, args)",
                "    _errnum_ = 0",
                "    _errmsg_ = ''",
                "    local ok, result = pcall(fn, args)",
                "    local errnum = tonumber(_errnum_) or 0",
                "    local success = ok and result ~= nil and result ~= false and errnum == 0",
                "    runtime_log(label .. ' success=' .. tostring(success) .. ' err=' .. tostring(_errmsg_ or ''))",
                "    return success, result",
                "end",
                "",
                "local function absolute_time_ticks(add_seconds)",
                "    return string.format('%.0f', (ScenEdit_CurrentTime() + add_seconds) * 1e7 + 621355968000000000)",
                "end",
                "",
                "local function schedule_lua(event_name, lua_script, delay_seconds)",
                "    local trigger_name = event_name .. '_trigger'",
                "    local action_name = event_name .. '_action'",
                "    pcall(ScenEdit_SetEvent, event_name, {mode='remove'})",
                "    pcall(ScenEdit_SetAction, {mode='remove', type='LuaScript', name=action_name})",
                "    pcall(ScenEdit_SetTrigger, {mode='remove', type='Time', name=trigger_name})",
                "    local script = table.concat({lua_script, '\\n',",
                "        string.format('ScenEdit_SetEvent(%q,{mode=%q})\\n', event_name, 'remove'),",
                "        string.format('ScenEdit_SetAction({mode=%q,type=%q,name=%q})\\n', 'remove', 'LuaScript', action_name),",
                "        string.format('ScenEdit_SetTrigger({mode=%q,type=%q,name=%q})\\n', 'remove', 'Time', trigger_name),",
                "    })",
                "    pcall(ScenEdit_SetTrigger, {mode='add', type='Time', name=trigger_name, Time=absolute_time_ticks(delay_seconds)})",
                "    pcall(ScenEdit_SetAction, {mode='add', type='LuaScript', name=action_name, ScriptText=script})",
                "    pcall(ScenEdit_SetEvent, event_name, {mode='add', IsActive=true, IsRepeatable=false})",
                "    pcall(ScenEdit_SetEventTrigger, event_name, {mode='add', name=trigger_name})",
                "    pcall(ScenEdit_SetEventAction, event_name, {mode='add', name=action_name})",
                "end",
                "",
                "local function clear_unit_weapons(side, name)",
                "    local unit = lookup_unit(side, name)",
                "    if not unit or not unit.guid then return false end",
                "    for _, mount in ipairs(unit.mounts or {}) do",
                "        for _, weapon in ipairs(mount.mount_weapons or {}) do",
                "            local current = tonumber(weapon.wpn_current) or 0",
                "            if current > 0 then",
                "                pcall(ScenEdit_AddReloadsToUnit, {guid=unit.guid, wpn_dbid=weapon.wpn_dbid, mount_guid=mount.mount_guid, number=current, remove=true})",
                "            end",
                "        end",
                "    end",
                "    return true",
                "end",
                "",
                "local function reload_unit_weapons(side, name, weapon_dbid, quantity)",
                "    pcall(ScenEdit_AddReloadsToUnit, {side=side, unitname=name, wpn_dbid=weapon_dbid, number=quantity})",
                "end",
                "",
                "local function contact_guid(red_side, target_side, target_name)",
                "    local target = lookup_unit(target_side, target_name)",
                "    if not target or not target.guid then return nil end",
                "    pcall(ScenEdit_SetUnit, {guid=target.guid, autodetectable=true})",
                "    pcall(ScenEdit_SetSideOptions, {side=red_side, awareness='OMNI'})",
                "    local ok, side = pcall(VP_GetSide, {Side=red_side})",
                "    if ok and side and type(side.contacts) == 'table' then",
                "        local target_guid = tostring(target.guid):lower()",
                "        for _, contact in ipairs(side.contacts) do",
                "            local actual = contact.actualunitid or contact.actualUnitID or contact.actualunitguid or contact.actualUnitGuid",
                "            if actual and tostring(actual):lower() == target_guid then return contact.guid or contact.Guid end",
                "        end",
                "        for _, contact in ipairs(side.contacts) do",
                "            local name = tostring(contact.name or contact.Name or '')",
                "            if name ~= '' and (name == target_name or name:find(target_name, 1, true)) then return contact.guid or contact.Guid end",
                "        end",
                "    end",
                "    return nil",
                "end",
                "",
                "local function fire_at(attacker_side, target_side, attacker_name, target_name, weapon_dbid, quantity)",
                "    local attacker = lookup_unit(attacker_side, attacker_name)",
                "    if not attacker or not attacker.guid then runtime_log('missing attacker ' .. tostring(attacker_name)); return false end",
                "    local contact = contact_guid(attacker_side, target_side, target_name)",
                "    if not contact then runtime_log('missing contact ' .. tostring(target_name)); return false end",
                "    local opts = {mode='1', weapon=tonumber(weapon_dbid), qty=tonumber(quantity)}",
                "    _errnum_ = 0",
                "    _errmsg_ = ''",
                "    local ok, result = pcall(ScenEdit_AttackContact, attacker.guid, contact, opts)",
                "    local success = ok and result ~= nil and result ~= false and (tonumber(_errnum_) or 0) == 0",
                "    runtime_log('fire ' .. attacker_name .. ' -> ' .. target_name .. ' success=' .. tostring(success) .. ' err=' .. tostring(_errmsg_ or ''))",
                "    return success",
                "end",
                "",
                "local function print_air_state(prefix, unit)",
                "    if not unit then runtime_log(prefix .. ' unit=nil'); return end",
                "    runtime_log(prefix .. ' operating=' .. tostring(unit.isOperating) .. ' ready=' .. tostring(unit.readytime_v) .. ' loadout=' .. tostring(unit.loadoutdbid))",
                "end",
                "",
                "function air_attack_poll(name, target_side, target, weapon_dbid, quantity, return_delay, base_name, attempt)",
                "    local unit = lookup_unit('red', name)",
                "    local target_unit = lookup_unit(target_side, target)",
                "    if not unit or not unit.isOperating then runtime_log('air attack stopped for ' .. tostring(name)); return end",
                "    if not target_unit then pcall(ScenEdit_SetUnit, {guid=unit.guid, rtb=true}); return end",
                "    local ok, range_nm = pcall(Tool_Range, unit.guid, target_unit.guid)",
                "    runtime_log('range poll ' .. name .. ' -> ' .. target .. ' range=' .. tostring(range_nm))",
                "    if ok and range_nm and tonumber(range_nm) <= 80 then",
                "        if fire_at('red', target_side, name, target, weapon_dbid, quantity) then",
                "            local body = string.format('local u=ScenEdit_GetUnit({side=%q,name=%q}); if u and u.guid then ScenEdit_SetUnit({guid=u.guid,base=%q}); ScenEdit_SetUnit({guid=u.guid,rtb=true}) end', 'red', name, base_name)",
                "            schedule_lua(RUNTIME.events['air_rtb_' .. name] or ('evt_air_rtb_' .. name), body, return_delay)",
                "            return",
                "        end",
                "    end",
                f"    if attempt >= {runtime.max_attack_attempts} then pcall(ScenEdit_SetUnit, {{guid=unit.guid, rtb=true}}); return end",
                "    local next_attempt = attempt + 1",
                "    local body = string.format('air_attack_poll(%q,%q,%q,%d,%d,%d,%q,%d)', name, target_side, target, weapon_dbid, quantity, return_delay, base_name, next_attempt)",
                f"    schedule_lua('evt_air_attack_' .. name .. '_' .. tostring(next_attempt), body, {runtime.attack_poll_seconds})",
                "end",
                "",
                "function air_launch_poll(name, target_side, target, mid_lat, mid_lon, app_lat, app_lon, altitude, throttle, weapon_dbid, quantity, return_delay, base_name, attempt)",
                "    local unit = lookup_unit('red', name)",
                "    if not unit then runtime_log('missing aircraft ' .. tostring(name)); return end",
                "    print_air_state('launch poll ' .. tostring(attempt), unit)",
                "    if unit.isOperating then",
                "        checked_cmo_call('Route/' .. name, ScenEdit_SetUnit, {guid=unit.guid, course={{latitude=mid_lat, longitude=mid_lon}, {latitude=app_lat, longitude=app_lon}}, altitude=altitude, throttle=throttle})",
                "        local body = string.format('air_attack_poll(%q,%q,%q,%d,%d,%d,%q,%d)', name, target_side, target, weapon_dbid, quantity, return_delay, base_name, 1)",
                f"        schedule_lua('evt_air_attack_' .. name .. '_1', body, {runtime.attack_poll_seconds})",
                "        return",
                "    end",
                f"    if attempt > {runtime.max_launch_attempts} then runtime_log('launch timeout ' .. name); return end",
                "    checked_cmo_call('ReadyRetry/' .. name, ScenEdit_SetUnit, {guid=unit.guid, timetoready_minutes=0})",
                "    checked_cmo_call('Launch/' .. name, ScenEdit_SetUnit, {guid=unit.guid, launch=true})",
                "    local next_attempt = attempt + 1",
                "    local body = string.format('air_launch_poll(%q,%q,%q,%.8f,%.8f,%.8f,%.8f,%d,%q,%d,%d,%d,%q,%d)', name, target_side, target, mid_lat, mid_lon, app_lat, app_lon, altitude, throttle, weapon_dbid, quantity, return_delay, base_name, next_attempt)",
                f"    schedule_lua('evt_air_launch_' .. name .. '_' .. tostring(next_attempt), body, {runtime.launch_poll_seconds})",
                "end",
                "",
                "local function phase3_collect_final_state()",
                "    -- Reserved Phase 3 hook. It is intentionally not an ExecutionPlan operation.",
                "end",
                "",
            ]
        )

    def _render_operation(
        self,
        operation: Operation,
        *,
        plan: ExecutionPlan,
        runtime: LuaRuntimeProfile,
        context: _RenderContext,
    ) -> list[str]:
        event_name = runtime.event_name(
            scenario_id=plan.scenario_id,
            operation_id=operation.operation_id,
            phase="main",
            attempt=0,
        )
        body = _OPERATION_RENDERERS.get(operation.primitive_type, _render_generic)(
            operation,
            event_name,
            context,
        )
        return [
            f"-- BEGIN OP {operation.operation_id}",
            f"-- primitive: {operation.primitive_type}",
            f"-- source: {operation.source_strategy_path}",
            *body,
            f"-- END OP {operation.operation_id}",
            "",
        ]


def _render_generic(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    return [
        f"runtime_log('operation {operation.operation_id} event {event_name}')",
    ]


def _render_ensure_sides(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    side_ids = operation.parameters["side_ids"]
    lines = [f"runtime_log('operation {operation.operation_id} event {event_name}')"]
    for side_id in side_ids:
        lines.append(f"pcall(ScenEdit_AddSide, {{name={_lua_value(side_id)}}})")
    return lines


def _render_side_state(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    side_ids = operation.parameters["side_ids"]
    posture = operation.parameters["posture"]
    awareness = operation.parameters["awareness"]
    wcs = operation.parameters["weapon_control_status"]
    lines = [f"runtime_log('operation {operation.operation_id} event {event_name}')"]
    if len(side_ids) >= 2:
        first, second = side_ids[0], side_ids[1]
        lines.append(f"pcall(ScenEdit_SetSidePosture, {_lua_value(first)}, {_lua_value(second)}, {_lua_value(posture)})")
        lines.append(f"pcall(ScenEdit_SetSidePosture, {_lua_value(second)}, {_lua_value(first)}, {_lua_value(posture)})")
    for side_id in side_ids:
        lines.append(f"pcall(ScenEdit_SetSideOptions, {{side={_lua_value(side_id)}, awareness={_lua_value(awareness)}}})")
        lines.append(
            "pcall(ScenEdit_SetDoctrine, "
            + f"{{side={_lua_value(side_id)}}}, "
            + "{weapon_control_status_air="
            + _lua_value(wcs)
            + ", weapon_control_status_surface="
            + _lua_value(wcs)
            + ", weapon_control_status_subsurface="
            + _lua_value(wcs)
            + "})"
        )
    return lines


def _render_ensure_ship(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    parameters = operation.parameters
    return [
        f"runtime_log('operation {operation.operation_id} event {event_name}')",
        f"if not lookup_unit({_lua_value(parameters['side_id'])}, {_lua_value(parameters['name'])}) then",
        "    checked_cmo_call('AddShip', ScenEdit_AddUnit, {",
        "        type='Ship',",
        f"        side={_lua_value(parameters['side_id'])},",
        f"        name={_lua_value(parameters['name'])},",
        f"        dbid={_lua_value(parameters['dbid'])},",
        f"        latitude={_lua_value(parameters.get('latitude'))},",
        f"        longitude={_lua_value(parameters.get('longitude'))},",
        f"        heading={_lua_value(parameters.get('heading'))},",
        f"        speed={_lua_value(parameters.get('speed'))},",
        "        proficiency='Veteran',",
        "    })",
        "end",
        f"local unit = lookup_unit({_lua_value(parameters['side_id'])}, {_lua_value(parameters['name'])})",
        "if unit and unit.guid then pcall(ScenEdit_SetEMCON, 'Unit', unit.guid, 'Radar=Active') end",
    ]


def _render_ensure_aircraft(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    parameters = operation.parameters
    base_name = context.unit_names.get(str(parameters.get("base_unit_id")), "")
    return [
        f"runtime_log('operation {operation.operation_id} event {event_name}')",
        f"if not lookup_unit({_lua_value(parameters['side_id'])}, {_lua_value(parameters['name'])}) then",
        "    checked_cmo_call('AddAircraft', ScenEdit_AddUnit, {",
        "        type='Air',",
        f"        side={_lua_value(parameters['side_id'])},",
        f"        unitname={_lua_value(parameters['name'])},",
        f"        dbid={_lua_value(parameters['dbid'])},",
        f"        loadoutid={_lua_value(parameters.get('loadout_id'))},",
        f"        base={_lua_value(base_name)},",
        "        proficiency='Veteran',",
        "    })",
        "end",
    ]


def _render_configure_aircraft(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    parameters = operation.parameters
    aircraft_name = context.unit_names[str(parameters["aircraft_id"])]
    base_name = context.unit_names[str(parameters["base_unit_id"])]
    return [
        f"runtime_log('operation {operation.operation_id} event {event_name}')",
        f"local unit = lookup_unit('red', {_lua_value(aircraft_name)})",
        "if unit and unit.guid and not unit.isOperating then",
        f"    checked_cmo_call('SetBase/' .. {_lua_value(aircraft_name)}, ScenEdit_SetUnit, {{guid=unit.guid, base={_lua_value(base_name)}}})",
        f"    checked_cmo_call('SetLoadout/' .. {_lua_value(aircraft_name)}, ScenEdit_SetLoadout, {{unitname=unit.guid, LoadoutID={_lua_value(parameters.get('loadout_id'))}, TimeToReady_Minutes=0, IgnoreMagazines=true}})",
        "    checked_cmo_call('ReadyNow', ScenEdit_SetUnit, {guid=unit.guid, timetoready_minutes=0})",
        "end",
    ]


def _render_inventory(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    parameters = operation.parameters
    unit_id = str(parameters["unit_id"])
    unit_name = context.unit_names[unit_id]
    side = context.unit_sides[unit_id]
    lines = [
        f"runtime_log('operation {operation.operation_id} event {event_name}')",
        f"clear_unit_weapons({_lua_value(side)}, {_lua_value(unit_name)})",
    ]
    for weapon in parameters["weapon_inventory"]:
        lines.append(
            f"reload_unit_weapons({_lua_value(side)}, {_lua_value(unit_name)}, "
            f"{_lua_value(weapon['weapon_dbid'])}, {_lua_value(weapon['max_quantity'])})"
        )
    return lines


def _render_contact(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    target_id = str(operation.parameters["target_id"])
    target_name = context.unit_names[target_id]
    target_side = context.unit_sides[target_id]
    return [
        f"runtime_log('operation {operation.operation_id} event {event_name}')",
        f"local target = lookup_unit({_lua_value(target_side)}, {_lua_value(target_name)})",
        "if target and target.guid then pcall(ScenEdit_SetUnit, {guid=target.guid, autodetectable=true}) end",
    ]


def _render_ship_attack(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    parameters = operation.parameters
    shooter_id = str(parameters["shooter_id"])
    target_id = str(parameters["target_ids"][0])
    body = (
        "fire_at("
        + ",".join(
            (
                _lua_value(context.unit_sides[shooter_id]),
                _lua_value(context.unit_sides[target_id]),
                _lua_value(context.unit_names[shooter_id]),
                _lua_value(context.unit_names[target_id]),
                str(parameters["weapon_dbid"]),
                str(parameters["fire_quantity"]),
            )
        )
        + ")"
    )
    return [
        f"runtime_log('operation {operation.operation_id} event {event_name}')",
        f"schedule_lua({_lua_value(event_name)}, {_lua_value(body)}, {_lua_value(parameters['delay_seconds'])})",
    ]


def _render_air_launch(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    sortie_id = str(operation.parameters["sortie_id"])
    route = context.routes[sortie_id]
    attack = context.air_targets[sortie_id]
    aircraft_id = str(operation.parameters["aircraft_id"])
    aircraft_name = context.unit_names[aircraft_id]
    target_id = str(attack["target_id"])
    target_name = context.unit_names[target_id]
    base_name = context.unit_names[str(operation.parameters["base_unit_id"])]
    body = (
        "air_launch_poll("
        + ",".join(
            (
                _lua_value(aircraft_name),
                _lua_value(context.unit_sides[target_id]),
                _lua_value(target_name),
                str(route["mid_lat"]),
                str(route["mid_lon"]),
                str(route["app_lat"]),
                str(route["app_lon"]),
                str(route["altitude_meters"]),
                _lua_value(route["throttle"]),
                str(attack["weapon_dbid"]),
                str(attack["fire_quantity"]),
                str(route["return_delay_seconds"]),
                _lua_value(base_name),
                "1",
            )
        )
        + ")"
    )
    return [
        f"runtime_log('operation {operation.operation_id} event {event_name}')",
        f"schedule_lua({_lua_value(event_name)}, {_lua_value(body)}, 5)",
    ]


def _render_noop(
    operation: Operation,
    event_name: str,
    context: _RenderContext,
) -> list[str]:
    return [
        f"runtime_log('operation {operation.operation_id} event {event_name}')",
    ]


_OPERATION_RENDERERS = {
    "ensure_sides": _render_ensure_sides,
    "configure_side_state": _render_side_state,
    "ensure_ship": _render_ensure_ship,
    "ensure_aircraft": _render_ensure_aircraft,
    "configure_aircraft": _render_configure_aircraft,
    "configure_ship_inventory": _render_inventory,
    "prepare_target_contact": _render_contact,
    "schedule_ship_attack": _render_ship_attack,
    "request_aircraft_launch": _render_air_launch,
    "wait_aircraft_airborne": _render_noop,
    "set_aircraft_route": _render_noop,
    "wait_aircraft_attack_range": _render_noop,
    "aircraft_attack": _render_noop,
    "return_aircraft_to_base": _render_noop,
}


def _build_context(plan: ExecutionPlan) -> _RenderContext:
    unit_names: dict[str, str] = {}
    unit_sides: dict[str, str] = {}
    routes: dict[str, dict[str, Any]] = {}
    air_targets: dict[str, dict[str, Any]] = {}

    for operation in plan.operations:
        parameters = operation.parameters
        if operation.primitive_type in {"ensure_ship", "ensure_aircraft"}:
            unit_id = str(parameters["unit_id"])
            unit_names[unit_id] = str(parameters["name"])
            unit_sides[unit_id] = str(parameters["side_id"])
        elif operation.primitive_type == "set_aircraft_route":
            route = parameters["route"]
            if len(route) < 2:
                continue
            routes[str(parameters["sortie_id"])] = {
                "mid_lat": route[0]["latitude"],
                "mid_lon": route[0]["longitude"],
                "app_lat": route[1]["latitude"],
                "app_lon": route[1]["longitude"],
                "altitude_meters": parameters["altitude_meters"],
                "throttle": parameters["throttle"],
                "return_delay_seconds": 600,
            }
        elif operation.primitive_type == "aircraft_attack":
            sortie_id = str(parameters["sortie_id"])
            air_targets[sortie_id] = {
                "target_id": parameters["target_ids"][0],
                "weapon_dbid": parameters["weapon_dbid"],
                "fire_quantity": parameters["fire_quantity"],
            }
            if sortie_id in routes:
                routes[sortie_id]["return_delay_seconds"] = parameters["return_delay_seconds"]
    return _RenderContext(
        unit_names=unit_names,
        unit_sides=unit_sides,
        routes=routes,
        air_targets=air_targets,
    )


def _lua_value(value: Any) -> str:
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, Mapping):
        pairs = [
            f"[{_lua_value(key)}]={_lua_value(item)}"
            for key, item in sorted(value.items())
        ]
        return "{" + ", ".join(pairs) + "}"
    if isinstance(value, (list, tuple)):
        return "{" + ", ".join(_lua_value(item) for item in value) + "}"
    raise TypeError(f"unsupported Lua value: {type(value).__name__}")
